package org.geogebra.common.exam.restrictions;

public enum ExamFeatureRestriction {
	/** APPS-4866 */
	DATA_TABLE_REGRESSION,

	/** APPS_5751 */
	AUTOMATIC_GRAPH_SELECTION_FOR_FUNCTIONS,

	/** APPS-5926, APPS-6088, APPS-6315 */
	HIDE_CALCULATED_EQUATION,

	/** APPS-6308 */
	HIDE_SPECIAL_POINTS,

	/** APPS-6088 */
	RESTRICT_CHANGING_EQUATION_FORM,

	/** APPS-5929 */
	RATIONALIZATION,

	/** APPS-5929 */
	SURD,

	/** APPS-6310 */
	SPREADSHEET,

	/** APPS-6519 */
	DISABLE_MIXED_NUMBERS
}
