package org.geogebra.common.properties;

/**
 * This enum represents resources that are used by this package.
 */
public enum PropertyResource {

	/* Icons for the grid style property */
	ICON_CARTESIAN, ICON_CARTESIAN_MINOR, ICON_POLAR, ICON_ISOMETRIC, ICON_DOTS,

	/* Icons for buttons */
	ICON_STANDARD_VIEW, ICON_ZOOM_TO_FIT, ICON_RELOAD_AR, ICON_AR_FIT_THICKNESS,

	/* Icons for 3D view projection type */
	ICON_PROJECTION_PARALLEL, ICON_PROJECTION_PERSPECTIVE, ICON_PROJECTION_GLASSES,
	ICON_PROJECTION_OBLIQUE,

	/* Icons for point style */
	ICON_POINT_STYLE_DOT, ICON_POINT_STYLE_CIRCLE, ICON_POINT_STYLE_FILLED_DIAMOND,
	ICON_POINT_STYLE_EMPTY_DIAMOND, ICON_POINT_STYLE_CROSS, ICON_POINT_STYLE_PLUS,
	ICON_POINT_STYLE_NO_OUTLINE, ICON_POINT_STYLE_TRIANGLE_NORTH, ICON_POINT_STYLE_TRIANGLE_SOUTH,
	ICON_POINT_STYLE_TRIANGLE_WEST, ICON_POINT_STYLE_TRIANGLE_EAST,

	/* Icons for line type */
	ICON_LINE_TYPE_FULL, ICON_LINE_TYPE_DASHED_DOTTED, ICON_LINE_TYPE_DASHED_LONG,
	ICON_LINE_TYPE_DOTTED, ICON_LINE_TYPE_DASHED_SHORT,

	/* Icons for probability modes */
	ICON_PROBABILITY_MODE_LEFT, ICON_PROBABILITY_MODE_RIGHT, ICON_PROBABILITY_MODE_INTERVAL,
	ICON_PROBABILITY_MODE_TWO_TAILED,

	/* Icons for filling type */
	ICON_FILLING_HATCHED, ICON_FILLING_DOTTED, ICON_FILLING_CROSSHATCHED, ICON_FILLING_HONEYCOMB,
	ICON_NO_FILLING,

	/* Horizontal alignment type */
	ICON_ALIGNMENT_LEFT, ICON_ALIGNMENT_CENTER, ICON_ALIGNMENT_RIGHT,

	/* Vertical alignment type */
	ICON_ALIGNMENT_BOTTOM, ICON_ALIGNMENT_MIDDLE, ICON_ALIGNMENT_TOP,

	/* Segment start type */
	ICON_SEGMENT_START_DEFAULT, ICON_SEGMENT_START_LINE, ICON_SEGMENT_START_SQUARE_OUTLINE,
	ICON_SEGMENT_START_SQUARE, ICON_SEGMENT_START_ARROW, ICON_SEGMENT_START_ARROW_FILLED,
	ICON_SEGMENT_START_CIRCLE_OUTLINE, ICON_SEGMENT_START_CIRCLE,

	/* Segment end type */
	ICON_SEGMENT_END_DEFAULT, ICON_SEGMENT_END_LINE, ICON_SEGMENT_END_SQUARE_OUTLINE,
	ICON_SEGMENT_END_SQUARE, ICON_SEGMENT_END_ARROW, ICON_SEGMENT_END_ARROW_FILLED,
	ICON_SEGMENT_END_CIRCLE_OUTLINE, ICON_SEGMENT_END_CIRCLE,

	/* Cell border type */
	ICON_CELL_BORDER_ALL, ICON_CELL_BORDER_INNER, ICON_CELL_BORDER_OUTER, ICON_CELL_BORDER_NONE
}
