/*
 * GeoGebra - Dynamic Mathematics for Everyone
 * Copyright (c) GeoGebra GmbH, Altenbergerstr. 69, 4040 Linz, Austria
 * https://www.geogebra.org
 *
 * This file is licensed by GeoGebra GmbH under the EUPL 1.2 licence and
 * may be used under the EUPL 1.2 in compatible projects (see Article 5
 * and the Appendix of EUPL 1.2 for details).
 * You may obtain a copy of the licence at:
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Note: The overall GeoGebra software package is free to use for
 * non-commercial purposes only.
 * See https://www.geogebra.org/license for full licensing details
 */

package org.geogebra.common.properties;

/**
 * This enum represents resources that are used by this package.
 */
public enum PropertyResource {

	/* Icons for the grid style property */
	ICON_CARTESIAN, ICON_CARTESIAN_MINOR, ICON_POLAR, ICON_ISOMETRIC, ICON_DOTS,

	/* Icons for buttons */
	ICON_STANDARD_VIEW, ICON_ZOOM_TO_FIT, ICON_RELOAD_AR, ICON_AR_FIT_THICKNESS,
	ICON_CLEAR_COLOR,

	/* Icons for 3D view projection type */
	ICON_PROJECTION_PARALLEL, ICON_PROJECTION_PERSPECTIVE, ICON_PROJECTION_GLASSES,
	ICON_PROJECTION_OBLIQUE,

	/* Icons for 3D view direction */
	ICON_VIEW_DIRECTION_XY, ICON_VIEW_DIRECTION_XZ, ICON_VIEW_DIRECTION_YZ,

	/* Icons label style */
	ICON_BOLD, ICON_ITALIC, ICON_SERIF, ICON_UNDERLINE,

	/* Icons for axes line style */
	ICON_AXES_LINE_TYPE_FULL, ICON_AXES_LINE_TYPE_ARROW, ICON_AXES_LINE_TYPE_ARROW_FILLED,
	ICON_AXES_LINE_TYPE_TWO_ARROWS, ICON_AXES_LINE_TYPE_TWO_ARROWS_FILLED,

	/* Icons for point style */
	ICON_POINT_STYLE_DOT, ICON_POINT_STYLE_CIRCLE, ICON_POINT_STYLE_FILLED_DIAMOND,
	ICON_POINT_STYLE_EMPTY_DIAMOND, ICON_POINT_STYLE_CROSS, ICON_POINT_STYLE_PLUS,
	ICON_POINT_STYLE_NO_OUTLINE, ICON_POINT_STYLE_TRIANGLE_NORTH, ICON_POINT_STYLE_TRIANGLE_SOUTH,
	ICON_POINT_STYLE_TRIANGLE_WEST, ICON_POINT_STYLE_TRIANGLE_EAST,

	/* Icons for line type */
	ICON_LINE_TYPE_FULL, ICON_LINE_TYPE_DASHED_DOTTED, ICON_LINE_TYPE_DASHED_LONG,
	ICON_LINE_TYPE_DOTTED, ICON_LINE_TYPE_DASHED_SHORT,

	/* Icons for probability modes */
	ICON_PROBABILITY_MODE_LEFT, ICON_PROBABILITY_MODE_RIGHT, ICON_PROBABILITY_MODE_INTERVAL,
	ICON_PROBABILITY_MODE_TWO_TAILED,

	/* Icons for filling type */
	ICON_FILLING_HATCHED, ICON_FILLING_DOTTED, ICON_FILLING_CROSSHATCHED, ICON_FILLING_HONEYCOMB,
	ICON_NO_FILLING, ICON_FILLING_CHESSBOARD, ICON_FILLING_BRICK, ICON_FILLING_SYMBOL,
	ICON_FILLING_WEAVING, ICON_FILLING_IMAGE,

	/* Horizontal alignment type */
	ICON_ALIGNMENT_LEFT, ICON_ALIGNMENT_CENTER, ICON_ALIGNMENT_RIGHT,

	/* Vertical alignment type */
	ICON_ALIGNMENT_BOTTOM, ICON_ALIGNMENT_MIDDLE, ICON_ALIGNMENT_TOP,

	/* Segment start type */
	ICON_SEGMENT_START_DEFAULT, ICON_SEGMENT_START_LINE, ICON_SEGMENT_START_ARROW,
	ICON_SEGMENT_START_CROWS_FOOT, ICON_SEGMENT_START_ARROW_OUTLINE,
	ICON_SEGMENT_START_ARROW_FILLED, ICON_SEGMENT_START_CIRCLE_OUTLINE, ICON_SEGMENT_START_CIRCLE,
	ICON_SEGMENT_START_SQUARE_OUTLINE, ICON_SEGMENT_START_SQUARE,
	ICON_SEGMENT_START_DIAMOND_OUTLINE, ICON_SEGMENT_START_DIAMOND,

	/* Segment end type */
	ICON_SEGMENT_END_DEFAULT, ICON_SEGMENT_END_LINE, ICON_SEGMENT_END_ARROW,
	ICON_SEGMENT_END_CROWS_FOOT, ICON_SEGMENT_END_ARROW_OUTLINE, ICON_SEGMENT_END_ARROW_FILLED,
	ICON_SEGMENT_END_CIRCLE_OUTLINE, ICON_SEGMENT_END_CIRCLE, ICON_SEGMENT_END_SQUARE_OUTLINE,
	ICON_SEGMENT_END_SQUARE, ICON_SEGMENT_END_DIAMOND_OUTLINE, ICON_SEGMENT_END_DIAMOND,

	/* Cell border type */
	ICON_CELL_BORDER_ALL, ICON_CELL_BORDER_INNER, ICON_CELL_BORDER_OUTER, ICON_CELL_BORDER_NONE,

	/* Text border type */
	ICON_BORDER_NONE, ICON_BORDER_THIN, ICON_BORDER_THICK,

	/* Angle style */
	ICON_RIGHT_ANGLE_STYLE_NONE, ICON_RIGHT_ANGLE_STYLE_SQUARE, ICON_RIGHT_ANGLE_STYLE_DOT,
	ICON_RIGHT_ANGLE_STYLE_L,

	ICON_SEGMENT_DECO_1STROKE, ICON_SEGMENT_DECO_2STROKES, ICON_SEGMENT_DECO_3STROKES,
	ICON_SEGMENT_DECO_1ARROW, ICON_SEGMENT_DECO_2ARROWS, ICON_SEGMENT_DECO_3ARROWS,
	ICON_SEGMENT_DECO_NONE,

	ICON_ANGLE_DECO_NONE, ICON_ANGLE_DECO_TWO_ARCS,
	ICON_ANGLE_DECO_THREE_ARCS, ICON_ANGLE_DECO_ONE_TICK, ICON_ANGLE_DECO_TWO_TICKS,
	ICON_ANGLE_DECO_THREE_TICKS, ICON_ANGLE_DECO_ARROW_ANTICLOCKWISE,
	ICON_ANGLE_DECO_ARROW_CLOCKWISE, ICON_VECTOR_DECO_DEFAULT, ICON_VECTOR_DECO_ARROW,

	/* Axis tick style */
	ICON_AXIS_TICK_MAJOR, ICON_AXIS_TICK_MAJOR_AND_MINOR, ICON_AXIS_TICK_OFF

	}
