package org.geogebra.web.html5.sound;


import org.geogebra.common.kernel.geos.GeoFunction;
import org.geogebra.common.main.App;
import org.geogebra.common.sound.FunctionSound;
import org.geogebra.web.html5.sound.WebAudioWrapper.FunctionAudioBuffer;

import com.google.gwt.user.client.Timer;

/**
 * Class for playing function-generated sounds.
 * 
 * @author Laszlo Gal
 *
 */
public final class FunctionSoundW extends FunctionSound implements
		FunctionAudioBuffer {

	private static final int PREBUFFER = 5;
	private static final int SAMPLERATE_DIVIDER = 10;
	public static final FunctionSoundW INSTANCE = new FunctionSoundW();
	private WebAudioWrapper waw = WebAudioWrapper.INSTANCE;
	private byte[] wawBuffer;
	private int writeIdx;
	private Timer timer;
	/**
	 * Constructs instance of FunctionSound
	 * 
	 */
	public FunctionSoundW() {
		super();
		if (WebAudioWrapper.INSTANCE.init()) {
			App.debug("[WEB AUDIO] Initialization is OK.");
		} else {
			App.debug("[WEB AUDIO] Initialization has FAILED.");
		}

		if (!initStreamingAudio(getSampleRate(), getBitDepth())) {
			App.error("Cannot initialize streaming audio");
		}

	}
	/**
	 * Initializes instances of AudioFormat and SourceDataLine
	 * 
	 * @param sampleRate
	 *            = 8000, 16000, 11025, 16000, 22050, or 44100
	 * @param bitDepth
	 *            = 8 or 16
	 * @return
	 */
	protected boolean initStreamingAudio(int sampleRate, int bitDepth) {
		if (super.initStreamingAudio(sampleRate, bitDepth) == false) {
			return false;
		}
		setMaxVolume(1);
		waw.setBuffer(this);
		timer = new Timer() {

			@Override
			public void run() {
				fillBuffer();
			}
		};

		return true;
	}

	/**
	 * Plays a sound generated by the time valued GeoFunction f(t), from t = min
	 * to t = max in seconds. The function is assumed to have range [-1,1] and
	 * will be clipped to this range otherwise.
	 * 
	 * @param geoFunction
	 * @param min
	 * @param max
	 * @param sampleRate
	 * @param bitDepth
	 */

	@Override
	public void playFunction(final GeoFunction geoFunction, final double min,
			final double max, final int sampleRate, final int bitDepth) {
		if (!checkFunction(geoFunction, min, max, sampleRate, bitDepth)) {
			return;
		}
		App.debug("FunctionSound");
		waw.setBuffer(this);
		generateFunctionSound();
	}

	/**
	 * Pauses/resumes sound generation
	 * 
	 * @param doPause
	 */
	public void pause(boolean doPause) {

		if (doPause) {
			setMin(getT());
			stopSound();
		} else {
			playFunction(getF(), getMin(), getMax(), getSampleRate(),
					getBitDepth());
		}
	}

	private boolean stopped = false;



	private void generateFunctionSound() {

		stopped = false;

		// time between samples
		setSamplePeriod(1.0 / getSampleRate());

		// create internal buffer for mathematically generated sound data
		// a small buffer minimizes latency when the function changes
		// dynamically
		// TODO: find optimal buffer size
		waw.start(getSampleRate());

		int frameSetSize = getFrameSetSize();
		if (getBitDepth() == 8) {
			setBuf(new byte[frameSetSize]);
		} else {
			setBuf(new byte[2 * frameSetSize]);
		}

		setT(getMin());
		loadBuffer();
		doFade(getBuf()[0], false);

		waw.write(getBuf(), getBufLength());

		int period = 100;
		App.debug("PERIOD: " + period);
		timer.scheduleRepeating(period);
		timer.run();
	}

	private int getFrameSetSize() {
		return getSampleRate() / SAMPLERATE_DIVIDER;
	}

	private void loadBuffer() {
		if (getBitDepth() == 16) {
			loadBuffer16(getT());
		} else {
			loadBuffer8(getT());
		}

	}

	private void writeBuffer(byte[] buffer) {
		waw.write(buffer, buffer.length);
	}

	public void fillBuffer() {
		if (getT() < getMax() && !stopped) {
			setT(getT() + getSamplePeriod() * getFrameSetSize());
			loadBuffer();
			writeBuffer(getBuf());
		} else if (getBitDepth() == 16 || (getBitDepth() == 8 && !stopped)) {

			doFade(getBuf()[getBufLength() - 1], true);
		}

	}

	private void doFade(short peakValue, boolean isFadeOut) {
		byte[] fadeBuf = getFadeBuffer(peakValue, isFadeOut);
		writeBuffer(fadeBuf);
	}

	/**
	 * Stops function sound
	 */
	public void stopSound() {
		stopped = true;
		timer.cancel();
		waw.stop();

	}


}
