#!/bin/sh
# Deploys the Chrome Application to www.geogebra.org/web/...
# By default, it puts to www.geogebra.org/web/geogebra.crx,
# fine tuning is possible via an extra parameter on command line.

# 1. Setting up environment variables
# Override them if needed by using autobuild.conf
WWW_SERVER_LOGIN=zoltan@www.geogebra.org
GGBWEBDIR=/Library/WebServer/GeoGebra/web
APPNAME=geogebra

test -r autobuild.conf && . ./autobuild.conf && echo "* Using autobuild.conf for overriding defaults"

TARGET=$1

# 2. Updating war/web to www.geogebra.org/web/...
echo "Copying $APPNAME.crx to www.geogebra.org/web/$TARGET/$APPNAME.crx"
rsync -avPO --rsh=ssh $APPNAME $WWW_SERVER_LOGIN:$GGBWEBDIR/$TARGET 2>&1 | grep -v failed | grep -v "were not transferred"

# 3. Finished
echo "Now you might want to check this deployment by pointing your Chrome browser to
* http://www.geogebra.org/web/$TARGET/$APPNAME.crx"
