#!/bin/sh
# Deploys the Chrome Application to www.geogebra.org/web/...
# By default, it puts to www.geogebra.org/web/geogebra.crx,
# fine tuning is possible via an extra parameter on command line.

# 1. Setting up environment variables
# Override them if needed by using autobuild.conf
WWW_SERVER_LOGIN=www-refresh@www.geogebra.org
GGBWEBDIR=/home/GeoGebra/web
APPNAME=geogebra_chromeapp

AUTOBUILDCONF=../../desktop/scripts/autobuild/autobuild.conf

test -r $AUTOBUILDCONF && . $AUTOBUILDCONF && echo "* Using autobuild.conf for overriding defaults"

TARGET=$1

# 2. Copying
for i in crx zip; do
 echo "Copying $APPNAME.$i to $WWW_SERVER_LOGIN:$GGBWEBDIR/$TARGET/$APPNAME.$i"
 rsync -avPO --rsh="ssh -p $WWW_SERVER_PORT -i $WWW_SERVER_KEY" $APPNAME.$i $WWW_SERVER_LOGIN:$GGBWEBDIR/$TARGET
 done

# 3. Finished
echo "Now you might want to check this deployment by pointing your Chrome browser to
* http://www.geogebra.org/web/$TARGET/$APPNAME.crx

Or just download
http://www.geogebra.org/web/$TARGET/$APPNAME.zip
for uploading it to https://chrome.google.com/webstore/developer/dashboard."
