#!/bin/sh
# Creates the geogebra.crx file and also geogebra.zip for uploading to Chrome Web Store.
# We don't use the CRX file, however, since we do not host GeoGebraWeb on our own,
# but use the official Chrome Web Store instead.
# @author Gabor Ancsin <gabor@geogebra.org>
# @author Zoltan Kovacs <zoltan@geogebra.org>

# 1. Settings
APPNAME=geogebra
KEYFILE=igi-keystore-CL.key.pem
AUTOBUILDCONF=../../desktop/scripts/autobuild/autobuild.conf
VERSIONFILE=../../desktop/build/unpacked/version.txt

test -r $AUTOBUILDCONF || {
 echo "No autobuild.conf exists in $AUTOBUILDCONF"
 exit 11
 }

# FIXME, this is unelegant and slow
test -r $VERSIONFILE || {
 echo "$VERSIONFILE is missing - do a desktop build first"
 exit 12
 }

. ../../desktop/scripts/autobuild/autobuild.conf

test -r $P12DIR/$KEYFILE || {
 echo "No $KEYFILE exists in directory $P12DIR"
 exit 13
 }

# 2. Working directories
MYDIR=`dirname $0`
CHROMEDIR=`cd $MYDIR; pwd`
WEBDIR=`cd $CHROMEDIR/../../web; pwd`
VERSION=`cat $VERSIONFILE`

# 2/1. Compilation and file preparation
cd $WEBDIR
./build -u safari -c -cg
cp -r $WEBDIR/war/web $CHROMEDIR/$APPNAME
cp $WEBDIR/war/app.html $CHROMEDIR/$APPNAME
cd $CHROMEDIR
cat $APPNAME/manifest.json.template | sed s/VERSION/$VERSION/g > \
 $APPNAME/manifest.json

# 3. Packaging
rm -f $APPNAME.zip
./crxmake.sh $APPNAME $P12DIR/$KEYFILE

# 4. Cleanup
rm -rf $APPNAME/web
rm -f $APPNAME/app.html

# 5. Info
echo "Packaging is finished, the result is in $APPNAME.crx and $APPNAME.zip"
