/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.concord.sensor.labprousb;

public class LabProUSB {
  public static short open() {
    return LabProUSBJNI.open();
  }

  public static short close() {
    return LabProUSBJNI.close();
  }

  public static short isOpen() {
    return LabProUSBJNI.isOpen();
  }

  public static int getAvailableBytes() {
    return LabProUSBJNI.getAvailableBytes();
  }

  public static int readBytes(int numBytesRequested, byte[] buffer) {
    return LabProUSBJNI.readBytes(numBytesRequested, buffer);
  }

  public static short writeBytes(short numBytesRequested, byte[] buffer) {
    return LabProUSBJNI.writeBytes(numBytesRequested, buffer);
  }

  public static short clearInputs(short nothing) {
    return LabProUSBJNI.clearInputs(nothing);
  }

  public static short setNumChannelsAndModes(int nNumChannels, short bBinaryMode, short bRealTime) {
    return LabProUSBJNI.setNumChannelsAndModes(nNumChannels, bBinaryMode, bRealTime);
  }

}
