#!/bin/sh

# This script updates MathPiper and MPReduce source code in the GeoGebra
# source tree. We assume that GeoGebra, MathPiper and MPReduce have all
# three been already checked out into ../../../.., period.
#
# If they haven't, cd to that directory and run:
#
# svn checkout http://www.geogebra.org/svn/trunk/geogebra geogebra
# svn checkout https://mathpiper.googlecode.com/svn/trunk/ mathpiper 
# svn checkout https://mathpiper.googlecode.com/svn/trunk/src/library_apps/mpreduce mpreduce-read-only
#
# Otherwise, the script will check out them automatically.
#
# The script is based on Markus' and Thomas' idea, but enhanced to avoid SVN database confusions
# by introducing the svnsync-R script (Zoltan).

MYDIR=`dirname $0`
MYFULLDIR=`cd $MYDIR; pwd`

cd ../../../..
test -d geogebra || svn checkout http://www.geogebra.org/svn/trunk/geogebra geogebra
test -d mathpiper || https://mathpiper.googlecode.com/svn/trunk/ mathpiper 
test -d mpreduce-read-only || svn checkout https://mathpiper.googlecode.com/svn/trunk/src/library_apps/mpreduce mpreduce-read-only

#echo "Update MathPiper from SVN ..."
svn update mathpiper
cd mathpiper
ant *all
ant -Dtarget=geogebra_dist mathpiper_library
cd ..

#echo "Update MPReduce from SVN ..."
cd mpreduce-read-only
svn update
ant clean
ant compile
ant minireduce.img
cd ..

# merge MathPiper and MPReduce sources in one directory
mkdir -p tmp_mp
cp -r mathpiper/build/library_apps/mathpiper/geogebra_dist/src/* tmp_mp
cp -r mpreduce-read-only/src/java/* tmp_mp

# delete leftover .svn or classfiles
find tmp_mp -name ".svn" | xargs rm -r
find tmp_mp -name "*.class" -delete

# copy new MathPiper source files to geogebra project directory
cp -r tmp_mp/* geogebra/desktop/

# copying Reduce function image to geogebra
cp mpreduce-read-only/build/images/minireduce.img geogebra/desktop/default.img

# svn add/delete/modify
cd geogebra/desktop/org/mathpiper
$MYFULLDIR/svnsync-R

echo "Refresh and compile geogebra. Then commit changes to SVN."
