//Generated by CharTableConverter
//!!DO NOT EDIT
package org.freehep.graphics2d.font;

import java.util.HashMap;

/**
 * Generated Expert Encoding Table.
 *
 * @author org.freehep.graphics2d.font.CharTableConverter
 * @version $Id: Expert.java,v 1.4 2009-06-22 02:18:16 hohenwarter Exp $
 */
public class Expert extends AbstractCharTable {
	private final HashMap<Character, String> unicodeToName = new HashMap<>();
	private final HashMap<String, Character> nameToUnicode = new HashMap<>();
	private final HashMap<String, Integer> nameToEnc = new HashMap<>();
	private final String[] encToName = new String[256];

	public Expert() {

		unicodeToName.put((char) 0xF7E6, "AEsmall");
		nameToUnicode.put("AEsmall", (char) 0xF7E6);
		nameToEnc.put("AEsmall", 190);
		encToName[190] = "AEsmall";

		unicodeToName.put((char) 0xF7E1, "Aacutesmall");
		nameToUnicode.put("Aacutesmall", (char) 0xF7E1);
		nameToEnc.put("Aacutesmall", 135);
		encToName[135] = "Aacutesmall";

		unicodeToName.put((char) 0xF7E2, "Acircumflexsmall");
		nameToUnicode.put("Acircumflexsmall", (char) 0xF7E2);
		nameToEnc.put("Acircumflexsmall", 137);
		encToName[137] = "Acircumflexsmall";

		unicodeToName.put((char) 0xF7B4, "Acutesmall");
		nameToUnicode.put("Acutesmall", (char) 0xF7B4);
		nameToEnc.put("Acutesmall", 39);
		encToName[39] = "Acutesmall";

		unicodeToName.put((char) 0xF7E4, "Adieresissmall");
		nameToUnicode.put("Adieresissmall", (char) 0xF7E4);
		nameToEnc.put("Adieresissmall", 138);
		encToName[138] = "Adieresissmall";

		unicodeToName.put((char) 0xF7E0, "Agravesmall");
		nameToUnicode.put("Agravesmall", (char) 0xF7E0);
		nameToEnc.put("Agravesmall", 136);
		encToName[136] = "Agravesmall";

		unicodeToName.put((char) 0xF7E5, "Aringsmall");
		nameToUnicode.put("Aringsmall", (char) 0xF7E5);
		nameToEnc.put("Aringsmall", 140);
		encToName[140] = "Aringsmall";

		unicodeToName.put((char) 0xF761, "Asmall");
		nameToUnicode.put("Asmall", (char) 0xF761);
		nameToEnc.put("Asmall", 97);
		encToName[97] = "Asmall";

		unicodeToName.put((char) 0xF7E3, "Atildesmall");
		nameToUnicode.put("Atildesmall", (char) 0xF7E3);
		nameToEnc.put("Atildesmall", 139);
		encToName[139] = "Atildesmall";

		unicodeToName.put((char) 0xF6F4, "Brevesmall");
		nameToUnicode.put("Brevesmall", (char) 0xF6F4);
		nameToEnc.put("Brevesmall", 243);
		encToName[243] = "Brevesmall";

		unicodeToName.put((char) 0xF762, "Bsmall");
		nameToUnicode.put("Bsmall", (char) 0xF762);
		nameToEnc.put("Bsmall", 98);
		encToName[98] = "Bsmall";

		unicodeToName.put((char) 0xF6F5, "Caronsmall");
		nameToUnicode.put("Caronsmall", (char) 0xF6F5);
		nameToEnc.put("Caronsmall", 174);
		encToName[174] = "Caronsmall";

		unicodeToName.put((char) 0xF7E7, "Ccedillasmall");
		nameToUnicode.put("Ccedillasmall", (char) 0xF7E7);
		nameToEnc.put("Ccedillasmall", 141);
		encToName[141] = "Ccedillasmall";

		unicodeToName.put((char) 0xF7B8, "Cedillasmall");
		nameToUnicode.put("Cedillasmall", (char) 0xF7B8);
		nameToEnc.put("Cedillasmall", 201);
		encToName[201] = "Cedillasmall";

		unicodeToName.put((char) 0xF6F6, "Circumflexsmall");
		nameToUnicode.put("Circumflexsmall", (char) 0xF6F6);
		nameToEnc.put("Circumflexsmall", 94);
		encToName[94] = "Circumflexsmall";

		unicodeToName.put((char) 0xF763, "Csmall");
		nameToUnicode.put("Csmall", (char) 0xF763);
		nameToEnc.put("Csmall", 99);
		encToName[99] = "Csmall";

		unicodeToName.put((char) 0xF7A8, "Dieresissmall");
		nameToUnicode.put("Dieresissmall", (char) 0xF7A8);
		nameToEnc.put("Dieresissmall", 172);
		encToName[172] = "Dieresissmall";

		unicodeToName.put((char) 0xF6F7, "Dotaccentsmall");
		nameToUnicode.put("Dotaccentsmall", (char) 0xF6F7);
		nameToEnc.put("Dotaccentsmall", 250);
		encToName[250] = "Dotaccentsmall";

		unicodeToName.put((char) 0xF764, "Dsmall");
		nameToUnicode.put("Dsmall", (char) 0xF764);
		nameToEnc.put("Dsmall", 100);
		encToName[100] = "Dsmall";

		unicodeToName.put((char) 0xF7E9, "Eacutesmall");
		nameToUnicode.put("Eacutesmall", (char) 0xF7E9);
		nameToEnc.put("Eacutesmall", 142);
		encToName[142] = "Eacutesmall";

		unicodeToName.put((char) 0xF7EA, "Ecircumflexsmall");
		nameToUnicode.put("Ecircumflexsmall", (char) 0xF7EA);
		nameToEnc.put("Ecircumflexsmall", 144);
		encToName[144] = "Ecircumflexsmall";

		unicodeToName.put((char) 0xF7EB, "Edieresissmall");
		nameToUnicode.put("Edieresissmall", (char) 0xF7EB);
		nameToEnc.put("Edieresissmall", 145);
		encToName[145] = "Edieresissmall";

		unicodeToName.put((char) 0xF7E8, "Egravesmall");
		nameToUnicode.put("Egravesmall", (char) 0xF7E8);
		nameToEnc.put("Egravesmall", 143);
		encToName[143] = "Egravesmall";

		unicodeToName.put((char) 0xF765, "Esmall");
		nameToUnicode.put("Esmall", (char) 0xF765);
		nameToEnc.put("Esmall", 101);
		encToName[101] = "Esmall";

		unicodeToName.put((char) 0xF7F0, "Ethsmall");
		nameToUnicode.put("Ethsmall", (char) 0xF7F0);
		nameToEnc.put("Ethsmall", 68);
		encToName[68] = "Ethsmall";

		unicodeToName.put((char) 0xF766, "Fsmall");
		nameToUnicode.put("Fsmall", (char) 0xF766);
		nameToEnc.put("Fsmall", 102);
		encToName[102] = "Fsmall";

		unicodeToName.put((char) 0xF760, "Gravesmall");
		nameToUnicode.put("Gravesmall", (char) 0xF760);
		nameToEnc.put("Gravesmall", 96);
		encToName[96] = "Gravesmall";

		unicodeToName.put((char) 0xF767, "Gsmall");
		nameToUnicode.put("Gsmall", (char) 0xF767);
		nameToEnc.put("Gsmall", 103);
		encToName[103] = "Gsmall";

		unicodeToName.put((char) 0xF768, "Hsmall");
		nameToUnicode.put("Hsmall", (char) 0xF768);
		nameToEnc.put("Hsmall", 104);
		encToName[104] = "Hsmall";

		unicodeToName.put((char) 0xF6F8, "Hungarumlautsmall");
		nameToUnicode.put("Hungarumlautsmall", (char) 0xF6F8);
		nameToEnc.put("Hungarumlautsmall", 34);
		encToName[34] = "Hungarumlautsmall";

		unicodeToName.put((char) 0xF7ED, "Iacutesmall");
		nameToUnicode.put("Iacutesmall", (char) 0xF7ED);
		nameToEnc.put("Iacutesmall", 146);
		encToName[146] = "Iacutesmall";

		unicodeToName.put((char) 0xF7EE, "Icircumflexsmall");
		nameToUnicode.put("Icircumflexsmall", (char) 0xF7EE);
		nameToEnc.put("Icircumflexsmall", 148);
		encToName[148] = "Icircumflexsmall";

		unicodeToName.put((char) 0xF7EF, "Idieresissmall");
		nameToUnicode.put("Idieresissmall", (char) 0xF7EF);
		nameToEnc.put("Idieresissmall", 149);
		encToName[149] = "Idieresissmall";

		unicodeToName.put((char) 0xF7EC, "Igravesmall");
		nameToUnicode.put("Igravesmall", (char) 0xF7EC);
		nameToEnc.put("Igravesmall", 147);
		encToName[147] = "Igravesmall";

		unicodeToName.put((char) 0xF769, "Ismall");
		nameToUnicode.put("Ismall", (char) 0xF769);
		nameToEnc.put("Ismall", 105);
		encToName[105] = "Ismall";

		unicodeToName.put((char) 0xF76A, "Jsmall");
		nameToUnicode.put("Jsmall", (char) 0xF76A);
		nameToEnc.put("Jsmall", 106);
		encToName[106] = "Jsmall";

		unicodeToName.put((char) 0xF76B, "Ksmall");
		nameToUnicode.put("Ksmall", (char) 0xF76B);
		nameToEnc.put("Ksmall", 107);
		encToName[107] = "Ksmall";

		unicodeToName.put((char) 0xF6F9, "Lslashsmall");
		nameToUnicode.put("Lslashsmall", (char) 0xF6F9);
		nameToEnc.put("Lslashsmall", 194);
		encToName[194] = "Lslashsmall";

		unicodeToName.put((char) 0xF76C, "Lsmall");
		nameToUnicode.put("Lsmall", (char) 0xF76C);
		nameToEnc.put("Lsmall", 108);
		encToName[108] = "Lsmall";

		unicodeToName.put((char) 0xF7AF, "Macronsmall");
		nameToUnicode.put("Macronsmall", (char) 0xF7AF);
		nameToEnc.put("Macronsmall", 244);
		encToName[244] = "Macronsmall";

		unicodeToName.put((char) 0xF76D, "Msmall");
		nameToUnicode.put("Msmall", (char) 0xF76D);
		nameToEnc.put("Msmall", 109);
		encToName[109] = "Msmall";

		unicodeToName.put((char) 0xF76E, "Nsmall");
		nameToUnicode.put("Nsmall", (char) 0xF76E);
		nameToEnc.put("Nsmall", 110);
		encToName[110] = "Nsmall";

		unicodeToName.put((char) 0xF7F1, "Ntildesmall");
		nameToUnicode.put("Ntildesmall", (char) 0xF7F1);
		nameToEnc.put("Ntildesmall", 150);
		encToName[150] = "Ntildesmall";

		unicodeToName.put((char) 0xF6FA, "OEsmall");
		nameToUnicode.put("OEsmall", (char) 0xF6FA);
		nameToEnc.put("OEsmall", 207);
		encToName[207] = "OEsmall";

		unicodeToName.put((char) 0xF7F3, "Oacutesmall");
		nameToUnicode.put("Oacutesmall", (char) 0xF7F3);
		nameToEnc.put("Oacutesmall", 151);
		encToName[151] = "Oacutesmall";

		unicodeToName.put((char) 0xF7F4, "Ocircumflexsmall");
		nameToUnicode.put("Ocircumflexsmall", (char) 0xF7F4);
		nameToEnc.put("Ocircumflexsmall", 153);
		encToName[153] = "Ocircumflexsmall";

		unicodeToName.put((char) 0xF7F6, "Odieresissmall");
		nameToUnicode.put("Odieresissmall", (char) 0xF7F6);
		nameToEnc.put("Odieresissmall", 154);
		encToName[154] = "Odieresissmall";

		unicodeToName.put((char) 0xF6FB, "Ogoneksmall");
		nameToUnicode.put("Ogoneksmall", (char) 0xF6FB);
		nameToEnc.put("Ogoneksmall", 242);
		encToName[242] = "Ogoneksmall";

		unicodeToName.put((char) 0xF7F2, "Ogravesmall");
		nameToUnicode.put("Ogravesmall", (char) 0xF7F2);
		nameToEnc.put("Ogravesmall", 152);
		encToName[152] = "Ogravesmall";

		unicodeToName.put((char) 0xF7F8, "Oslashsmall");
		nameToUnicode.put("Oslashsmall", (char) 0xF7F8);
		nameToEnc.put("Oslashsmall", 191);
		encToName[191] = "Oslashsmall";

		unicodeToName.put((char) 0xF76F, "Osmall");
		nameToUnicode.put("Osmall", (char) 0xF76F);
		nameToEnc.put("Osmall", 111);
		encToName[111] = "Osmall";

		unicodeToName.put((char) 0xF7F5, "Otildesmall");
		nameToUnicode.put("Otildesmall", (char) 0xF7F5);
		nameToEnc.put("Otildesmall", 155);
		encToName[155] = "Otildesmall";

		unicodeToName.put((char) 0xF770, "Psmall");
		nameToUnicode.put("Psmall", (char) 0xF770);
		nameToEnc.put("Psmall", 112);
		encToName[112] = "Psmall";

		unicodeToName.put((char) 0xF771, "Qsmall");
		nameToUnicode.put("Qsmall", (char) 0xF771);
		nameToEnc.put("Qsmall", 113);
		encToName[113] = "Qsmall";

		unicodeToName.put((char) 0xF6FC, "Ringsmall");
		nameToUnicode.put("Ringsmall", (char) 0xF6FC);
		nameToEnc.put("Ringsmall", 251);
		encToName[251] = "Ringsmall";

		unicodeToName.put((char) 0xF772, "Rsmall");
		nameToUnicode.put("Rsmall", (char) 0xF772);
		nameToEnc.put("Rsmall", 114);
		encToName[114] = "Rsmall";

		unicodeToName.put((char) 0xF6FD, "Scaronsmall");
		nameToUnicode.put("Scaronsmall", (char) 0xF6FD);
		nameToEnc.put("Scaronsmall", 167);
		encToName[167] = "Scaronsmall";

		unicodeToName.put((char) 0xF773, "Ssmall");
		nameToUnicode.put("Ssmall", (char) 0xF773);
		nameToEnc.put("Ssmall", 115);
		encToName[115] = "Ssmall";

		unicodeToName.put((char) 0xF7FE, "Thornsmall");
		nameToUnicode.put("Thornsmall", (char) 0xF7FE);
		nameToEnc.put("Thornsmall", 185);
		encToName[185] = "Thornsmall";

		unicodeToName.put((char) 0xF6FE, "Tildesmall");
		nameToUnicode.put("Tildesmall", (char) 0xF6FE);
		nameToEnc.put("Tildesmall", 126);
		encToName[126] = "Tildesmall";

		unicodeToName.put((char) 0xF774, "Tsmall");
		nameToUnicode.put("Tsmall", (char) 0xF774);
		nameToEnc.put("Tsmall", 116);
		encToName[116] = "Tsmall";

		unicodeToName.put((char) 0xF7FA, "Uacutesmall");
		nameToUnicode.put("Uacutesmall", (char) 0xF7FA);
		nameToEnc.put("Uacutesmall", 156);
		encToName[156] = "Uacutesmall";

		unicodeToName.put((char) 0xF7FB, "Ucircumflexsmall");
		nameToUnicode.put("Ucircumflexsmall", (char) 0xF7FB);
		nameToEnc.put("Ucircumflexsmall", 158);
		encToName[158] = "Ucircumflexsmall";

		unicodeToName.put((char) 0xF7FC, "Udieresissmall");
		nameToUnicode.put("Udieresissmall", (char) 0xF7FC);
		nameToEnc.put("Udieresissmall", 159);
		encToName[159] = "Udieresissmall";

		unicodeToName.put((char) 0xF7F9, "Ugravesmall");
		nameToUnicode.put("Ugravesmall", (char) 0xF7F9);
		nameToEnc.put("Ugravesmall", 157);
		encToName[157] = "Ugravesmall";

		unicodeToName.put((char) 0xF775, "Usmall");
		nameToUnicode.put("Usmall", (char) 0xF775);
		nameToEnc.put("Usmall", 117);
		encToName[117] = "Usmall";

		unicodeToName.put((char) 0xF776, "Vsmall");
		nameToUnicode.put("Vsmall", (char) 0xF776);
		nameToEnc.put("Vsmall", 118);
		encToName[118] = "Vsmall";

		unicodeToName.put((char) 0xF777, "Wsmall");
		nameToUnicode.put("Wsmall", (char) 0xF777);
		nameToEnc.put("Wsmall", 119);
		encToName[119] = "Wsmall";

		unicodeToName.put((char) 0xF778, "Xsmall");
		nameToUnicode.put("Xsmall", (char) 0xF778);
		nameToEnc.put("Xsmall", 120);
		encToName[120] = "Xsmall";

		unicodeToName.put((char) 0xF7FD, "Yacutesmall");
		nameToUnicode.put("Yacutesmall", (char) 0xF7FD);
		nameToEnc.put("Yacutesmall", 180);
		encToName[180] = "Yacutesmall";

		unicodeToName.put((char) 0xF7FF, "Ydieresissmall");
		nameToUnicode.put("Ydieresissmall", (char) 0xF7FF);
		nameToEnc.put("Ydieresissmall", 216);
		encToName[216] = "Ydieresissmall";

		unicodeToName.put((char) 0xF779, "Ysmall");
		nameToUnicode.put("Ysmall", (char) 0xF779);
		nameToEnc.put("Ysmall", 121);
		encToName[121] = "Ysmall";

		unicodeToName.put((char) 0xF6FF, "Zcaronsmall");
		nameToUnicode.put("Zcaronsmall", (char) 0xF6FF);
		nameToEnc.put("Zcaronsmall", 189);
		encToName[189] = "Zcaronsmall";

		unicodeToName.put((char) 0xF77A, "Zsmall");
		nameToUnicode.put("Zsmall", (char) 0xF77A);
		nameToEnc.put("Zsmall", 122);
		encToName[122] = "Zsmall";

		unicodeToName.put((char) 0xfe60, "ampersandsmall");
		nameToUnicode.put("ampersandsmall", (char) 0xfe60);
		nameToEnc.put("ampersandsmall", 38);
		encToName[38] = "ampersandsmall";

		unicodeToName.put((char) 0xF6E9, "asuperior");
		nameToUnicode.put("asuperior", (char) 0xF6E9);
		nameToEnc.put("asuperior", 129);
		encToName[129] = "asuperior";

		unicodeToName.put((char) 0xF6EA, "bsuperior");
		nameToUnicode.put("bsuperior", (char) 0xF6EA);
		nameToEnc.put("bsuperior", 245);
		encToName[245] = "bsuperior";

		unicodeToName.put((char) 0xF6DF, "centinferior");
		nameToUnicode.put("centinferior", (char) 0xF6DF);
		nameToEnc.put("centinferior", 169);
		encToName[169] = "centinferior";

		unicodeToName.put((char) 0xF7A2, "centoldstyle");
		nameToUnicode.put("centoldstyle", (char) 0xF7A2);
		nameToEnc.put("centoldstyle", 35);
		encToName[35] = "centoldstyle";

		unicodeToName.put((char) 0xF6E0, "centsuperior");
		nameToUnicode.put("centsuperior", (char) 0xF6E0);
		nameToEnc.put("centsuperior", 130);
		encToName[130] = "centsuperior";

		unicodeToName.put((char) 0x003a, "colon");
		nameToUnicode.put("colon", (char) 0x003a);
		nameToEnc.put("colon", 58);
		encToName[58] = "colon";

		unicodeToName.put((char) 0x20a1, "colonmonetary");
		nameToUnicode.put("colonmonetary", (char) 0x20a1);
		nameToEnc.put("colonmonetary", 123);
		encToName[123] = "colonmonetary";

		unicodeToName.put((char) 0x002c, "comma");
		nameToUnicode.put("comma", (char) 0x002c);
		nameToEnc.put("comma", 44);
		encToName[44] = "comma";

		unicodeToName.put((char) 0xF6E1, "commainferior");
		nameToUnicode.put("commainferior", (char) 0xF6E1);
		nameToEnc.put("commainferior", 178);
		encToName[178] = "commainferior";

		unicodeToName.put((char) 0xF6E2, "commasuperior");
		nameToUnicode.put("commasuperior", (char) 0xF6E2);
		nameToEnc.put("commasuperior", 248);
		encToName[248] = "commasuperior";

		unicodeToName.put((char) 0xF6E3, "dollarinferior");
		nameToUnicode.put("dollarinferior", (char) 0xF6E3);
		nameToEnc.put("dollarinferior", 182);
		encToName[182] = "dollarinferior";

		unicodeToName.put((char) 0xF724, "dollaroldstyle");
		nameToUnicode.put("dollaroldstyle", (char) 0xF724);
		nameToEnc.put("dollaroldstyle", 36);
		encToName[36] = "dollaroldstyle";

		unicodeToName.put((char) 0xF6E4, "dollarsuperior");
		nameToUnicode.put("dollarsuperior", (char) 0xF6E4);
		nameToEnc.put("dollarsuperior", 37);
		encToName[37] = "dollarsuperior";

		unicodeToName.put((char) 0xF6EB, "dsuperior");
		nameToUnicode.put("dsuperior", (char) 0xF6EB);
		nameToEnc.put("dsuperior", 235);
		encToName[235] = "dsuperior";

		unicodeToName.put((char) 0x2088, "eightinferior");
		nameToUnicode.put("eightinferior", (char) 0x2088);
		nameToEnc.put("eightinferior", 165);
		encToName[165] = "eightinferior";

		unicodeToName.put((char) 0xF738, "eightoldstyle");
		nameToUnicode.put("eightoldstyle", (char) 0xF738);
		nameToEnc.put("eightoldstyle", 56);
		encToName[56] = "eightoldstyle";

		unicodeToName.put((char) 0x2078, "eightsuperior");
		nameToUnicode.put("eightsuperior", (char) 0x2078);
		nameToEnc.put("eightsuperior", 161);
		encToName[161] = "eightsuperior";

		unicodeToName.put((char) 0xF6EC, "esuperior");
		nameToUnicode.put("esuperior", (char) 0xF6EC);
		nameToEnc.put("esuperior", 228);
		encToName[228] = "esuperior";

		unicodeToName.put((char) 0xF7A1, "exclamdownsmall");
		nameToUnicode.put("exclamdownsmall", (char) 0xF7A1);
		nameToEnc.put("exclamdownsmall", 214);
		encToName[214] = "exclamdownsmall";

		unicodeToName.put((char) 0xfe57, "exclamsmall");
		nameToUnicode.put("exclamsmall", (char) 0xfe57);
		nameToEnc.put("exclamsmall", 33);
		encToName[33] = "exclamsmall";

		unicodeToName.put((char) 0xfb00, "ff");
		nameToUnicode.put("ff", (char) 0xfb00);
		nameToEnc.put("ff", 86);
		encToName[86] = "ff";

		unicodeToName.put((char) 0xfb03, "ffi");
		nameToUnicode.put("ffi", (char) 0xfb03);
		nameToEnc.put("ffi", 89);
		encToName[89] = "ffi";

		unicodeToName.put((char) 0xfb04, "ffl");
		nameToUnicode.put("ffl", (char) 0xfb04);
		nameToEnc.put("ffl", 90);
		encToName[90] = "ffl";

		unicodeToName.put((char) 0xfb01, "fi");
		nameToUnicode.put("fi", (char) 0xfb01);
		nameToEnc.put("fi", 87);
		encToName[87] = "fi";

		unicodeToName.put((char) 0x2012, "figuredash");
		nameToUnicode.put("figuredash", (char) 0x2012);
		nameToEnc.put("figuredash", 208);
		encToName[208] = "figuredash";

		unicodeToName.put((char) 0x215d, "fiveeighths");
		nameToUnicode.put("fiveeighths", (char) 0x215d);
		nameToEnc.put("fiveeighths", 76);
		encToName[76] = "fiveeighths";

		unicodeToName.put((char) 0x2085, "fiveinferior");
		nameToUnicode.put("fiveinferior", (char) 0x2085);
		nameToEnc.put("fiveinferior", 176);
		encToName[176] = "fiveinferior";

		unicodeToName.put((char) 0xF735, "fiveoldstyle");
		nameToUnicode.put("fiveoldstyle", (char) 0xF735);
		nameToEnc.put("fiveoldstyle", 53);
		encToName[53] = "fiveoldstyle";

		unicodeToName.put((char) 0x2075, "fivesuperior");
		nameToUnicode.put("fivesuperior", (char) 0x2075);
		nameToEnc.put("fivesuperior", 222);
		encToName[222] = "fivesuperior";

		unicodeToName.put((char) 0xfb02, "fl");
		nameToUnicode.put("fl", (char) 0xfb02);
		nameToEnc.put("fl", 88);
		encToName[88] = "fl";

		unicodeToName.put((char) 0x2084, "fourinferior");
		nameToUnicode.put("fourinferior", (char) 0x2084);
		nameToEnc.put("fourinferior", 162);
		encToName[162] = "fourinferior";

		unicodeToName.put((char) 0xF734, "fouroldstyle");
		nameToUnicode.put("fouroldstyle", (char) 0xF734);
		nameToEnc.put("fouroldstyle", 52);
		encToName[52] = "fouroldstyle";

		unicodeToName.put((char) 0x2074, "foursuperior");
		nameToUnicode.put("foursuperior", (char) 0x2074);
		nameToEnc.put("foursuperior", 221);
		encToName[221] = "foursuperior";

		unicodeToName.put((char) 0x2044, "fraction");
		nameToUnicode.put("fraction", (char) 0x2044);
		nameToEnc.put("fraction", 47);
		encToName[47] = "fraction";

		unicodeToName.put((char) 0x002d, "hyphen");
		nameToUnicode.put("hyphen", (char) 0x002d);
		nameToEnc.put("hyphen", 45);
		encToName[45] = "hyphen";

		unicodeToName.put((char) 0x208b, "hypheninferior");
		nameToUnicode.put("hypheninferior", (char) 0x208b);
		nameToEnc.put("hypheninferior", 95);
		encToName[95] = "hypheninferior";

		unicodeToName.put((char) 0x207b, "hyphensuperior");
		nameToUnicode.put("hyphensuperior", (char) 0x207b);
		nameToEnc.put("hyphensuperior", 209);
		encToName[209] = "hyphensuperior";

		unicodeToName.put((char) 0xF6ED, "isuperior");
		nameToUnicode.put("isuperior", (char) 0xF6ED);
		nameToEnc.put("isuperior", 233);
		encToName[233] = "isuperior";

		unicodeToName.put((char) 0xF6EE, "lsuperior");
		nameToUnicode.put("lsuperior", (char) 0xF6EE);
		nameToEnc.put("lsuperior", 241);
		encToName[241] = "lsuperior";

		unicodeToName.put((char) 0xF6EF, "msuperior");
		nameToUnicode.put("msuperior", (char) 0xF6EF);
		nameToEnc.put("msuperior", 247);
		encToName[247] = "msuperior";

		unicodeToName.put((char) 0x2089, "nineinferior");
		nameToUnicode.put("nineinferior", (char) 0x2089);
		nameToEnc.put("nineinferior", 187);
		encToName[187] = "nineinferior";

		unicodeToName.put((char) 0xF739, "nineoldstyle");
		nameToUnicode.put("nineoldstyle", (char) 0xF739);
		nameToEnc.put("nineoldstyle", 57);
		encToName[57] = "nineoldstyle";

		unicodeToName.put((char) 0x2079, "ninesuperior");
		nameToUnicode.put("ninesuperior", (char) 0x2079);
		nameToEnc.put("ninesuperior", 225);
		encToName[225] = "ninesuperior";

		unicodeToName.put((char) 0x207f, "nsuperior");
		nameToUnicode.put("nsuperior", (char) 0x207f);
		nameToEnc.put("nsuperior", 246);
		encToName[246] = "nsuperior";

		unicodeToName.put((char) 0x2024, "onedotenleader");
		nameToUnicode.put("onedotenleader", (char) 0x2024);
		nameToEnc.put("onedotenleader", 43);
		encToName[43] = "onedotenleader";

		unicodeToName.put((char) 0x215b, "oneeight");
		nameToUnicode.put("oneeight", (char) 0x215b);
		nameToEnc.put("oneeight", 74);
		encToName[74] = "oneeight";

		unicodeToName.put((char) 0xF6DC, "onefitted");
		nameToUnicode.put("onefitted", (char) 0xF6DC);
		nameToEnc.put("onefitted", 124);
		encToName[124] = "onefitted";

		unicodeToName.put((char) 0x00bd, "onehalf");
		nameToUnicode.put("onehalf", (char) 0x00bd);
		nameToEnc.put("onehalf", 72);
		encToName[72] = "onehalf";

		unicodeToName.put((char) 0x2081, "oneinferior");
		nameToUnicode.put("oneinferior", (char) 0x2081);
		nameToEnc.put("oneinferior", 193);
		encToName[193] = "oneinferior";

		unicodeToName.put((char) 0xF731, "oneoldstyle");
		nameToUnicode.put("oneoldstyle", (char) 0xF731);
		nameToEnc.put("oneoldstyle", 49);
		encToName[49] = "oneoldstyle";

		unicodeToName.put((char) 0x00bc, "onequarter");
		nameToUnicode.put("onequarter", (char) 0x00bc);
		nameToEnc.put("onequarter", 71);
		encToName[71] = "onequarter";

		unicodeToName.put((char) 0x00b9, "onesuperior");
		nameToUnicode.put("onesuperior", (char) 0x00b9);
		nameToEnc.put("onesuperior", 218);
		encToName[218] = "onesuperior";

		unicodeToName.put((char) 0x2153, "onethird");
		nameToUnicode.put("onethird", (char) 0x2153);
		nameToEnc.put("onethird", 78);
		encToName[78] = "onethird";

		unicodeToName.put((char) 0xF6F0, "osuperior");
		nameToUnicode.put("osuperior", (char) 0xF6F0);
		nameToEnc.put("osuperior", 175);
		encToName[175] = "osuperior";

		unicodeToName.put((char) 0x208d, "parenleftinferior");
		nameToUnicode.put("parenleftinferior", (char) 0x208d);
		nameToEnc.put("parenleftinferior", 91);
		encToName[91] = "parenleftinferior";

		unicodeToName.put((char) 0x207d, "parenleftsuperior");
		nameToUnicode.put("parenleftsuperior", (char) 0x207d);
		nameToEnc.put("parenleftsuperior", 40);
		encToName[40] = "parenleftsuperior";

		unicodeToName.put((char) 0x208e, "parenrightinferior");
		nameToUnicode.put("parenrightinferior", (char) 0x208e);
		nameToEnc.put("parenrightinferior", 93);
		encToName[93] = "parenrightinferior";

		unicodeToName.put((char) 0x207e, "parenrightsuperior");
		nameToUnicode.put("parenrightsuperior", (char) 0x207e);
		nameToEnc.put("parenrightsuperior", 41);
		encToName[41] = "parenrightsuperior";

		unicodeToName.put((char) 0x002e, "period");
		nameToUnicode.put("period", (char) 0x002e);
		nameToEnc.put("period", 46);
		encToName[46] = "period";

		unicodeToName.put((char) 0xF6E7, "periodinferior");
		nameToUnicode.put("periodinferior", (char) 0xF6E7);
		nameToEnc.put("periodinferior", 179);
		encToName[179] = "periodinferior";

		unicodeToName.put((char) 0xF6E8, "periodsuperior");
		nameToUnicode.put("periodsuperior", (char) 0xF6E8);
		nameToEnc.put("periodsuperior", 249);
		encToName[249] = "periodsuperior";

		unicodeToName.put((char) 0xF7BF, "questiondownsmall");
		nameToUnicode.put("questiondownsmall", (char) 0xF7BF);
		nameToEnc.put("questiondownsmall", 192);
		encToName[192] = "questiondownsmall";

		unicodeToName.put((char) 0xfe56, "questionsmall");
		nameToUnicode.put("questionsmall", (char) 0xfe56);
		nameToEnc.put("questionsmall", 63);
		encToName[63] = "questionsmall";

		unicodeToName.put((char) 0xF6F1, "rsuperior");
		nameToUnicode.put("rsuperior", (char) 0xF6F1);
		nameToEnc.put("rsuperior", 229);
		encToName[229] = "rsuperior";

		unicodeToName.put((char) 0xF6DD, "rupiah");
		nameToUnicode.put("rupiah", (char) 0xF6DD);
		nameToEnc.put("rupiah", 125);
		encToName[125] = "rupiah";

		unicodeToName.put((char) 0x003b, "semicolon");
		nameToUnicode.put("semicolon", (char) 0x003b);
		nameToEnc.put("semicolon", 59);
		encToName[59] = "semicolon";

		unicodeToName.put((char) 0x215e, "seveneighths");
		nameToUnicode.put("seveneighths", (char) 0x215e);
		nameToEnc.put("seveneighths", 77);
		encToName[77] = "seveneighths";

		unicodeToName.put((char) 0x2087, "seveninferior");
		nameToUnicode.put("seveninferior", (char) 0x2087);
		nameToEnc.put("seveninferior", 166);
		encToName[166] = "seveninferior";

		unicodeToName.put((char) 0xF737, "sevenoldstyle");
		nameToUnicode.put("sevenoldstyle", (char) 0xF737);
		nameToEnc.put("sevenoldstyle", 55);
		encToName[55] = "sevenoldstyle";

		unicodeToName.put((char) 0x2077, "sevensuperior");
		nameToUnicode.put("sevensuperior", (char) 0x2077);
		nameToEnc.put("sevensuperior", 224);
		encToName[224] = "sevensuperior";

		unicodeToName.put((char) 0x2086, "sixinferior");
		nameToUnicode.put("sixinferior", (char) 0x2086);
		nameToEnc.put("sixinferior", 164);
		encToName[164] = "sixinferior";

		unicodeToName.put((char) 0xF736, "sixoldstyle");
		nameToUnicode.put("sixoldstyle", (char) 0xF736);
		nameToEnc.put("sixoldstyle", 54);
		encToName[54] = "sixoldstyle";

		unicodeToName.put((char) 0x2076, "sixsuperior");
		nameToUnicode.put("sixsuperior", (char) 0x2076);
		nameToEnc.put("sixsuperior", 223);
		encToName[223] = "sixsuperior";

		unicodeToName.put((char) 0x0020, "space");
		nameToUnicode.put("space", (char) 0x0020);
		nameToEnc.put("space", 32);
		encToName[32] = "space";

		unicodeToName.put((char) 0xF6F2, "ssuperior");
		nameToUnicode.put("ssuperior", (char) 0xF6F2);
		nameToEnc.put("ssuperior", 234);
		encToName[234] = "ssuperior";

		unicodeToName.put((char) 0x215c, "threeeighths");
		nameToUnicode.put("threeeighths", (char) 0x215c);
		nameToEnc.put("threeeighths", 75);
		encToName[75] = "threeeighths";

		unicodeToName.put((char) 0x2083, "threeinferior");
		nameToUnicode.put("threeinferior", (char) 0x2083);
		nameToEnc.put("threeinferior", 163);
		encToName[163] = "threeinferior";

		unicodeToName.put((char) 0xF733, "threeoldstyle");
		nameToUnicode.put("threeoldstyle", (char) 0xF733);
		nameToEnc.put("threeoldstyle", 51);
		encToName[51] = "threeoldstyle";

		unicodeToName.put((char) 0x00be, "threequarters");
		nameToUnicode.put("threequarters", (char) 0x00be);
		nameToEnc.put("threequarters", 73);
		encToName[73] = "threequarters";

		unicodeToName.put((char) 0xfe58, "threequartersemdash");
		nameToUnicode.put("threequartersemdash", (char) 0xfe58);
		nameToEnc.put("threequartersemdash", 61);
		encToName[61] = "threequartersemdash";

		unicodeToName.put((char) 0x00b3, "threesuperior");
		nameToUnicode.put("threesuperior", (char) 0x00b3);
		nameToEnc.put("threesuperior", 220);
		encToName[220] = "threesuperior";

		unicodeToName.put((char) 0xF6F3, "tsuperior");
		nameToUnicode.put("tsuperior", (char) 0xF6F3);
		nameToEnc.put("tsuperior", 230);
		encToName[230] = "tsuperior";

		unicodeToName.put((char) 0x2025, "twodotenleader");
		nameToUnicode.put("twodotenleader", (char) 0x2025);
		nameToEnc.put("twodotenleader", 42);
		encToName[42] = "twodotenleader";

		unicodeToName.put((char) 0x2082, "twoinferior");
		nameToUnicode.put("twoinferior", (char) 0x2082);
		nameToEnc.put("twoinferior", 170);
		encToName[170] = "twoinferior";

		unicodeToName.put((char) 0xF732, "twooldstyle");
		nameToUnicode.put("twooldstyle", (char) 0xF732);
		nameToEnc.put("twooldstyle", 50);
		encToName[50] = "twooldstyle";

		unicodeToName.put((char) 0x00b2, "twosuperior");
		nameToUnicode.put("twosuperior", (char) 0x00b2);
		nameToEnc.put("twosuperior", 219);
		encToName[219] = "twosuperior";

		unicodeToName.put((char) 0x2154, "twothirds");
		nameToUnicode.put("twothirds", (char) 0x2154);
		nameToEnc.put("twothirds", 79);
		encToName[79] = "twothirds";

		unicodeToName.put((char) 0x2080, "zeroinferior");
		nameToUnicode.put("zeroinferior", (char) 0x2080);
		nameToEnc.put("zeroinferior", 188);
		encToName[188] = "zeroinferior";

		unicodeToName.put((char) 0xF730, "zerooldstyle");
		nameToUnicode.put("zerooldstyle", (char) 0xF730);
		nameToEnc.put("zerooldstyle", 48);
		encToName[48] = "zerooldstyle";

		unicodeToName.put((char) 0x2070, "zerosuperior");
		nameToUnicode.put("zerosuperior", (char) 0x2070);
		nameToEnc.put("zerosuperior", 226);
		encToName[226] = "zerosuperior";

	}

	@Override
	public String toName(Character c) {
		return unicodeToName.get(c);
	}

	@Override
	public String toName(int enc) {
		if (enc != 0) {
			return encToName[enc];
		}
		return null;
	}

	@Override
	public int toEncoding(String name) {
		return nameToEnc.get(name);
	}

	@Override
	public char toUnicode(String name) {
		return nameToUnicode.get(name);
	}

	@Override
	public String getName() {
		return "Expert";
	}

	@Override
	public String getEncoding() {
		return "";
	}

}
