#!/bin/sh

WIXDIR=../wix35 # You can override this by using a default value in autobuild.conf

./create-license
./create-wxs

test -r ../../autobuild.conf || {
 echo "Cannot find ../../autobuild.conf (make sure you edit autobuild.conf.dist first)"
 exit 1
 }
. ../../autobuild.conf

test -r $WIXDIR/candle.exe || {
 echo WiX is not installed into $WIXDIR
 exit 1
 }
 
WINEVERSION=`wine --version | sed s/"\."/""/g | sed s/wine\-//`

if [ "$WINEVERSION" -lt "1320" ]; then
 echo Wine is almost surely too old to run this program, get at least 1.3.20
 exit 2
 fi

test -r ../../../../build/installer/windows/geogebra.exe || {
 echo GeoGebra Windows Install does not seem to be built, run../../buildggb40 first
 }

# Copying needed files here:
cp ../../../../build/unpacked/* .
cp ../../../../installer/geogebra.ico .
cp ../../../../build/installer/windows/geogebra.exe .
cp ../../../../installer/cc-by-sa-3.0.txt .
cp ../../../../installer/cc.ico .
cp ../../../../installer/forum.ico .
cp ../../../../installer/wiki.ico .
cp ../../../../installer/gpl-3.0.txt .
mkdir -p unsigned
cp ../../../../build/unsigned/unpacked/* unsigned

GGBVERSION=`cat ../../../../build/unpacked/version.txt`
GGBVERSION_DASHED=`echo $GGBVERSION | tr . -`
MSIFILE=GeoGebra-Windows-Installer-$GGBVERSION_DASHED.msi

wine $WIXDIR/candle.exe GeoGebra.wxs
wine $WIXDIR/light.exe -sval -ext WixUIExtension GeoGebra.wixobj

mv GeoGebra.msi $MSIFILE

echo "Now you can run 'msiexec /i $MSIFILE' to test GeoGebra Windows Installer on Unix"

