#!/bin/sh
# Creates the .wxs file from the .template.

O=GeoGebra.wxs
T=$O.template

SHORTVERSION=4.2

VERSION_STRING=`cat ../../../../build/unpacked/version.txt`
if [ "$VERSION_STRING" = "" ]; then
 echo "Please build GeoGebra first."
 exit 1
 fi

LONGVERSION=$VERSION_STRING
INSTALLERVERSION=`echo $SHORTVERSION | sed s/"\."/""/g`

cat $T |\
 sed s/\$LONGVERSION/$LONGVERSION/g |\
 sed s/\$SHORTVERSION/$SHORTVERSION/g |\
 sed s/\$INSTALLERVERSION/$INSTALLERVERSION/g \
 > $O
