package geogebra.common.plugin;

public enum GeoClass {
	ANGLE, AXIS, BOOLEAN, BUTTON, TEXTFIELD, CONIC, CONICPART, FUNCTION, INTERVAL, FUNCTIONCONDITIONAL, IMAGE, LINE, LIST, LOCUS, NUMERIC, POINT, POLYGON, RAY, SEGMENT, TEXT, VECTOR, CURVE_CARTESIAN, CURVE_POLAR, IMPLICIT_POLY, FUNCTION_NVAR, POLYLINE, LINEAR_INEQUALITY,
	TURTLE,
	CAS_CELL,

	ANGLE3D, POINT3D, VECTOR3D, SEGMENT3D, LINE3D, RAY3D, CONIC3D, AXIS3D, CURVECARTESIAN3D, POLYGON3D, PLANE3D, QUADRIC, QUADRIC_PART, QUADRIC_LIMITED, POLYLINE3D, POLYHEDRON,

	SURFACECARTESIAN3D,
	
	CLIPPINGCUBE3D,
	
	DEFAULT
}
