package org.apache.commons.math.exception.util;

public class LocalizedFormats {

	public static final String TOO_LARGE_CUTOFF_SINGULAR_VALUE = "TOO_LARGE_CUTOFF_SINGULAR_VALUE";
	public static final String ASSYMETRIC_EIGEN_NOT_SUPPORTED = "ASSYMETRIC_EIGEN_NOT_SUPPORTED";
	public static final String VECTOR_LENGTH_MISMATCH = "VECTOR_LENGTH_MISMATCH";
	public static final String DIMENSIONS_MISMATCH_2x2 = "DIMENSIONS_MISMATCH_2x2";
	public static final String ROW_INDEX_OUT_OF_RANGE = "ROW_INDEX_OUT_OF_RANGE";
	public static final String COLUMN_INDEX_OUT_OF_RANGE = "COLUMN_INDEX_OUT_OF_RANGE";
	public static final String INITIAL_ROW_AFTER_FINAL_ROW = "INITIAL_ROW_AFTER_FINAL_ROW";
	public static final String INITIAL_COLUMN_AFTER_FINAL_COLUMN = "INITIAL_COLUMN_AFTER_FINAL_COLUMN";
	public static final String EMPTY_SELECTED_ROW_INDEX_ARRAY = "EMPTY_SELECTED_ROW_INDEX_ARRAY";
	public static final String EMPTY_SELECTED_COLUMN_INDEX_ARRAY = "EMPTY_SELECTED_COLUMN_INDEX_ARRAY";
	public static final String NOT_ADDITION_COMPATIBLE_MATRICES = "NOT_ADDITION_COMPATIBLE_MATRICES";
	public static final String NOT_SUBTRACTION_COMPATIBLE_MATRICES = "NOT_SUBTRACTION_COMPATIBLE_MATRICES";
	public static final String NOT_MULTIPLICATION_COMPATIBLE_MATRICES = "NOT_MULTIPLICATION_COMPATIBLE_MATRICES";
	public static final String INSUFFICIENT_DIMENSION = "INSUFFICIENT_DIMENSION";
	public static final String DIFFERENT_ROWS_LENGTHS = "DIFFERENT_ROWS_LENGTHS";
	public static final String AT_LEAST_ONE_ROW = "AT_LEAST_ONE_ROW";
	public static final String AT_LEAST_ONE_COLUMN = "AT_LEAST_ONE_COLUMN";
	public static final String INDEX_OUT_OF_RANGE = "INDEX_OUT_OF_RANGE";
	public static final String DIMENSIONS_MISMATCH_SIMPLE = "DIMENSIONS_MISMATCH_SIMPLE";

}
