{" polar_complex ",13,22,0,*((unsigned longlong *) at_ polar_complex )},
{"%",13,-124,0,*((unsigned longlong *) at_PERCENT)},
{"%CHANGE",13,-124,0,*((unsigned longlong *) at_PERCENTCHANGE)},
{"%TOTAL",13,-124,0,*((unsigned longlong *) at_PERCENTTOTAL)},
{"ABS",13,-124,0,*((unsigned longlong *) at_ABS)},
{"ACOS",13,-124,0,*((unsigned longlong *) at_ACOS)},
{"ACOSH",13,-124,0,*((unsigned longlong *) at_ACOSH)},
{"ACOT",13,-124,0,*((unsigned longlong *) at_ACOT)},
{"ACSC",13,-124,0,*((unsigned longlong *) at_ACSC)},
{"ADDCOL",13,-124,0,*((unsigned longlong *) at_ADDCOL)| 1},
{"ADDROW",13,-124,0,*((unsigned longlong *) at_ADDROW)| 1},
{"ALOG",13,-124,0,*((unsigned longlong *) at_ALOG)},
{"ARC",13,-124,0,*((unsigned longlong *) at_ARC)},
{"ARG",13,-124,0,*((unsigned longlong *) at_ARG)},
{"ASEC",13,-124,0,*((unsigned longlong *) at_ASEC)},
{"ASIN",13,-124,0,*((unsigned longlong *) at_ASIN)},
{"ASINH",13,-124,0,*((unsigned longlong *) at_ASINH)},
{"ATAN",13,-124,0,*((unsigned longlong *) at_ATAN)},
{"ATANH",13,-124,0,*((unsigned longlong *) at_ATANH)},
{"Airy_Ai",13,9,0,*((unsigned longlong *) at_Airy_Ai)},
{"Airy_Bi",13,9,0,*((unsigned longlong *) at_Airy_Bi)},
{"Ans",13,4,0,*((unsigned longlong *) at_Ans)},
{"Archive",13,77,0,*((unsigned longlong *) at_Archive)| 1},
{"BesselI",13,9,0,*((unsigned longlong *) at_BesselI)},
{"BesselJ",13,9,0,*((unsigned longlong *) at_BesselJ)},
{"BesselK",13,9,0,*((unsigned longlong *) at_BesselK)},
{"BesselY",13,9,0,*((unsigned longlong *) at_BesselY)},
{"Beta",13,9,0,*((unsigned longlong *) at_Beta)},
{"BlockDiagonal",13,9,0,*((unsigned longlong *) at_BlockDiagonal)},
{"CEILING",13,-124,0,*((unsigned longlong *) at_CEILING)},
{"CHOOSE",13,-124,0,*((unsigned longlong *) at_CHOOSE)| 1},
{"COLNORM",13,-124,0,*((unsigned longlong *) at_COLNORM)},
{"COMB",13,-124,0,*((unsigned longlong *) at_COMB)},
{"CONCAT",13,-124,0,*((unsigned longlong *) at_CONCAT)},
{"COND",13,-124,0,*((unsigned longlong *) at_COND)},
{"CONJ",13,-124,0,*((unsigned longlong *) at_CONJ)},
{"COS",13,-124,0,*((unsigned longlong *) at_COS)},
{"COSH",13,-124,0,*((unsigned longlong *) at_COSH)},
{"COT",13,-124,0,*((unsigned longlong *) at_COT)},
{"CROSS",13,-124,0,*((unsigned longlong *) at_CROSS)},
{"CSC",13,-124,0,*((unsigned longlong *) at_CSC)},
{"Celsius2Fahrenheit",13,-124,0,*((unsigned longlong *) at_Celsius2Fahrenheit)},
{"Ci",13,9,0,*((unsigned longlong *) at_Ci)},
{"Ci0",13,9,0,*((unsigned longlong *) at_Ci0)},
{"Circle",13,77,0,*((unsigned longlong *) at_Circle)},
{"ClrDraw",13,8,0,*((unsigned longlong *) at_ClrDraw)},
{"ClrGraph",13,8,0,*((unsigned longlong *) at_ClrGraph)},
{"ClrIO",13,8,0,*((unsigned longlong *) at_ClrIO)},
{"CopyVar",13,77,0,*((unsigned longlong *) at_CopyVar)| 1},
{"CyclePic",13,77,0,*((unsigned longlong *) at_CyclePic)},
{"DEGXRAD",13,-124,0,*((unsigned longlong *) at_DEGXRAD)},
{"DELCOL",13,-124,0,*((unsigned longlong *) at_DELCOL)| 1},
{"DELROW",13,-124,0,*((unsigned longlong *) at_DELROW)| 1},
{"DET",13,-124,0,*((unsigned longlong *) at_DET)},
{"DISP",13,-124,0,*((unsigned longlong *) at_DISP)| 1},
{"DOT",13,-124,0,*((unsigned longlong *) at_DOT)},
{"DROP",13,85,0,*((unsigned longlong *) at_DROP)},
{"DUP",13,85,0,*((unsigned longlong *) at_DUP)},
{"DelFold",13,77,0,*((unsigned longlong *) at_DelFold)| 1},
{"DelVar",13,77,0,*((unsigned longlong *) at_DelVar)| 1},
{"Det",13,9,0,*((unsigned longlong *) at_Det)},
{"Dirac",13,9,0,*((unsigned longlong *) at_Dirac)},
{"DispG",13,8,0,*((unsigned longlong *) at_DispG)},
{"DispHome",13,8,0,*((unsigned longlong *) at_DispHome)},
{"DrawFunc",13,77,0,*((unsigned longlong *) at_DrawFunc)},
{"DrawInv",13,77,0,*((unsigned longlong *) at_DrawInv)},
{"DrawParm",13,77,0,*((unsigned longlong *) at_DrawParm)},
{"DrawPol",13,77,0,*((unsigned longlong *) at_DrawPol)},
{"DrawSlp",13,77,0,*((unsigned longlong *) at_DrawSlp)},
{"DrwCtour",13,77,0,*((unsigned longlong *) at_DrwCtour)},
{"EDITMAT",13,-124,0,*((unsigned longlong *) at_EDITMAT)| 1},
{"EIGENVAL",13,-124,0,*((unsigned longlong *) at_EIGENVAL)},
{"EIGENVV",13,-124,0,*((unsigned longlong *) at_EIGENVV)},
{"EXP",13,-124,0,*((unsigned longlong *) at_EXP)},
{"EXPM1",13,-124,0,*((unsigned longlong *) at_EXPM1)},
{"EXPORT",13,77,0,*((unsigned longlong *) at_EXPORT)| 1},
{"Ei",13,9,0,*((unsigned longlong *) at_Ei)},
{"Ei0",13,9,0,*((unsigned longlong *) at_Ei0)},
{"Ei_f",13,9,0,*((unsigned longlong *) at_Ei_f)},
{"Eta",13,9,0,*((unsigned longlong *) at_Eta)},
{"Exec",13,77,0,*((unsigned longlong *) at_Exec)},
{"FLOOR",13,-124,0,*((unsigned longlong *) at_FLOOR)},
{"FNROOT",13,-124,0,*((unsigned longlong *) at_FNROOT)| 1},
{"FRAC",13,-124,0,*((unsigned longlong *) at_FRAC)},
{"Factor",13,9,0,*((unsigned longlong *) at_Factor)},
{"Fahrenheit2Celsius",13,-124,0,*((unsigned longlong *) at_Fahrenheit2Celsius)},
{"Fill",13,77,0,*((unsigned longlong *) at_Fill)| 1},
{"GETKEY",13,-124,0,*((unsigned longlong *) at_GETKEY)},
{"GF",13,9,0,*((unsigned longlong *) at_GF)},
{"Gamma",13,9,0,*((unsigned longlong *) at_Gamma)},
{"Gcd",13,9,0,*((unsigned longlong *) at_Gcd)},
{"Gcdex",13,9,0,*((unsigned longlong *) at_Gcdex)},
{"Get",13,77,0,*((unsigned longlong *) at_Get)| 1},
{"GetCalc",13,77,0,*((unsigned longlong *) at_GetCalc)| 1},
{"GetFold",13,8,0,*((unsigned longlong *) at_GetFold)},
{"Graph",13,77,0,*((unsigned longlong *) at_Graph)},
{"HMSX",13,-124,0,*((unsigned longlong *) at_HMSX)},
{"Heaviside",13,9,0,*((unsigned longlong *) at_Heaviside)},
{"IDENMAT",13,-124,0,*((unsigned longlong *) at_IDENMAT)},
{"IFTE",13,85,0,*((unsigned longlong *) at_IFTE)},
{"IM",13,-124,0,*((unsigned longlong *) at_IM)},
{"INPUT",13,-124,0,*((unsigned longlong *) at_INPUT)| 1},
{"INT",13,-124,0,*((unsigned longlong *) at_INT)},
{"INVERSE",13,-124,0,*((unsigned longlong *) at_INVERSE)},
{"ISOLATE",13,-124,0,*((unsigned longlong *) at_ISOLATE)| 1},
{"ITERATE",13,-124,0,*((unsigned longlong *) at_ITERATE)| 1},
{"Input",13,77,0,*((unsigned longlong *) at_Input)| 1},
{"InputStr",13,77,0,*((unsigned longlong *) at_InputStr)| 1},
{"Int",13,9,0,*((unsigned longlong *) at_Int)},
{"Inverse",13,9,0,*((unsigned longlong *) at_Inverse)},
{"JordanBlock",13,9,0,*((unsigned longlong *) at_JordanBlock)},
{"LINE",13,-124,0,*((unsigned longlong *) at_LINE)},
{"LINEAR?",13,-124,0,*((unsigned longlong *) at_LINEAR?)| 1},
{"LN",13,-124,0,*((unsigned longlong *) at_LN)},
{"LNP1",13,-124,0,*((unsigned longlong *) at_LNP1)},
{"LOG",13,-124,0,*((unsigned longlong *) at_LOG)},
{"LQ",13,-124,0,*((unsigned longlong *) at_LQ)},
{"LSQ",13,-124,0,*((unsigned longlong *) at_LSQ)},
{"LU",13,9,0,*((unsigned longlong *) at_LU)| 1},
{"Line",13,77,0,*((unsigned longlong *) at_Line)},
{"LineHorz",13,77,0,*((unsigned longlong *) at_LineHorz)},
{"LineTan",13,77,0,*((unsigned longlong *) at_LineTan)},
{"LineVert",13,77,0,*((unsigned longlong *) at_LineVert)},
{"MAKELIST",13,-124,0,*((unsigned longlong *) at_MAKELIST)| 1},
{"MAKEMAT",13,-124,0,*((unsigned longlong *) at_MAKEMAT)| 1},
{"MANT",13,-124,0,*((unsigned longlong *) at_MANT)},
{"MAX",13,-124,0,*((unsigned longlong *) at_MAX)},
{"MAXREAL",13,77,0,*((unsigned longlong *) at_MAXREAL)},
{"MIN",13,-124,0,*((unsigned longlong *) at_MIN)},
{"MINREAL",13,77,0,*((unsigned longlong *) at_MINREAL)},
{"MOD",13,21,0,*((unsigned longlong *) at_MOD)},
{"MSGBOX",13,-124,0,*((unsigned longlong *) at_MSGBOX)},
{"NOP",13,85,0,*((unsigned longlong *) at_NOP)},
{"NTHROOT",13,23,0,*((unsigned longlong *) at_NTHROOT)},
{"NewFold",13,77,0,*((unsigned longlong *) at_NewFold)| 1},
{"NewPic",13,77,0,*((unsigned longlong *) at_NewPic)},
{"Nullspace",13,9,0,*((unsigned longlong *) at_Nullspace)},
{"OVER",13,85,0,*((unsigned longlong *) at_OVER)},
{"Output",13,77,0,*((unsigned longlong *) at_Output)},
{"Ox_2d_unit_vector",13,9,0,*((unsigned longlong *) at_Ox_2d_unit_vector)},
{"Ox_3d_unit_vector",13,9,0,*((unsigned longlong *) at_Ox_3d_unit_vector)},
{"Oy_2d_unit_vector",13,9,0,*((unsigned longlong *) at_Oy_2d_unit_vector)},
{"Oy_3d_unit_vector",13,9,0,*((unsigned longlong *) at_Oy_3d_unit_vector)},
{"Oz_3d_unit_vector",13,9,0,*((unsigned longlong *) at_Oz_3d_unit_vector)},
{"PERM",13,-124,0,*((unsigned longlong *) at_PERM)},
{"PICK",13,85,0,*((unsigned longlong *) at_PICK)},
{"PIXOFF",13,-124,0,*((unsigned longlong *) at_PIXOFF)},
{"PIXON",13,-124,0,*((unsigned longlong *) at_PIXON)},
{"POLYCOEF",13,-124,0,*((unsigned longlong *) at_POLYCOEF)| 1},
{"POLYEVAL",13,-124,0,*((unsigned longlong *) at_POLYEVAL)},
{"POLYFORM",13,-124,0,*((unsigned longlong *) at_POLYFORM)| 1},
{"POLYROOT",13,-124,0,*((unsigned longlong *) at_POLYROOT)| 1},
{"POS",13,-124,0,*((unsigned longlong *) at_POS)},
{"PRINT",13,-124,0,*((unsigned longlong *) at_PRINT)| 1},
{"Pause",13,77,0,*((unsigned longlong *) at_Pause)},
{"Phi",13,9,0,*((unsigned longlong *) at_Phi)},
{"Pictsize",13,9,0,*((unsigned longlong *) at_Pictsize)},
{"PopUp",13,77,0,*((unsigned longlong *) at_PopUp)| 1},
{"Prompt",13,77,0,*((unsigned longlong *) at_Prompt)| 1},
{"Psi",13,9,0,*((unsigned longlong *) at_Psi)},
{"Psi_minus_ln",13,9,0,*((unsigned longlong *) at_Psi_minus_ln)},
{"PtOff",13,77,0,*((unsigned longlong *) at_PtOff)},
{"PtOn",13,77,0,*((unsigned longlong *) at_PtOn)},
{"PtText",13,77,0,*((unsigned longlong *) at_PtText)},
{"PxlOff",13,77,0,*((unsigned longlong *) at_PxlOff)},
{"PxlOn",13,77,0,*((unsigned longlong *) at_PxlOn)},
{"QR",13,9,0,*((unsigned longlong *) at_QR)| 1},
{"QUAD",13,-124,0,*((unsigned longlong *) at_QUAD)| 1},
{"QUOTE",13,-124,0,*((unsigned longlong *) at_QUOTE)| 1},
{"Quo",13,9,0,*((unsigned longlong *) at_Quo)},
{"RADXDEG",13,-124,0,*((unsigned longlong *) at_RADXDEG)},
{"RANDMAT",13,-124,0,*((unsigned longlong *) at_RANDMAT)| 1},
{"RANDOM",13,77,0,*((unsigned longlong *) at_RANDOM)},
{"RANDSEED",13,77,0,*((unsigned longlong *) at_RANDSEED)},
{"RANK",13,-124,0,*((unsigned longlong *) at_RANK)},
{"RCL",13,85,0,*((unsigned longlong *) at_RCL)},
{"RE",13,-124,0,*((unsigned longlong *) at_RE)},
{"RECT",13,-124,0,*((unsigned longlong *) at_RECT)},
{"RECURSE",13,-124,0,*((unsigned longlong *) at_RECURSE)| 1},
{"REDIM",13,-124,0,*((unsigned longlong *) at_REDIM)| 1},
{"REPLACE",13,-124,0,*((unsigned longlong *) at_REPLACE)| 1},
{"REVERSE",13,-124,0,*((unsigned longlong *) at_REVERSE)},
{"ROUND",13,-124,0,*((unsigned longlong *) at_ROUND)},
{"ROWNORM",13,-124,0,*((unsigned longlong *) at_ROWNORM)},
{"RPN_CASE",13,85,0,*((unsigned longlong *) at_RPN_CASE)},
{"RPN_FOR",13,85,0,*((unsigned longlong *) at_RPN_FOR)},
{"RPN_LOCAL",13,85,0,*((unsigned longlong *) at_RPN_LOCAL)},
{"RPN_WHILE",13,85,0,*((unsigned longlong *) at_RPN_WHILE)},
{"RREF",13,-124,0,*((unsigned longlong *) at_RREF)},
{"RandSeed",13,77,0,*((unsigned longlong *) at_RandSeed)},
{"Rank",13,9,0,*((unsigned longlong *) at_Rank)},
{"RclPic",13,77,0,*((unsigned longlong *) at_RclPic)| 1},
{"Rem",13,9,0,*((unsigned longlong *) at_Rem)},
{"Resultant",13,9,0,*((unsigned longlong *) at_Resultant)},
{"RplcPic",13,77,0,*((unsigned longlong *) at_RplcPic)| 1},
{"Rref",13,9,0,*((unsigned longlong *) at_Rref)},
{"SCALE",13,-124,0,*((unsigned longlong *) at_SCALE)| 1},
{"SCALEADD",13,-124,0,*((unsigned longlong *) at_SCALEADD)| 1},
{"SCHUR",13,-124,0,*((unsigned longlong *) at_SCHUR)},
{"SEC",13,-124,0,*((unsigned longlong *) at_SEC)},
{"SIGN",13,-124,0,*((unsigned longlong *) at_SIGN)},
{"SIN",13,-124,0,*((unsigned longlong *) at_SIN)},
{"SINH",13,-124,0,*((unsigned longlong *) at_SINH)},
{"SIZE",13,-124,0,*((unsigned longlong *) at_SIZE)},
{"SORT",13,-124,0,*((unsigned longlong *) at_SORT)},
{"SPECNORM",13,-124,0,*((unsigned longlong *) at_SPECNORM)},
{"SPECRAD",13,-124,0,*((unsigned longlong *) at_SPECRAD)},
{"SUB",13,-124,0,*((unsigned longlong *) at_SUB)| 1},
{"SVD",13,-124,0,*((unsigned longlong *) at_SVD)},
{"SVL",13,-124,0,*((unsigned longlong *) at_SVL)},
{"SWAP",13,85,0,*((unsigned longlong *) at_SWAP)},
{"SWAPCOL",13,-124,0,*((unsigned longlong *) at_SWAPCOL)| 1},
{"SWAPROW",13,-124,0,*((unsigned longlong *) at_SWAPROW)| 1},
{"SetFold",13,77,0,*((unsigned longlong *) at_SetFold)| 1},
{"Si",13,9,0,*((unsigned longlong *) at_Si)},
{"SiCi_f",13,9,0,*((unsigned longlong *) at_SiCi_f)},
{"SiCi_g",13,9,0,*((unsigned longlong *) at_SiCi_g)},
{"SortA",13,77,0,*((unsigned longlong *) at_SortA)| 1},
{"SortD",13,77,0,*((unsigned longlong *) at_SortD)| 1},
{"StoPic",13,77,0,*((unsigned longlong *) at_StoPic)| 1},
{"Store",13,9,0,*((unsigned longlong *) at_Store)| 1},
{"Sum",13,9,0,*((unsigned longlong *) at_Sum)| 1},
{"TAN",13,-124,0,*((unsigned longlong *) at_TAN)},
{"TANH",13,-124,0,*((unsigned longlong *) at_TANH)},
{"TAYLOR",13,-124,0,*((unsigned longlong *) at_TAYLOR)| 1},
{"TRACE",13,-124,0,*((unsigned longlong *) at_TRACE)},
{"TRN",13,-124,0,*((unsigned longlong *) at_TRN)},
{"TRUNCATE",13,-124,0,*((unsigned longlong *) at_TRUNCATE)},
{"TeX",13,9,0,*((unsigned longlong *) at_TeX)},
{"UTPC",13,9,0,*((unsigned longlong *) at_UTPC)},
{"UTPF",13,9,0,*((unsigned longlong *) at_UTPF)},
{"UTPN",13,9,0,*((unsigned longlong *) at_UTPN)},
{"UTPT",13,9,0,*((unsigned longlong *) at_UTPT)},
{"Unarchiv",13,77,0,*((unsigned longlong *) at_Unarchiv)| 1},
{"VAS",13,9,0,*((unsigned longlong *) at_VAS)},
{"VAS_positive",13,9,0,*((unsigned longlong *) at_VAS_positive)},
{"VIEWS",13,77,0,*((unsigned longlong *) at_VIEWS)| 1},
{"WAIT",13,-124,0,*((unsigned longlong *) at_WAIT)},
{"XHMS",13,-124,0,*((unsigned longlong *) at_XHMS)},
{"XPON",13,-124,0,*((unsigned longlong *) at_XPON)},
{"Zeta",13,9,0,*((unsigned longlong *) at_Zeta)},
{"ZoomRcl",13,77,0,*((unsigned longlong *) at_ZoomRcl)},
{"ZoomSto",13,77,0,*((unsigned longlong *) at_ZoomSto)},
{"a2q",13,9,0,*((unsigned longlong *) at_a2q)},
{"abcuv",13,9,0,*((unsigned longlong *) at_abcuv)},
{"about",13,9,0,*((unsigned longlong *) at_about)},
{"abs",13,9,0,*((unsigned longlong *) at_abs)},
{"abscissa",13,9,0,*((unsigned longlong *) at_abscissa)},
{"accumulate_head_tail",13,9,0,*((unsigned longlong *) at_accumulate_head_tail)},
{"acos",13,9,0,*((unsigned longlong *) at_acos)},
{"acos2asin",13,9,0,*((unsigned longlong *) at_acos2asin)},
{"acos2atan",13,9,0,*((unsigned longlong *) at_acos2atan)},
{"acosh",13,9,0,*((unsigned longlong *) at_acosh)},
{"acot",13,9,0,*((unsigned longlong *) at_acot)},
{"acsc",13,9,0,*((unsigned longlong *) at_acsc)},
{"add",13,9,0,*((unsigned longlong *) at_add)| 1},
{"add_language",13,9,0,*((unsigned longlong *) at_add_language)},
{"additionally",13,9,0,*((unsigned longlong *) at_additionally)| 1},
{"adjoint_matrix",13,9,0,*((unsigned longlong *) at_adjoint_matrix)},
{"affix",13,9,0,*((unsigned longlong *) at_affix)},
{"alg",13,9,0,*((unsigned longlong *) at_alg)},
{"algvar",13,9,0,*((unsigned longlong *) at_algvar)},
{"alog10",13,9,0,*((unsigned longlong *) at_alog10)},
{"alors",13,49,0,*((unsigned longlong *) at_alors)| 1},
{"altitude",13,9,0,*((unsigned longlong *) at_altitude)},
{"and",13,33,0,*((unsigned longlong *) at_and)| 1},
{"angle",13,9,0,*((unsigned longlong *) at_angle)},
{"angleat",13,9,0,*((unsigned longlong *) at_angleat)| 1},
{"angleatraw",13,9,0,*((unsigned longlong *) at_angleatraw)},
{"animate",13,9,0,*((unsigned longlong *) at_animate)},
{"animate3d",13,9,0,*((unsigned longlong *) at_animate3d)},
{"animation",13,9,0,*((unsigned longlong *) at_animation)},
{"ans",13,9,0,*((unsigned longlong *) at_ans)},
{"append",13,9,0,*((unsigned longlong *) at_append)},
{"apply",13,9,0,*((unsigned longlong *) at_apply)},
{"approx",13,9,0,*((unsigned longlong *) at_approx)},
{"arc",13,9,0,*((unsigned longlong *) at_arc)| 1},
{"arcLen",13,9,0,*((unsigned longlong *) at_arcLen)},
{"archive",13,9,0,*((unsigned longlong *) at_archive)},
{"area",13,9,0,*((unsigned longlong *) at_area)},
{"areaat",13,9,0,*((unsigned longlong *) at_areaat)| 1},
{"areaatraw",13,9,0,*((unsigned longlong *) at_areaatraw)},
{"areaplot",13,9,0,*((unsigned longlong *) at_areaplot)},
{"arg",13,9,0,*((unsigned longlong *) at_arg)},
{"array",13,9,0,*((unsigned longlong *) at_array)},
{"array_sto",13,9,0,*((unsigned longlong *) at_array_sto)| 1},
{"as_function_of",13,9,0,*((unsigned longlong *) at_as_function_of)| 1},
{"asc",13,9,0,*((unsigned longlong *) at_asc)},
{"asec",13,9,0,*((unsigned longlong *) at_asec)},
{"asin",13,9,0,*((unsigned longlong *) at_asin)},
{"asin2acos",13,9,0,*((unsigned longlong *) at_asin2acos)},
{"asin2atan",13,9,0,*((unsigned longlong *) at_asin2atan)},
{"asinh",13,9,0,*((unsigned longlong *) at_asinh)},
{"assign",13,9,0,*((unsigned longlong *) at_assign)},
{"assume",13,9,0,*((unsigned longlong *) at_assume)| 1},
{"atan",13,9,0,*((unsigned longlong *) at_atan)},
{"atan2acos",13,9,0,*((unsigned longlong *) at_atan2acos)},
{"atan2asin",13,9,0,*((unsigned longlong *) at_atan2asin)},
{"atanh",13,9,0,*((unsigned longlong *) at_atanh)},
{"atrig2ln",13,9,0,*((unsigned longlong *) at_atrig2ln)},
{"augment",13,9,0,*((unsigned longlong *) at_augment)},
{"avance",13,126,0,*((unsigned longlong *) at_avance)},
{"avgRC",13,9,0,*((unsigned longlong *) at_avgRC)},
{"background",13,9,0,*((unsigned longlong *) at_background)| 1},
{"baisse_crayon",13,126,0,*((unsigned longlong *) at_baisse_crayon)},
{"bar_plot",13,9,0,*((unsigned longlong *) at_bar_plot)},
{"barycenter",13,9,0,*((unsigned longlong *) at_barycenter)},
{"basis",13,9,0,*((unsigned longlong *) at_basis)},
{"bernoulli",13,9,0,*((unsigned longlong *) at_bernoulli)},
{"bezout_entiers",13,9,0,*((unsigned longlong *) at_bezout_entiers)},
{"binomial",13,9,0,*((unsigned longlong *) at_binomial)},
{"binomial_cdf",13,9,0,*((unsigned longlong *) at_binomial_cdf)},
{"binomial_icdf",13,9,0,*((unsigned longlong *) at_binomial_icdf)},
{"binprint",13,9,0,*((unsigned longlong *) at_binprint)},
{"bisector",13,9,0,*((unsigned longlong *) at_bisector)},
{"bitand",13,9,0,*((unsigned longlong *) at_bitand)},
{"bitmap",13,9,0,*((unsigned longlong *) at_bitmap)},
{"bitor",13,9,0,*((unsigned longlong *) at_bitor)},
{"bitxor",13,9,0,*((unsigned longlong *) at_bitxor)},
{"black",13,2,0,*((unsigned longlong *) at_black)},
{"blockmatrix",13,9,0,*((unsigned longlong *) at_blockmatrix)},
{"blue",13,2,0,*((unsigned longlong *) at_blue)},
{"border",13,9,0,*((unsigned longlong *) at_border)},
{"bounded_function",13,9,0,*((unsigned longlong *) at_bounded_function)},
{"boxwhisker",13,9,0,*((unsigned longlong *) at_boxwhisker)},
{"break",13,68,0,*((unsigned longlong *) at_break)},
{"breakpoint",13,9,0,*((unsigned longlong *) at_breakpoint)| 1},
{"c1oc2",13,9,0,*((unsigned longlong *) at_c1oc2)},
{"c1op2",13,9,0,*((unsigned longlong *) at_c1op2)},
{"cFactor",13,9,0,*((unsigned longlong *) at_cFactor)},
{"cSolve",13,9,0,*((unsigned longlong *) at_cSolve)| 1},
{"cZeros",13,9,0,*((unsigned longlong *) at_cZeros)| 1},
{"cache_tortue",13,126,0,*((unsigned longlong *) at_cache_tortue)},
{"calc_mode",13,9,0,*((unsigned longlong *) at_calc_mode)},
{"camembert",13,9,0,*((unsigned longlong *) at_camembert)},
{"canonical_form",13,9,0,*((unsigned longlong *) at_canonical_form)},
{"cap",13,126,0,*((unsigned longlong *) at_cap)},
{"cas_setup",13,9,0,*((unsigned longlong *) at_cas_setup)},
{"cat",13,9,0,*((unsigned longlong *) at_cat)},
{"cd",13,9,0,*((unsigned longlong *) at_cd)},
{"ceil",13,9,0,*((unsigned longlong *) at_ceil)},
{"ceiling",13,9,0,*((unsigned longlong *) at_ceiling)},
{"cell",13,9,0,*((unsigned longlong *) at_cell)},
{"center",13,9,0,*((unsigned longlong *) at_center)},
{"center2interval",13,9,0,*((unsigned longlong *) at_center2interval)},
{"centered_cube",13,9,0,*((unsigned longlong *) at_centered_cube)},
{"centered_tetrahedron",13,9,0,*((unsigned longlong *) at_centered_tetrahedron)},
{"cfactor",13,9,0,*((unsigned longlong *) at_cfactor)},
{"changebase",13,9,0,*((unsigned longlong *) at_changebase)},
{"char",13,9,0,*((unsigned longlong *) at_char)},
{"charpoly",13,9,0,*((unsigned longlong *) at_charpoly)},
{"chinrem",13,9,0,*((unsigned longlong *) at_chinrem)},
{"chisquare",13,9,0,*((unsigned longlong *) at_chisquare)},
{"chisquare_cdf",13,9,0,*((unsigned longlong *) at_chisquare_cdf)},
{"chisquare_icdf",13,9,0,*((unsigned longlong *) at_chisquare_icdf)},
{"cholesky",13,9,0,*((unsigned longlong *) at_cholesky)},
{"choosebox",13,9,0,*((unsigned longlong *) at_choosebox)| 1},
{"chrem",13,9,0,*((unsigned longlong *) at_chrem)},
{"circle",13,9,0,*((unsigned longlong *) at_circle)| 1},
{"circumcircle",13,9,0,*((unsigned longlong *) at_circumcircle)},
{"classes",13,9,0,*((unsigned longlong *) at_classes)},
{"click",13,9,0,*((unsigned longlong *) at_click)| 1},
{"close",13,9,0,*((unsigned longlong *) at_close)},
{"coeff",13,9,0,*((unsigned longlong *) at_coeff)},
{"coeffs",13,9,0,*((unsigned longlong *) at_coeffs)},
{"col",13,9,0,*((unsigned longlong *) at_col)},
{"colDim",13,9,0,*((unsigned longlong *) at_colDim)},
{"colNorm",13,9,0,*((unsigned longlong *) at_colNorm)},
{"coldim",13,9,0,*((unsigned longlong *) at_coldim)},
{"collect",13,9,0,*((unsigned longlong *) at_collect)},
{"colnorm",13,9,0,*((unsigned longlong *) at_colnorm)},
{"color",13,9,0,*((unsigned longlong *) at_color)},
{"colspace",13,9,0,*((unsigned longlong *) at_colspace)},
{"comDenom",13,9,0,*((unsigned longlong *) at_comDenom)},
{"comb",13,9,0,*((unsigned longlong *) at_comb)},
{"combine",13,9,0,*((unsigned longlong *) at_combine)},
{"comment",13,9,0,*((unsigned longlong *) at_comment)},
{"common_perpendicular",13,9,0,*((unsigned longlong *) at_common_perpendicular)},
{"companion",13,9,0,*((unsigned longlong *) at_companion)},
{"compare",13,9,0,*((unsigned longlong *) at_compare)},
{"complexroot",13,9,0,*((unsigned longlong *) at_complexroot)},
{"concat",13,9,0,*((unsigned longlong *) at_concat)},
{"cone",13,9,0,*((unsigned longlong *) at_cone)},
{"conic",13,9,0,*((unsigned longlong *) at_conic)},
{"conj",13,9,0,*((unsigned longlong *) at_conj)},
{"cont",13,9,0,*((unsigned longlong *) at_cont)| 1},
{"contains",13,9,0,*((unsigned longlong *) at_contains)},
{"content",13,9,0,*((unsigned longlong *) at_content)},
{"contourplot",13,9,0,*((unsigned longlong *) at_contourplot)| 1},
{"convert",13,9,0,*((unsigned longlong *) at_convert)},
{"convertir",13,9,0,*((unsigned longlong *) at_convertir)},
{"convexhull",13,9,0,*((unsigned longlong *) at_convexhull)},
{"coordinates",13,9,0,*((unsigned longlong *) at_coordinates)},
{"copy",13,9,0,*((unsigned longlong *) at_copy)},
{"correlation",13,9,0,*((unsigned longlong *) at_correlation)},
{"cos",13,9,0,*((unsigned longlong *) at_cos)},
{"cos2sintan",13,9,0,*((unsigned longlong *) at_cos2sintan)},
{"cosh",13,9,0,*((unsigned longlong *) at_cosh)},
{"cot",13,9,0,*((unsigned longlong *) at_cot)},
{"cote",13,9,0,*((unsigned longlong *) at_cote)},
{"count",13,9,0,*((unsigned longlong *) at_count)},
{"count_eq",13,9,0,*((unsigned longlong *) at_count_eq)},
{"count_inf",13,9,0,*((unsigned longlong *) at_count_inf)},
{"count_sup",13,9,0,*((unsigned longlong *) at_count_sup)},
{"courbe_parametrique",13,9,0,*((unsigned longlong *) at_courbe_parametrique)| 1},
{"courbe_polaire",13,9,0,*((unsigned longlong *) at_courbe_polaire)| 1},
{"covariance",13,9,0,*((unsigned longlong *) at_covariance)},
{"covariance_correlation",13,9,0,*((unsigned longlong *) at_covariance_correlation)},
{"cpartfrac",13,9,0,*((unsigned longlong *) at_cpartfrac)},
{"crationalroot",13,9,0,*((unsigned longlong *) at_crationalroot)},
{"crayon",13,126,0,*((unsigned longlong *) at_crayon)},
{"cross",13,9,0,*((unsigned longlong *) at_cross)},
{"crossP",13,9,0,*((unsigned longlong *) at_crossP)},
{"cross_ratio",13,9,0,*((unsigned longlong *) at_cross_ratio)},
{"crossproduct",13,9,0,*((unsigned longlong *) at_crossproduct)},
{"csc",13,9,0,*((unsigned longlong *) at_csc)},
{"csolve",13,9,0,*((unsigned longlong *) at_csolve)| 1},
{"csv2gen",13,9,0,*((unsigned longlong *) at_csv2gen)},
{"cube",13,9,0,*((unsigned longlong *) at_cube)},
{"cumSum",13,9,0,*((unsigned longlong *) at_cumSum)},
{"cumulated_frequencies",13,9,0,*((unsigned longlong *) at_cumulated_frequencies)},
{"curl",13,9,0,*((unsigned longlong *) at_curl)| 1},
{"current_sheet",13,9,0,*((unsigned longlong *) at_current_sheet)| 1},
{"curve",13,9,0,*((unsigned longlong *) at_curve)},
{"cyan",13,2,0,*((unsigned longlong *) at_cyan)},
{"cycle2perm",13,9,0,*((unsigned longlong *) at_cycle2perm)},
{"cycleinv",13,9,0,*((unsigned longlong *) at_cycleinv)},
{"cycles2permu",13,9,0,*((unsigned longlong *) at_cycles2permu)},
{"cyclotomic",13,9,0,*((unsigned longlong *) at_cyclotomic)},
{"cylinder",13,9,0,*((unsigned longlong *) at_cylinder)},
{"de",13,57,0,*((unsigned longlong *) at_de)| 1},
{"deSolve",13,77,0,*((unsigned longlong *) at_deSolve)| 1},
{"debug",13,9,0,*((unsigned longlong *) at_debug)| 1},
{"debug_infolevel",13,9,0,*((unsigned longlong *) at_debug_infolevel)},
{"debut_enregistrement",13,126,0,*((unsigned longlong *) at_debut_enregistrement)},
{"decrement",13,9,0,*((unsigned longlong *) at_decrement)| 1},
{"degree",13,9,0,*((unsigned longlong *) at_degree)},
{"delcols",13,9,0,*((unsigned longlong *) at_delcols)},
{"delrows",13,9,0,*((unsigned longlong *) at_delrows)},
{"deltalist",13,9,0,*((unsigned longlong *) at_deltalist)},
{"denom",13,9,0,*((unsigned longlong *) at_denom)},
{"densityplot",13,9,0,*((unsigned longlong *) at_densityplot)| 1},
{"deriver",13,9,0,*((unsigned longlong *) at_deriver)},
{"desolve",13,9,0,*((unsigned longlong *) at_desolve)| 1},
{"dessine_tortue",13,126,0,*((unsigned longlong *) at_dessine_tortue)},
{"det",13,9,0,*((unsigned longlong *) at_det)},
{"det_minor",13,9,0,*((unsigned longlong *) at_det_minor)},
{"developper",13,9,0,*((unsigned longlong *) at_developper)},
{"developper_transcendant",13,9,0,*((unsigned longlong *) at_developper_transcendant)},
{"dfc",13,9,0,*((unsigned longlong *) at_dfc)},
{"dfc2f",13,9,0,*((unsigned longlong *) at_dfc2f)},
{"diag",13,9,0,*((unsigned longlong *) at_diag)},
{"diff",13,9,0,*((unsigned longlong *) at_diff)| 1},
{"dim",13,9,0,*((unsigned longlong *) at_dim)},
{"display",13,9,0,*((unsigned longlong *) at_display)},
{"disque",13,126,0,*((unsigned longlong *) at_disque)},
{"disque_centre",13,126,0,*((unsigned longlong *) at_disque_centre)},
{"distance",13,9,0,*((unsigned longlong *) at_distance)},
{"distance2",13,9,0,*((unsigned longlong *) at_distance2)},
{"distanceat",13,9,0,*((unsigned longlong *) at_distanceat)| 1},
{"distanceatraw",13,9,0,*((unsigned longlong *) at_distanceatraw)},
{"div",13,22,0,*((unsigned longlong *) at_div)},
{"divcrement",13,9,0,*((unsigned longlong *) at_divcrement)| 1},
{"divergence",13,9,0,*((unsigned longlong *) at_divergence)| 1},
{"divide",13,9,0,*((unsigned longlong *) at_divide)},
{"divis",13,9,0,*((unsigned longlong *) at_divis)},
{"division_point",13,9,0,*((unsigned longlong *) at_division_point)},
{"divisors",13,9,0,*((unsigned longlong *) at_divisors)},
{"divpc",13,9,0,*((unsigned longlong *) at_divpc)},
{"dodecahedron",13,9,0,*((unsigned longlong *) at_dodecahedron)},
{"dot",13,9,0,*((unsigned longlong *) at_dot)},
{"dotP",13,9,0,*((unsigned longlong *) at_dotP)},
{"dot_paper",13,9,0,*((unsigned longlong *) at_dot_paper)},
{"dotprod",13,9,0,*((unsigned longlong *) at_dotprod)},
{"droit",13,9,0,*((unsigned longlong *) at_droit)},
{"droite_tangente",13,9,0,*((unsigned longlong *) at_droite_tangente)},
{"dsolve",13,9,0,*((unsigned longlong *) at_dsolve)| 1},
{"e2r",13,9,0,*((unsigned longlong *) at_e2r)},
{"ecart_type",13,9,0,*((unsigned longlong *) at_ecart_type)},
{"ecart_type_population",13,9,0,*((unsigned longlong *) at_ecart_type_population)},
{"ecris",13,126,0,*((unsigned longlong *) at_ecris)},
{"efface",13,126,0,*((unsigned longlong *) at_efface)},
{"egcd",13,9,0,*((unsigned longlong *) at_egcd)},
{"egv",13,9,0,*((unsigned longlong *) at_egv)},
{"egvl",13,9,0,*((unsigned longlong *) at_egvl)},
{"eigVc",13,9,0,*((unsigned longlong *) at_eigVc)},
{"eigVl",13,9,0,*((unsigned longlong *) at_eigVl)},
{"eigenvals",13,9,0,*((unsigned longlong *) at_eigenvals)},
{"eigenvalues",13,9,0,*((unsigned longlong *) at_eigenvalues)},
{"eigenvectors",13,9,0,*((unsigned longlong *) at_eigenvectors)},
{"eigenvects",13,9,0,*((unsigned longlong *) at_eigenvects)},
{"element",13,9,0,*((unsigned longlong *) at_element)},
{"ellipse",13,9,0,*((unsigned longlong *) at_ellipse)},
{"entry",13,9,0,*((unsigned longlong *) at_entry)},
{"envelope",13,9,0,*((unsigned longlong *) at_envelope)},
{"epsilon2zero",13,9,0,*((unsigned longlong *) at_epsilon2zero)| 1},
{"equal2diff",13,9,0,*((unsigned longlong *) at_equal2diff)},
{"equal2list",13,9,0,*((unsigned longlong *) at_equal2list)},
{"equation",13,9,0,*((unsigned longlong *) at_equation)},
{"equilateral_triangle",13,9,0,*((unsigned longlong *) at_equilateral_triangle)| 1},
{"erase3d",13,9,0,*((unsigned longlong *) at_erase3d)},
{"erf",13,9,0,*((unsigned longlong *) at_erf)},
{"erfc",13,9,0,*((unsigned longlong *) at_erfc)},
{"erfs",13,9,0,*((unsigned longlong *) at_erfs)},
{"et",13,33,0,*((unsigned longlong *) at_et)| 1},
{"euler",13,9,0,*((unsigned longlong *) at_euler)},
{"euler_mac_laurin",13,9,0,*((unsigned longlong *) at_euler_mac_laurin)},
{"eval",13,9,0,*((unsigned longlong *) at_eval)| 1},
{"eval_level",13,9,0,*((unsigned longlong *) at_eval_level)},
{"evala",13,9,0,*((unsigned longlong *) at_evala)},
{"evalb",13,9,0,*((unsigned longlong *) at_evalb)| 1},
{"evalc",13,9,0,*((unsigned longlong *) at_evalc)},
{"evalf",13,9,0,*((unsigned longlong *) at_evalf)},
{"evalm",13,9,0,*((unsigned longlong *) at_evalm)},
{"even",13,9,0,*((unsigned longlong *) at_even)},
{"exact",13,9,0,*((unsigned longlong *) at_exact)},
{"exbisector",13,9,0,*((unsigned longlong *) at_exbisector)},
{"excircle",13,9,0,*((unsigned longlong *) at_excircle)},
{"execute",13,9,0,*((unsigned longlong *) at_execute)},
{"exp",13,9,0,*((unsigned longlong *) at_exp)},
{"exp2list",13,9,0,*((unsigned longlong *) at_exp2list)| 1},
{"exp2pow",13,9,0,*((unsigned longlong *) at_exp2pow)},
{"exp2trig",13,9,0,*((unsigned longlong *) at_exp2trig)},
{"expexpand",13,9,0,*((unsigned longlong *) at_expexpand)},
{"exponential_regression",13,9,0,*((unsigned longlong *) at_exponential_regression)},
{"exponential_regression_plot",13,9,0,*((unsigned longlong *) at_exponential_regression_plot)},
{"expr",13,9,0,*((unsigned longlong *) at_expr)},
{"extract_measure",13,9,0,*((unsigned longlong *) at_extract_measure)},
{"ezgcd",13,9,0,*((unsigned longlong *) at_ezgcd)},
{"f2nd",13,9,0,*((unsigned longlong *) at_f2nd)},
{"fMax",13,9,0,*((unsigned longlong *) at_fMax)},
{"fMin",13,9,0,*((unsigned longlong *) at_fMin)},
{"fPart",13,9,0,*((unsigned longlong *) at_fPart)},
{"faces",13,9,0,*((unsigned longlong *) at_faces)},
{"facteurs_premiers",13,9,0,*((unsigned longlong *) at_facteurs_premiers)},
{"factor",13,9,0,*((unsigned longlong *) at_factor)},
{"factor_xn",13,9,0,*((unsigned longlong *) at_factor_xn)},
{"factorial",13,9,0,*((unsigned longlong *) at_factorial)},
{"factoriser",13,9,0,*((unsigned longlong *) at_factoriser)},
{"factoriser_entier",13,9,0,*((unsigned longlong *) at_factoriser_entier)},
{"factoriser_sur_C",13,9,0,*((unsigned longlong *) at_factoriser_sur_C)},
{"factoriser_xn",13,9,0,*((unsigned longlong *) at_factoriser_xn)},
{"factors",13,9,0,*((unsigned longlong *) at_factors)},
{"faire",13,59,0,*((unsigned longlong *) at_faire)| 1},
{"fclose",13,9,0,*((unsigned longlong *) at_fclose)},
{"fcoeff",13,9,0,*((unsigned longlong *) at_fcoeff)},
{"ffaire",13,76,0,*((unsigned longlong *) at_ffaire)| 1},
{"ffonction",13,76,0,*((unsigned longlong *) at_ffonction)| 1},
{"fft",13,9,0,*((unsigned longlong *) at_fft)},
{"fieldplot",13,9,0,*((unsigned longlong *) at_fieldplot)},
{"filled",13,2,0,*((unsigned longlong *) at_filled)},
{"fin_enregistrement",13,126,0,*((unsigned longlong *) at_fin_enregistrement)},
{"findhelp",13,9,0,*((unsigned longlong *) at_findhelp)| 1},
{"fisher",13,9,0,*((unsigned longlong *) at_fisher)},
{"fisher_cdf",13,9,0,*((unsigned longlong *) at_fisher_cdf)},
{"fisher_icdf",13,9,0,*((unsigned longlong *) at_fisher_icdf)},
{"float",13,9,0,*((unsigned longlong *) at_float)},
{"float2rational",13,9,0,*((unsigned longlong *) at_float2rational)},
{"floor",13,9,0,*((unsigned longlong *) at_floor)},
{"fonction",13,73,0,*((unsigned longlong *) at_fonction)| 1},
{"fonction_derivee",13,9,0,*((unsigned longlong *) at_fonction_derivee)},
{"fopen",13,9,0,*((unsigned longlong *) at_fopen)},
{"format",13,9,0,*((unsigned longlong *) at_format)},
{"fourier_an",13,9,0,*((unsigned longlong *) at_fourier_an)},
{"fourier_bn",13,9,0,*((unsigned longlong *) at_fourier_bn)},
{"fourier_cn",13,9,0,*((unsigned longlong *) at_fourier_cn)},
{"fpour",13,76,0,*((unsigned longlong *) at_fpour)| 1},
{"fprint",13,9,0,*((unsigned longlong *) at_fprint)},
{"frac",13,9,0,*((unsigned longlong *) at_frac)},
{"fracmod",13,9,0,*((unsigned longlong *) at_fracmod)},
{"frame_2d",13,9,0,*((unsigned longlong *) at_frame_2d)},
{"frame_3d",13,9,0,*((unsigned longlong *) at_frame_3d)},
{"froot",13,9,0,*((unsigned longlong *) at_froot)},
{"fsi",13,76,0,*((unsigned longlong *) at_fsi)| 1},
{"fsolve",13,9,0,*((unsigned longlong *) at_fsolve)| 1},
{"ftantque",13,76,0,*((unsigned longlong *) at_ftantque)| 1},
{"funcplot",13,9,0,*((unsigned longlong *) at_funcplot)| 1},
{"function_diff",13,9,0,*((unsigned longlong *) at_function_diff)},
{"fxnd",13,9,0,*((unsigned longlong *) at_fxnd)},
{"gauche",13,9,0,*((unsigned longlong *) at_gauche)},
{"gauss",13,9,0,*((unsigned longlong *) at_gauss)},
{"gaussjord",13,9,0,*((unsigned longlong *) at_gaussjord)},
{"gbasis",13,9,0,*((unsigned longlong *) at_gbasis)},
{"gcd",13,9,0,*((unsigned longlong *) at_gcd)},
{"gcdex",13,9,0,*((unsigned longlong *) at_gcdex)},
{"genpoly",13,9,0,*((unsigned longlong *) at_genpoly)},
{"geo2d",13,9,0,*((unsigned longlong *) at_geo2d)},
{"geo3d",13,9,0,*((unsigned longlong *) at_geo3d)},
{"getDenom",13,9,0,*((unsigned longlong *) at_getDenom)},
{"getKey",13,9,0,*((unsigned longlong *) at_getKey)},
{"getNum",13,9,0,*((unsigned longlong *) at_getNum)},
{"getType",13,9,0,*((unsigned longlong *) at_getType)},
{"giac",13,9,0,*((unsigned longlong *) at_giac)},
{"goto",13,77,0,*((unsigned longlong *) at_goto)},
{"grad",13,9,0,*((unsigned longlong *) at_grad)| 1},
{"gramschmidt",13,9,0,*((unsigned longlong *) at_gramschmidt)},
{"graph2tex",13,9,0,*((unsigned longlong *) at_graph2tex)},
{"graph3d2tex",13,9,0,*((unsigned longlong *) at_graph3d2tex)},
{"graphe",13,9,0,*((unsigned longlong *) at_graphe)| 1},
{"graphe3d",13,9,0,*((unsigned longlong *) at_graphe3d)},
{"graphe_suite",13,9,0,*((unsigned longlong *) at_graphe_suite)},
{"greduce",13,9,0,*((unsigned longlong *) at_greduce)},
{"green",13,2,0,*((unsigned longlong *) at_green)},
{"grid_paper",13,9,0,*((unsigned longlong *) at_grid_paper)},
{"groupermu",13,9,0,*((unsigned longlong *) at_groupermu)},
{"hadamard",13,9,0,*((unsigned longlong *) at_hadamard)},
{"half_cone",13,9,0,*((unsigned longlong *) at_half_cone)},
{"half_line",13,9,0,*((unsigned longlong *) at_half_line)},
{"halftan",13,9,0,*((unsigned longlong *) at_halftan)},
{"halftan_hyp2exp",13,9,0,*((unsigned longlong *) at_halftan_hyp2exp)},
{"halt",13,9,0,*((unsigned longlong *) at_halt)| 1},
{"hamdist",13,9,0,*((unsigned longlong *) at_hamdist)},
{"harmonic_conjugate",13,9,0,*((unsigned longlong *) at_harmonic_conjugate)},
{"harmonic_division",13,9,0,*((unsigned longlong *) at_harmonic_division)| 1},
{"has",13,9,0,*((unsigned longlong *) at_has)},
{"hasard",13,126,0,*((unsigned longlong *) at_hasard)},
{"head",13,9,0,*((unsigned longlong *) at_head)},
{"heap_mult",13,9,0,*((unsigned longlong *) at_heap_mult)},
{"hermite",13,9,0,*((unsigned longlong *) at_hermite)},
{"hessenberg",13,9,0,*((unsigned longlong *) at_hessenberg)},
{"hessian",13,9,0,*((unsigned longlong *) at_hessian)| 1},
{"heugcd",13,9,0,*((unsigned longlong *) at_heugcd)},
{"hexagon",13,9,0,*((unsigned longlong *) at_hexagon)| 1},
{"hexprint",13,9,0,*((unsigned longlong *) at_hexprint)},
{"hidden_name",13,2,0,*((unsigned longlong *) at_hidden_name)},
{"hilbert",13,9,0,*((unsigned longlong *) at_hilbert)},
{"histogram",13,9,0,*((unsigned longlong *) at_histogram)},
{"hold",13,9,0,*((unsigned longlong *) at_hold)| 1},
{"homothety",13,9,0,*((unsigned longlong *) at_homothety)},
{"horner",13,9,0,*((unsigned longlong *) at_horner)},
{"hp38",13,9,0,*((unsigned longlong *) at_hp38)},
{"hyp2exp",13,9,0,*((unsigned longlong *) at_hyp2exp)},
{"hyperbola",13,9,0,*((unsigned longlong *) at_hyperbola)},
{"hyperplan",13,9,0,*((unsigned longlong *) at_hyperplan)},
{"hypersphere",13,9,0,*((unsigned longlong *) at_hypersphere)},
{"hypersurface",13,9,0,*((unsigned longlong *) at_hypersurface)},
{"iPart",13,9,0,*((unsigned longlong *) at_iPart)},
{"iabcuv",13,9,0,*((unsigned longlong *) at_iabcuv)},
{"ibasis",13,9,0,*((unsigned longlong *) at_ibasis)},
{"ibpdv",13,9,0,*((unsigned longlong *) at_ibpdv)},
{"ibpu",13,9,0,*((unsigned longlong *) at_ibpu)},
{"ichinrem",13,9,0,*((unsigned longlong *) at_ichinrem)},
{"ichrem",13,9,0,*((unsigned longlong *) at_ichrem)},
{"icontent",13,9,0,*((unsigned longlong *) at_icontent)},
{"icosahedron",13,9,0,*((unsigned longlong *) at_icosahedron)},
{"id",13,9,0,*((unsigned longlong *) at_id)},
{"identity",13,9,0,*((unsigned longlong *) at_identity)},
{"idivis",13,9,0,*((unsigned longlong *) at_idivis)},
{"idn",13,9,0,*((unsigned longlong *) at_idn)},
{"iegcd",13,9,0,*((unsigned longlong *) at_iegcd)},
{"ifactor",13,9,0,*((unsigned longlong *) at_ifactor)},
{"ifactors",13,9,0,*((unsigned longlong *) at_ifactors)},
{"ifft",13,9,0,*((unsigned longlong *) at_ifft)},
{"igcd",13,9,0,*((unsigned longlong *) at_igcd)},
{"igcdex",13,9,0,*((unsigned longlong *) at_igcdex)},
{"ihermite",13,9,0,*((unsigned longlong *) at_ihermite)},
{"ilaplace",13,9,0,*((unsigned longlong *) at_ilaplace)},
{"im",13,9,0,*((unsigned longlong *) at_im)},
{"imag",13,9,0,*((unsigned longlong *) at_imag)},
{"image",13,9,0,*((unsigned longlong *) at_image)},
{"implicitplot",13,9,0,*((unsigned longlong *) at_implicitplot)},
{"implicitplot3d",13,9,0,*((unsigned longlong *) at_implicitplot3d)},
{"inString",13,9,0,*((unsigned longlong *) at_inString)},
{"in_ideal",13,9,0,*((unsigned longlong *) at_in_ideal)},
{"incircle",13,9,0,*((unsigned longlong *) at_incircle)},
{"increment",13,9,0,*((unsigned longlong *) at_increment)| 1},
{"indets",13,9,0,*((unsigned longlong *) at_indets)},
{"inequationplot",13,9,0,*((unsigned longlong *) at_inequationplot)| 1},
{"input",13,9,0,*((unsigned longlong *) at_input)| 1},
{"inputform",13,9,0,*((unsigned longlong *) at_inputform)| 1},
{"insmod",13,9,0,*((unsigned longlong *) at_insmod)},
{"int",13,9,0,*((unsigned longlong *) at_int)},
{"intDiv",13,9,0,*((unsigned longlong *) at_intDiv)},
{"integer_format",13,9,0,*((unsigned longlong *) at_integer_format)},
{"integrate",13,9,0,*((unsigned longlong *) at_integrate)| 1},
{"integrer",13,9,0,*((unsigned longlong *) at_integrer)},
{"inter",13,9,0,*((unsigned longlong *) at_inter)},
{"interactive",13,9,0,*((unsigned longlong *) at_interactive)| 1},
{"interactive_odeplot",13,9,0,*((unsigned longlong *) at_interactive_odeplot)},
{"interactive_plotode",13,9,0,*((unsigned longlong *) at_interactive_plotode)},
{"interp",13,9,0,*((unsigned longlong *) at_interp)},
{"interval2center",13,9,0,*((unsigned longlong *) at_interval2center)},
{"inv",13,9,0,*((unsigned longlong *) at_inv)},
{"inverse",13,9,0,*((unsigned longlong *) at_inverse)},
{"inversion",13,9,0,*((unsigned longlong *) at_inversion)},
{"invlaplace",13,9,0,*((unsigned longlong *) at_invlaplace)},
{"invztrans",13,9,0,*((unsigned longlong *) at_invztrans)},
{"iquo",13,9,0,*((unsigned longlong *) at_iquo)},
{"iquorem",13,9,0,*((unsigned longlong *) at_iquorem)},
{"iratrecon",13,9,0,*((unsigned longlong *) at_iratrecon)},
{"irem",13,9,0,*((unsigned longlong *) at_irem)},
{"isPrime",13,9,0,*((unsigned longlong *) at_isPrime)},
{"is_collinear",13,9,0,*((unsigned longlong *) at_is_collinear)},
{"is_concyclic",13,9,0,*((unsigned longlong *) at_is_concyclic)},
{"is_conjugate",13,9,0,*((unsigned longlong *) at_is_conjugate)},
{"is_coplanar",13,9,0,*((unsigned longlong *) at_is_coplanar)},
{"is_cospheric",13,9,0,*((unsigned longlong *) at_is_cospheric)},
{"is_cycle",13,9,0,*((unsigned longlong *) at_is_cycle)},
{"is_element",13,9,0,*((unsigned longlong *) at_is_element)},
{"is_equilateral",13,9,0,*((unsigned longlong *) at_is_equilateral)},
{"is_harmonic",13,9,0,*((unsigned longlong *) at_is_harmonic)},
{"is_harmonic_circle_bundle",13,9,0,*((unsigned longlong *) at_is_harmonic_circle_bundle)},
{"is_harmonic_line_bundle",13,9,0,*((unsigned longlong *) at_is_harmonic_line_bundle)},
{"is_included",13,9,0,*((unsigned longlong *) at_is_included)},
{"is_isoceles",13,9,0,*((unsigned longlong *) at_is_isoceles)},
{"is_orthogonal",13,9,0,*((unsigned longlong *) at_is_orthogonal)},
{"is_parallel",13,9,0,*((unsigned longlong *) at_is_parallel)},
{"is_parallelogram",13,9,0,*((unsigned longlong *) at_is_parallelogram)},
{"is_permu",13,9,0,*((unsigned longlong *) at_is_permu)},
{"is_perpendicular",13,9,0,*((unsigned longlong *) at_is_perpendicular)},
{"is_prime",13,9,0,*((unsigned longlong *) at_is_prime)},
{"is_pseudoprime",13,9,0,*((unsigned longlong *) at_is_pseudoprime)},
{"is_rectangle",13,9,0,*((unsigned longlong *) at_is_rectangle)},
{"is_rhombus",13,9,0,*((unsigned longlong *) at_is_rhombus)},
{"is_square",13,9,0,*((unsigned longlong *) at_is_square)},
{"ismith",13,9,0,*((unsigned longlong *) at_ismith)},
{"isobarycenter",13,9,0,*((unsigned longlong *) at_isobarycenter)},
{"isoceles_triangle",13,9,0,*((unsigned longlong *) at_isoceles_triangle)| 1},
{"isom",13,9,0,*((unsigned longlong *) at_isom)},
{"isopolygon",13,9,0,*((unsigned longlong *) at_isopolygon)},
{"isprime",13,9,0,*((unsigned longlong *) at_isprime)},
{"ithprime",13,9,0,*((unsigned longlong *) at_ithprime)},
{"jacobi_symbol",13,9,0,*((unsigned longlong *) at_jacobi_symbol)},
{"jordan",13,9,0,*((unsigned longlong *) at_jordan)},
{"jusque",13,58,0,*((unsigned longlong *) at_jusque)| 1},
{"ker",13,9,0,*((unsigned longlong *) at_ker)},
{"kernel",13,9,0,*((unsigned longlong *) at_kernel)},
{"keyboard",13,9,0,*((unsigned longlong *) at_keyboard)},
{"kill",13,9,0,*((unsigned longlong *) at_kill)},
{"l1norm",13,9,0,*((unsigned longlong *) at_l1norm)},
{"l2norm",13,9,0,*((unsigned longlong *) at_l2norm)},
{"label",13,77,0,*((unsigned longlong *) at_label)},
{"lagrange",13,9,0,*((unsigned longlong *) at_lagrange)},
{"laguerre",13,9,0,*((unsigned longlong *) at_laguerre)},
{"laplace",13,9,0,*((unsigned longlong *) at_laplace)},
{"laplacian",13,9,0,*((unsigned longlong *) at_laplacian)| 1},
{"latex",13,9,0,*((unsigned longlong *) at_latex)},
{"lcm",13,9,0,*((unsigned longlong *) at_lcm)},
{"lcoeff",13,9,0,*((unsigned longlong *) at_lcoeff)},
{"ldegree",13,9,0,*((unsigned longlong *) at_ldegree)},
{"left",13,9,0,*((unsigned longlong *) at_left)},
{"legend",13,9,0,*((unsigned longlong *) at_legend)| 1},
{"legendre",13,9,0,*((unsigned longlong *) at_legendre)},
{"legendre_symbol",13,9,0,*((unsigned longlong *) at_legendre_symbol)},
{"length",13,9,0,*((unsigned longlong *) at_length)},
{"leve_crayon",13,126,0,*((unsigned longlong *) at_leve_crayon)},
{"lgcd",13,9,0,*((unsigned longlong *) at_lgcd)},
{"lhs",13,9,0,*((unsigned longlong *) at_lhs)},
{"ligne_polygonale",13,9,0,*((unsigned longlong *) at_ligne_polygonale)},
{"ligne_polygonale_pointee",13,9,0,*((unsigned longlong *) at_ligne_polygonale_pointee)},
{"limit",13,9,0,*((unsigned longlong *) at_limit)},
{"limite",13,9,0,*((unsigned longlong *) at_limite)},
{"lin",13,9,0,*((unsigned longlong *) at_lin)},
{"line",13,9,0,*((unsigned longlong *) at_line)},
{"line_inter",13,9,0,*((unsigned longlong *) at_line_inter)},
{"line_paper",13,9,0,*((unsigned longlong *) at_line_paper)},
{"line_segments",13,9,0,*((unsigned longlong *) at_line_segments)},
{"linear_interpolate",13,9,0,*((unsigned longlong *) at_linear_interpolate)},
{"linear_regression",13,9,0,*((unsigned longlong *) at_linear_regression)},
{"linear_regression_plot",13,9,0,*((unsigned longlong *) at_linear_regression_plot)},
{"lineariser",13,9,0,*((unsigned longlong *) at_lineariser)},
{"lineariser_trigo",13,9,0,*((unsigned longlong *) at_lineariser_trigo)},
{"linsolve",13,9,0,*((unsigned longlong *) at_linsolve)| 1},
{"lis",13,77,0,*((unsigned longlong *) at_lis)| 1},
{"lis_phrase",13,77,0,*((unsigned longlong *) at_lis_phrase)| 1},
{"list2mat",13,9,0,*((unsigned longlong *) at_list2mat)},
{"listplot",13,9,0,*((unsigned longlong *) at_listplot)},
{"lll",13,9,0,*((unsigned longlong *) at_lll)},
{"ln",13,9,0,*((unsigned longlong *) at_ln)},
{"lnGamma_minus",13,9,0,*((unsigned longlong *) at_lnGamma_minus)},
{"lname",13,9,0,*((unsigned longlong *) at_lname)},
{"lncollect",13,9,0,*((unsigned longlong *) at_lncollect)},
{"lnexpand",13,9,0,*((unsigned longlong *) at_lnexpand)},
{"locus",13,9,0,*((unsigned longlong *) at_locus)| 1},
{"log10",13,9,0,*((unsigned longlong *) at_log10)},
{"logarithmic_regression",13,9,0,*((unsigned longlong *) at_logarithmic_regression)},
{"logarithmic_regression_plot",13,9,0,*((unsigned longlong *) at_logarithmic_regression_plot)},
{"logb",13,9,0,*((unsigned longlong *) at_logb)},
{"logistic_regression",13,9,0,*((unsigned longlong *) at_logistic_regression)},
{"logistic_regression_plot",13,9,0,*((unsigned longlong *) at_logistic_regression_plot)},
{"lsmod",13,9,0,*((unsigned longlong *) at_lsmod)},
{"lu",13,9,0,*((unsigned longlong *) at_lu)},
{"lvar",13,9,0,*((unsigned longlong *) at_lvar)},
{"mRow",13,9,0,*((unsigned longlong *) at_mRow)},
{"mRowAdd",13,9,0,*((unsigned longlong *) at_mRowAdd)},
{"magenta",13,2,0,*((unsigned longlong *) at_magenta)},
{"makelist",13,9,0,*((unsigned longlong *) at_makelist)},
{"makemat",13,9,0,*((unsigned longlong *) at_makemat)},
{"makemod",13,9,0,*((unsigned longlong *) at_makemod)},
{"makesuite",13,9,0,*((unsigned longlong *) at_makesuite)},
{"makevector",13,9,0,*((unsigned longlong *) at_makevector)},
{"map",13,9,0,*((unsigned longlong *) at_map)},
{"maple2mupad",13,9,0,*((unsigned longlong *) at_maple2mupad)| 1},
{"maple2xcas",13,9,0,*((unsigned longlong *) at_maple2xcas)| 1},
{"maple_ifactors",13,9,0,*((unsigned longlong *) at_maple_ifactors)},
{"maple_mode",13,9,0,*((unsigned longlong *) at_maple_mode)},
{"mat2list",13,9,0,*((unsigned longlong *) at_mat2list)},
{"mathml",13,9,0,*((unsigned longlong *) at_mathml)},
{"matpow",13,9,0,*((unsigned longlong *) at_matpow)},
{"matrix",13,9,0,*((unsigned longlong *) at_matrix)},
{"max",13,9,0,*((unsigned longlong *) at_max)},
{"maxnorm",13,9,0,*((unsigned longlong *) at_maxnorm)},
{"mean",13,9,0,*((unsigned longlong *) at_mean)},
{"median",13,9,0,*((unsigned longlong *) at_median)},
{"median_line",13,9,0,*((unsigned longlong *) at_median_line)},
{"member",13,9,0,*((unsigned longlong *) at_member)| 1},
{"mid",13,9,0,*((unsigned longlong *) at_mid)},
{"midpoint",13,9,0,*((unsigned longlong *) at_midpoint)},
{"min",13,9,0,*((unsigned longlong *) at_min)},
{"mkisom",13,9,0,*((unsigned longlong *) at_mkisom)},
{"mksa",13,9,0,*((unsigned longlong *) at_mksa)},
{"modgcd",13,9,0,*((unsigned longlong *) at_modgcd)},
{"modgcd_cachesize",13,9,0,*((unsigned longlong *) at_modgcd_cachesize)},
{"modp",13,9,0,*((unsigned longlong *) at_modp)},
{"mods",13,9,0,*((unsigned longlong *) at_mods)},
{"montre_tortue",13,126,0,*((unsigned longlong *) at_montre_tortue)},
{"moustache",13,9,0,*((unsigned longlong *) at_moustache)},
{"moyal",13,9,0,*((unsigned longlong *) at_moyal)},
{"moyenne",13,9,0,*((unsigned longlong *) at_moyenne)},
{"mpzclass_allowed",13,9,0,*((unsigned longlong *) at_mpzclass_allowed)},
{"mul",13,9,0,*((unsigned longlong *) at_mul)},
{"mult_c_conjugate",13,9,0,*((unsigned longlong *) at_mult_c_conjugate)| 1},
{"mult_conjugate",13,9,0,*((unsigned longlong *) at_mult_conjugate)},
{"multcrement",13,9,0,*((unsigned longlong *) at_multcrement)| 1},
{"multiplier_conjugue",13,9,0,*((unsigned longlong *) at_multiplier_conjugue)},
{"multiplier_conjugue_complexe",13,9,0,*((unsigned longlong *) at_multiplier_conjugue_complexe)},
{"multiply",13,9,0,*((unsigned longlong *) at_multiply)},
{"mupad2maple",13,9,0,*((unsigned longlong *) at_mupad2maple)| 1},
{"mupad2xcas",13,9,0,*((unsigned longlong *) at_mupad2xcas)| 1},
{"nCr",13,9,0,*((unsigned longlong *) at_nCr)},
{"nDeriv",13,9,0,*((unsigned longlong *) at_nDeriv)},
{"nInt",13,9,0,*((unsigned longlong *) at_nInt)},
{"nPr",13,9,0,*((unsigned longlong *) at_nPr)},
{"nSolve",13,9,0,*((unsigned longlong *) at_nSolve)},
{"ncols",13,9,0,*((unsigned longlong *) at_ncols)},
{"newList",13,9,0,*((unsigned longlong *) at_newList)},
{"newMat",13,9,0,*((unsigned longlong *) at_newMat)},
{"newton",13,9,0,*((unsigned longlong *) at_newton)},
{"nextperm",13,9,0,*((unsigned longlong *) at_nextperm)},
{"nextprime",13,9,0,*((unsigned longlong *) at_nextprime)},
{"nodisp",13,9,0,*((unsigned longlong *) at_nodisp)},
{"non",13,11,0,*((unsigned longlong *) at_non)},
{"non_recursive_normal",13,9,0,*((unsigned longlong *) at_non_recursive_normal)},
{"nop",13,9,0,*((unsigned longlong *) at_nop)},
{"nops",13,9,0,*((unsigned longlong *) at_nops)},
{"norm",13,9,0,*((unsigned longlong *) at_norm)},
{"normal",13,9,0,*((unsigned longlong *) at_normal)},
{"normal_cdf",13,9,0,*((unsigned longlong *) at_normal_cdf)},
{"normal_icdf",13,9,0,*((unsigned longlong *) at_normal_icdf)},
{"normald",13,9,0,*((unsigned longlong *) at_normald)},
{"normald_cdf",13,9,0,*((unsigned longlong *) at_normald_cdf)},
{"normald_icdf",13,9,0,*((unsigned longlong *) at_normald_icdf)},
{"normalize",13,9,0,*((unsigned longlong *) at_normalize)},
{"nrows",13,9,0,*((unsigned longlong *) at_nrows)},
{"nuage_points",13,9,0,*((unsigned longlong *) at_nuage_points)},
{"nullspace",13,9,0,*((unsigned longlong *) at_nullspace)},
{"numer",13,9,0,*((unsigned longlong *) at_numer)},
{"octahedron",13,9,0,*((unsigned longlong *) at_octahedron)},
{"octprint",13,9,0,*((unsigned longlong *) at_octprint)},
{"odd",13,9,0,*((unsigned longlong *) at_odd)},
{"odeplot",13,9,0,*((unsigned longlong *) at_odeplot)},
{"odesolve",13,9,0,*((unsigned longlong *) at_odesolve)},
{"op",13,9,0,*((unsigned longlong *) at_op)},
{"open",13,9,0,*((unsigned longlong *) at_open)},
{"open_polygon",13,9,0,*((unsigned longlong *) at_open_polygon)},
{"or",13,33,0,*((unsigned longlong *) at_or)| 1},
{"ord",13,9,0,*((unsigned longlong *) at_ord)},
{"order_size",13,9,0,*((unsigned longlong *) at_order_size)},
{"ordinate",13,9,0,*((unsigned longlong *) at_ordinate)},
{"orthocenter",13,9,0,*((unsigned longlong *) at_orthocenter)},
{"orthogonal",13,9,0,*((unsigned longlong *) at_orthogonal)},
{"os_version",13,9,0,*((unsigned longlong *) at_os_version)},
{"ou",13,33,0,*((unsigned longlong *) at_ou)| 1},
{"output",13,9,0,*((unsigned longlong *) at_output)| 1},
{"p1oc2",13,9,0,*((unsigned longlong *) at_p1oc2)},
{"p1op2",13,9,0,*((unsigned longlong *) at_p1op2)},
{"pa2b2",13,9,0,*((unsigned longlong *) at_pa2b2)},
{"pade",13,9,0,*((unsigned longlong *) at_pade)},
{"padic_linsolve",13,9,0,*((unsigned longlong *) at_padic_linsolve)},
{"parabola",13,9,0,*((unsigned longlong *) at_parabola)},
{"parabolic_interpolate",13,9,0,*((unsigned longlong *) at_parabolic_interpolate)},
{"parallel",13,9,0,*((unsigned longlong *) at_parallel)},
{"parallelepiped",13,9,0,*((unsigned longlong *) at_parallelepiped)},
{"parallelogram",13,9,0,*((unsigned longlong *) at_parallelogram)| 1},
{"parameq",13,9,0,*((unsigned longlong *) at_parameq)},
{"parameter",13,9,0,*((unsigned longlong *) at_parameter)},
{"paramplot",13,9,0,*((unsigned longlong *) at_paramplot)| 1},
{"pari",13,9,0,*((unsigned longlong *) at_pari)| 1},
{"pari_unlock",13,9,0,*((unsigned longlong *) at_pari_unlock)| 1},
{"part",13,9,0,*((unsigned longlong *) at_part)},
{"partfrac",13,9,0,*((unsigned longlong *) at_partfrac)},
{"pas",13,60,0,*((unsigned longlong *) at_pas)| 1},
{"pas_de_cote",13,126,0,*((unsigned longlong *) at_pas_de_cote)},
{"pcar",13,9,0,*((unsigned longlong *) at_pcar)},
{"pcar_hessenberg",13,9,0,*((unsigned longlong *) at_pcar_hessenberg)},
{"pcoeff",13,9,0,*((unsigned longlong *) at_pcoeff)},
{"perimeter",13,9,0,*((unsigned longlong *) at_perimeter)},
{"perimeterat",13,9,0,*((unsigned longlong *) at_perimeterat)| 1},
{"perimeteratraw",13,9,0,*((unsigned longlong *) at_perimeteratraw)},
{"perm",13,9,0,*((unsigned longlong *) at_perm)},
{"perminv",13,9,0,*((unsigned longlong *) at_perminv)},
{"permu2cycles",13,9,0,*((unsigned longlong *) at_permu2cycles)},
{"permu2mat",13,9,0,*((unsigned longlong *) at_permu2mat)},
{"permuorder",13,9,0,*((unsigned longlong *) at_permuorder)},
{"perpen_bisector",13,9,0,*((unsigned longlong *) at_perpen_bisector)},
{"perpendicular",13,9,0,*((unsigned longlong *) at_perpendicular)},
{"peval",13,9,0,*((unsigned longlong *) at_peval)},
{"piecewise",13,9,0,*((unsigned longlong *) at_piecewise)| 1},
{"pivot",13,9,0,*((unsigned longlong *) at_pivot)},
{"pixoff",13,9,0,*((unsigned longlong *) at_pixoff)},
{"pixon",13,9,0,*((unsigned longlong *) at_pixon)},
{"plane",13,9,0,*((unsigned longlong *) at_plane)},
{"plot",13,9,0,*((unsigned longlong *) at_plot)| 1},
{"plot3d",13,9,0,*((unsigned longlong *) at_plot3d)},
{"plot_style",13,9,0,*((unsigned longlong *) at_plot_style)},
{"plotarea",13,9,0,*((unsigned longlong *) at_plotarea)},
{"plotcontour",13,9,0,*((unsigned longlong *) at_plotcontour)| 1},
{"plotdensity",13,9,0,*((unsigned longlong *) at_plotdensity)| 1},
{"plotfield",13,9,0,*((unsigned longlong *) at_plotfield)},
{"plotfunc",13,9,0,*((unsigned longlong *) at_plotfunc)| 1},
{"plotimplicit",13,9,0,*((unsigned longlong *) at_plotimplicit)},
{"plotinequation",13,9,0,*((unsigned longlong *) at_plotinequation)| 1},
{"plotlist",13,9,0,*((unsigned longlong *) at_plotlist)},
{"plotode",13,9,0,*((unsigned longlong *) at_plotode)},
{"plotparam",13,9,0,*((unsigned longlong *) at_plotparam)| 1},
{"plotpolar",13,9,0,*((unsigned longlong *) at_plotpolar)| 1},
{"plotseq",13,9,0,*((unsigned longlong *) at_plotseq)},
{"pmin",13,9,0,*((unsigned longlong *) at_pmin)},
{"pnt",13,9,0,*((unsigned longlong *) at_pnt)},
{"point",13,9,0,*((unsigned longlong *) at_point)},
{"point2d",13,9,0,*((unsigned longlong *) at_point2d)| 1},
{"point3d",13,9,0,*((unsigned longlong *) at_point3d)| 1},
{"pointer",13,-124,0,*((unsigned longlong *) at_pointer)},
{"poisson",13,9,0,*((unsigned longlong *) at_poisson)},
{"poisson_cdf",13,9,0,*((unsigned longlong *) at_poisson_cdf)},
{"poisson_icdf",13,9,0,*((unsigned longlong *) at_poisson_icdf)},
{"polar",13,9,0,*((unsigned longlong *) at_polar)},
{"polar2rectangular",13,9,0,*((unsigned longlong *) at_polar2rectangular)},
{"polar_coordinates",13,9,0,*((unsigned longlong *) at_polar_coordinates)},
{"polar_point",13,9,0,*((unsigned longlong *) at_polar_point)},
{"polarplot",13,9,0,*((unsigned longlong *) at_polarplot)| 1},
{"pole",13,9,0,*((unsigned longlong *) at_pole)},
{"poly2symb",13,9,0,*((unsigned longlong *) at_poly2symb)},
{"polyEval",13,9,0,*((unsigned longlong *) at_polyEval)},
{"polygon",13,9,0,*((unsigned longlong *) at_polygon)},
{"polygone_rempli",13,126,0,*((unsigned longlong *) at_polygone_rempli)},
{"polygonplot",13,9,0,*((unsigned longlong *) at_polygonplot)},
{"polygonscatterplot",13,9,0,*((unsigned longlong *) at_polygonscatterplot)},
{"polyhedron",13,9,0,*((unsigned longlong *) at_polyhedron)},
{"polynomial_regression",13,9,0,*((unsigned longlong *) at_polynomial_regression)},
{"polynomial_regression_plot",13,9,0,*((unsigned longlong *) at_polynomial_regression_plot)},
{"position",13,126,0,*((unsigned longlong *) at_position)},
{"poslbdLMQ",13,9,0,*((unsigned longlong *) at_poslbdLMQ)},
{"posubLMQ",13,9,0,*((unsigned longlong *) at_posubLMQ)},
{"potential",13,9,0,*((unsigned longlong *) at_potential)| 1},
{"pour",13,56,0,*((unsigned longlong *) at_pour)| 1},
{"pow2exp",13,9,0,*((unsigned longlong *) at_pow2exp)},
{"power_regression",13,9,0,*((unsigned longlong *) at_power_regression)},
{"power_regression_plot",13,9,0,*((unsigned longlong *) at_power_regression_plot)},
{"powermod",13,9,0,*((unsigned longlong *) at_powermod)},
{"powerpc",13,9,0,*((unsigned longlong *) at_powerpc)},
{"powexpand",13,9,0,*((unsigned longlong *) at_powexpand)},
{"powmod",13,9,0,*((unsigned longlong *) at_powmod)},
{"prepend",13,9,0,*((unsigned longlong *) at_prepend)},
{"preval",13,9,0,*((unsigned longlong *) at_preval)},
{"prevperm",13,9,0,*((unsigned longlong *) at_prevperm)},
{"prevprime",13,9,0,*((unsigned longlong *) at_prevprime)},
{"primpart",13,9,0,*((unsigned longlong *) at_primpart)},
{"print",13,9,0,*((unsigned longlong *) at_print)| 1},
{"printpow",13,9,0,*((unsigned longlong *) at_printpow)},
{"prism",13,9,0,*((unsigned longlong *) at_prism)},
{"product",13,9,0,*((unsigned longlong *) at_product)| 1},
{"prog_eval_level",13,9,0,*((unsigned longlong *) at_prog_eval_level)},
{"projection",13,9,0,*((unsigned longlong *) at_projection)},
{"proot",13,9,0,*((unsigned longlong *) at_proot)},
{"propFrac",13,9,0,*((unsigned longlong *) at_propFrac)},
{"propfrac",13,9,0,*((unsigned longlong *) at_propfrac)},
{"psrgcd",13,9,0,*((unsigned longlong *) at_psrgcd)},
{"ptayl",13,9,0,*((unsigned longlong *) at_ptayl)},
{"pwd",13,9,0,*((unsigned longlong *) at_pwd)},
{"pyramid",13,9,0,*((unsigned longlong *) at_pyramid)},
{"q2a",13,9,0,*((unsigned longlong *) at_q2a)},
{"qr",13,9,0,*((unsigned longlong *) at_qr)},
{"quadric",13,9,0,*((unsigned longlong *) at_quadric)},
{"quadrilateral",13,9,0,*((unsigned longlong *) at_quadrilateral)},
{"quantile",13,9,0,*((unsigned longlong *) at_quantile)},
{"quartile1",13,9,0,*((unsigned longlong *) at_quartile1)},
{"quartile3",13,9,0,*((unsigned longlong *) at_quartile3)},
{"quartiles",13,9,0,*((unsigned longlong *) at_quartiles)},
{"quaternion",13,9,0,*((unsigned longlong *) at_quaternion)},
{"quest",13,9,0,*((unsigned longlong *) at_quest)},
{"quo",13,9,0,*((unsigned longlong *) at_quo)},
{"quorem",13,9,0,*((unsigned longlong *) at_quorem)},
{"quote",13,9,0,*((unsigned longlong *) at_quote)| 1},
{"r2e",13,9,0,*((unsigned longlong *) at_r2e)},
{"radical_axis",13,9,0,*((unsigned longlong *) at_radical_axis)},
{"radius",13,9,0,*((unsigned longlong *) at_radius)},
{"ramene",13,126,0,*((unsigned longlong *) at_ramene)},
{"rand",13,9,0,*((unsigned longlong *) at_rand)},
{"randMat",13,9,0,*((unsigned longlong *) at_randMat)},
{"randNorm",13,9,0,*((unsigned longlong *) at_randNorm)},
{"randPoly",13,9,0,*((unsigned longlong *) at_randPoly)},
{"randexp",13,9,0,*((unsigned longlong *) at_randexp)},
{"randmatrix",13,9,0,*((unsigned longlong *) at_randmatrix)},
{"randperm",13,9,0,*((unsigned longlong *) at_randperm)},
{"randpoly",13,9,0,*((unsigned longlong *) at_randpoly)},
{"randvector",13,9,0,*((unsigned longlong *) at_randvector)},
{"rank",13,9,0,*((unsigned longlong *) at_rank)},
{"ranm",13,9,0,*((unsigned longlong *) at_ranm)},
{"rassembler_trigo",13,9,0,*((unsigned longlong *) at_rassembler_trigo)},
{"rat_jordan",13,9,0,*((unsigned longlong *) at_rat_jordan)},
{"rat_jordan_block",13,9,0,*((unsigned longlong *) at_rat_jordan_block)},
{"rationalroot",13,9,0,*((unsigned longlong *) at_rationalroot)},
{"ratnormal",13,9,0,*((unsigned longlong *) at_ratnormal)},
{"rdiv",13,9,0,*((unsigned longlong *) at_rdiv)},
{"re",13,9,0,*((unsigned longlong *) at_re)},
{"read",13,77,0,*((unsigned longlong *) at_read)},
{"readrgb",13,9,0,*((unsigned longlong *) at_readrgb)},
{"readwav",13,9,0,*((unsigned longlong *) at_readwav)},
{"real",13,9,0,*((unsigned longlong *) at_real)},
{"realroot",13,9,0,*((unsigned longlong *) at_realroot)},
{"reciprocation",13,9,0,*((unsigned longlong *) at_reciprocation)},
{"rectangle",13,9,0,*((unsigned longlong *) at_rectangle)| 1},
{"rectangle_plein",13,126,0,*((unsigned longlong *) at_rectangle_plein)},
{"rectangular2polar",13,9,0,*((unsigned longlong *) at_rectangular2polar)},
{"rectangular_coordinates",13,9,0,*((unsigned longlong *) at_rectangular_coordinates)},
{"recule",13,126,0,*((unsigned longlong *) at_recule)},
{"red",13,2,0,*((unsigned longlong *) at_red)},
{"reduced_conic",13,9,0,*((unsigned longlong *) at_reduced_conic)},
{"reduced_quadric",13,9,0,*((unsigned longlong *) at_reduced_quadric)},
{"ref",13,9,0,*((unsigned longlong *) at_ref)},
{"reflection",13,9,0,*((unsigned longlong *) at_reflection)},
{"regrouper",13,9,0,*((unsigned longlong *) at_regrouper)},
{"rem",13,9,0,*((unsigned longlong *) at_rem)},
{"remain",13,9,0,*((unsigned longlong *) at_remain)},
{"remove",13,9,0,*((unsigned longlong *) at_remove)},
{"remove_language",13,9,0,*((unsigned longlong *) at_remove_language)},
{"reorder",13,9,0,*((unsigned longlong *) at_reorder)},
{"repete",13,77,0,*((unsigned longlong *) at_repete)| 1},
{"reset_solve_counter",13,9,0,*((unsigned longlong *) at_reset_solve_counter)},
{"residue",13,9,0,*((unsigned longlong *) at_residue)},
{"resoudre",13,9,0,*((unsigned longlong *) at_resoudre)| 1},
{"resoudre_dans_C",13,9,0,*((unsigned longlong *) at_resoudre_dans_C)| 1},
{"resoudre_systeme_lineaire",13,9,0,*((unsigned longlong *) at_resoudre_systeme_lineaire)| 1},
{"restart",13,77,0,*((unsigned longlong *) at_restart)},
{"restart_modes",13,77,0,*((unsigned longlong *) at_restart_modes)},
{"restart_vars",13,77,0,*((unsigned longlong *) at_restart_vars)},
{"resultant",13,9,0,*((unsigned longlong *) at_resultant)},
{"resultat",13,77,0,*((unsigned longlong *) at_resultat)| 1},
{"reverse_rsolve",13,9,0,*((unsigned longlong *) at_reverse_rsolve)},
{"revert",13,9,0,*((unsigned longlong *) at_revert)},
{"revlist",13,9,0,*((unsigned longlong *) at_revlist)},
{"rhombus",13,9,0,*((unsigned longlong *) at_rhombus)| 1},
{"rhs",13,9,0,*((unsigned longlong *) at_rhs)},
{"right",13,9,0,*((unsigned longlong *) at_right)},
{"right_triangle",13,9,0,*((unsigned longlong *) at_right_triangle)| 1},
{"risch",13,9,0,*((unsigned longlong *) at_risch)},
{"rm_a_z",13,9,0,*((unsigned longlong *) at_rm_a_z)},
{"rm_all_vars",13,9,0,*((unsigned longlong *) at_rm_all_vars)},
{"rmbreakpoint",13,9,0,*((unsigned longlong *) at_rmbreakpoint)| 1},
{"rmmod",13,9,0,*((unsigned longlong *) at_rmmod)},
{"rmwatch",13,9,0,*((unsigned longlong *) at_rmwatch)| 1},
{"romberg",13,9,0,*((unsigned longlong *) at_romberg)},
{"rond",13,126,0,*((unsigned longlong *) at_rond)},
{"rootof",13,9,0,*((unsigned longlong *) at_rootof)},
{"roots",13,9,0,*((unsigned longlong *) at_roots)},
{"rotate",13,9,0,*((unsigned longlong *) at_rotate)},
{"rotation",13,9,0,*((unsigned longlong *) at_rotation)},
{"round",13,9,0,*((unsigned longlong *) at_round)},
{"row",13,9,0,*((unsigned longlong *) at_row)},
{"rowAdd",13,9,0,*((unsigned longlong *) at_rowAdd)},
{"rowDim",13,9,0,*((unsigned longlong *) at_rowDim)},
{"rowNorm",13,9,0,*((unsigned longlong *) at_rowNorm)},
{"rowSwap",13,9,0,*((unsigned longlong *) at_rowSwap)},
{"rowdim",13,9,0,*((unsigned longlong *) at_rowdim)},
{"rownorm",13,9,0,*((unsigned longlong *) at_rownorm)},
{"rowspace",13,9,0,*((unsigned longlong *) at_rowspace)},
{"rpn",13,9,0,*((unsigned longlong *) at_rpn)},
{"rref",13,9,0,*((unsigned longlong *) at_rref)},
{"rsolve",13,9,0,*((unsigned longlong *) at_rsolve)| 1},
{"saute",13,126,0,*((unsigned longlong *) at_saute)},
{"sauve",13,126,0,*((unsigned longlong *) at_sauve)| 1},
{"save_history",13,9,0,*((unsigned longlong *) at_save_history)},
{"scalarProduct",13,9,0,*((unsigned longlong *) at_scalarProduct)},
{"scalar_product",13,9,0,*((unsigned longlong *) at_scalar_product)},
{"scatterplot",13,9,0,*((unsigned longlong *) at_scatterplot)},
{"sec",13,9,0,*((unsigned longlong *) at_sec)},
{"segment",13,9,0,*((unsigned longlong *) at_segment)},
{"select",13,9,0,*((unsigned longlong *) at_select)},
{"semi_augment",13,9,0,*((unsigned longlong *) at_semi_augment)},
{"seq",13,9,0,*((unsigned longlong *) at_seq)| 1},
{"seqplot",13,9,0,*((unsigned longlong *) at_seqplot)},
{"seqsolve",13,9,0,*((unsigned longlong *) at_seqsolve)| 1},
{"series",13,9,0,*((unsigned longlong *) at_series)},
{"shift",13,9,0,*((unsigned longlong *) at_shift)},
{"shift_phase",13,9,0,*((unsigned longlong *) at_shift_phase)},
{"show_language",13,9,0,*((unsigned longlong *) at_show_language)},
{"si",13,46,0,*((unsigned longlong *) at_si)| 1},
{"sialorssinon",13,51,0,*((unsigned longlong *) at_sialorssinon)| 1},
{"sign",13,9,0,*((unsigned longlong *) at_sign)},
{"signature",13,9,0,*((unsigned longlong *) at_signature)},
{"signe",13,126,0,*((unsigned longlong *) at_signe)},
{"similarity",13,9,0,*((unsigned longlong *) at_similarity)},
{"simp2",13,9,0,*((unsigned longlong *) at_simp2)},
{"simplex_reduce",13,9,0,*((unsigned longlong *) at_simplex_reduce)},
{"simplifier",13,9,0,*((unsigned longlong *) at_simplifier)},
{"simplify",13,9,0,*((unsigned longlong *) at_simplify)},
{"simult",13,9,0,*((unsigned longlong *) at_simult)},
{"sin",13,9,0,*((unsigned longlong *) at_sin)},
{"sin2costan",13,9,0,*((unsigned longlong *) at_sin2costan)},
{"sincos",13,9,0,*((unsigned longlong *) at_sincos)},
{"single_inter",13,9,0,*((unsigned longlong *) at_single_inter)},
{"singular",13,9,0,*((unsigned longlong *) at_singular)},
{"sinh",13,9,0,*((unsigned longlong *) at_sinh)},
{"sinon",13,50,0,*((unsigned longlong *) at_sinon)| 1},
{"size",13,9,0,*((unsigned longlong *) at_size)},
{"sizes",13,9,0,*((unsigned longlong *) at_sizes)},
{"slope",13,9,0,*((unsigned longlong *) at_slope)},
{"slopeat",13,9,0,*((unsigned longlong *) at_slopeat)| 1},
{"slopeatraw",13,9,0,*((unsigned longlong *) at_slopeatraw)},
{"smod",13,9,0,*((unsigned longlong *) at_smod)},
{"snedecor",13,9,0,*((unsigned longlong *) at_snedecor)},
{"snedecor_cdf",13,9,0,*((unsigned longlong *) at_snedecor_cdf)},
{"snedecor_icdf",13,9,0,*((unsigned longlong *) at_snedecor_icdf)},
{"solve",13,9,0,*((unsigned longlong *) at_solve)| 1},
{"solve_zero_extremum",13,9,0,*((unsigned longlong *) at_solve_zero_extremum)| 1},
{"somme",13,9,0,*((unsigned longlong *) at_somme)| 1},
{"sommet",13,9,0,*((unsigned longlong *) at_sommet)},
{"sort",13,9,0,*((unsigned longlong *) at_sort)},
{"sphere",13,9,0,*((unsigned longlong *) at_sphere)},
{"spline",13,9,0,*((unsigned longlong *) at_spline)},
{"split",13,9,0,*((unsigned longlong *) at_split)},
{"spread2mathml",13,9,0,*((unsigned longlong *) at_spread2mathml)},
{"spreadsheet",13,9,0,*((unsigned longlong *) at_spreadsheet)},
{"sq",13,9,0,*((unsigned longlong *) at_sq)},
{"sqrfree",13,9,0,*((unsigned longlong *) at_sqrfree)},
{"sqrt",13,9,0,*((unsigned longlong *) at_sqrt)},
{"square",13,9,0,*((unsigned longlong *) at_square)| 1},
{"srand",13,77,0,*((unsigned longlong *) at_srand)},
{"sst",13,9,0,*((unsigned longlong *) at_sst)| 1},
{"sst_in",13,9,0,*((unsigned longlong *) at_sst_in)| 1},
{"stdDev",13,9,0,*((unsigned longlong *) at_stdDev)},
{"stddev",13,9,0,*((unsigned longlong *) at_stddev)},
{"stddevp",13,9,0,*((unsigned longlong *) at_stddevp)},
{"sto",13,9,0,*((unsigned longlong *) at_sto)},
{"string",13,9,0,*((unsigned longlong *) at_string)},
{"student",13,9,0,*((unsigned longlong *) at_student)},
{"student_cdf",13,9,0,*((unsigned longlong *) at_student_cdf)},
{"student_icdf",13,9,0,*((unsigned longlong *) at_student_icdf)},
{"sturm",13,9,0,*((unsigned longlong *) at_sturm)},
{"sturmab",13,9,0,*((unsigned longlong *) at_sturmab)},
{"sturmseq",13,9,0,*((unsigned longlong *) at_sturmseq)},
{"subMat",13,9,0,*((unsigned longlong *) at_subMat)},
{"submatrix",13,9,0,*((unsigned longlong *) at_submatrix)},
{"subst",13,9,0,*((unsigned longlong *) at_subst)},
{"substituer",13,9,0,*((unsigned longlong *) at_substituer)},
{"sum",13,9,0,*((unsigned longlong *) at_sum)| 1},
{"sum_riemann",13,9,0,*((unsigned longlong *) at_sum_riemann)},
{"suppress",13,9,0,*((unsigned longlong *) at_suppress)},
{"surd",13,9,0,*((unsigned longlong *) at_surd)},
{"svd",13,9,0,*((unsigned longlong *) at_svd)},
{"switch_axes",13,9,0,*((unsigned longlong *) at_switch_axes)},
{"sylvester",13,9,0,*((unsigned longlong *) at_sylvester)},
{"symb2poly",13,9,0,*((unsigned longlong *) at_symb2poly)},
{"syst2mat",13,9,0,*((unsigned longlong *) at_syst2mat)},
{"tCollect",13,9,0,*((unsigned longlong *) at_tCollect)},
{"tExpand",13,9,0,*((unsigned longlong *) at_tExpand)},
{"table",13,9,0,*((unsigned longlong *) at_table)},
{"tablefunc",13,9,0,*((unsigned longlong *) at_tablefunc)},
{"tableseq",13,9,0,*((unsigned longlong *) at_tableseq)| 1},
{"tail",13,9,0,*((unsigned longlong *) at_tail)},
{"tan",13,9,0,*((unsigned longlong *) at_tan)},
{"tan2cossin2",13,9,0,*((unsigned longlong *) at_tan2cossin2)},
{"tan2sincos",13,9,0,*((unsigned longlong *) at_tan2sincos)},
{"tan2sincos2",13,9,0,*((unsigned longlong *) at_tan2sincos2)},
{"tangent",13,9,0,*((unsigned longlong *) at_tangent)},
{"tangente",13,9,0,*((unsigned longlong *) at_tangente)},
{"tanh",13,9,0,*((unsigned longlong *) at_tanh)},
{"tantque",13,62,0,*((unsigned longlong *) at_tantque)| 1},
{"taux_accroissement",13,9,0,*((unsigned longlong *) at_taux_accroissement)},
{"taylor",13,9,0,*((unsigned longlong *) at_taylor)},
{"tchebyshev1",13,9,0,*((unsigned longlong *) at_tchebyshev1)},
{"tchebyshev2",13,9,0,*((unsigned longlong *) at_tchebyshev2)},
{"tcoeff",13,9,0,*((unsigned longlong *) at_tcoeff)},
{"tcollect",13,9,0,*((unsigned longlong *) at_tcollect)},
{"testfunc",13,9,0,*((unsigned longlong *) at_testfunc)},
{"tests",13,-124,0,*((unsigned longlong *) at_tests)},
{"tetrahedron",13,9,0,*((unsigned longlong *) at_tetrahedron)},
{"texpand",13,9,0,*((unsigned longlong *) at_texpand)},
{"textinput",13,9,0,*((unsigned longlong *) at_textinput)| 1},
{"threads_allowed",13,9,0,*((unsigned longlong *) at_threads_allowed)},
{"throw",13,77,0,*((unsigned longlong *) at_throw)},
{"time",13,9,0,*((unsigned longlong *) at_time)| 1},
{"tlin",13,9,0,*((unsigned longlong *) at_tlin)},
{"tourne_droite",13,126,0,*((unsigned longlong *) at_tourne_droite)},
{"tourne_gauche",13,126,0,*((unsigned longlong *) at_tourne_gauche)},
{"trace",13,9,0,*((unsigned longlong *) at_trace)},
{"tran",13,9,0,*((unsigned longlong *) at_tran)},
{"translation",13,9,0,*((unsigned longlong *) at_translation)},
{"transpose",13,9,0,*((unsigned longlong *) at_transpose)},
{"triangle",13,9,0,*((unsigned longlong *) at_triangle)},
{"triangle_paper",13,9,0,*((unsigned longlong *) at_triangle_paper)},
{"triangle_plein",13,126,0,*((unsigned longlong *) at_triangle_plein)},
{"trig2exp",13,9,0,*((unsigned longlong *) at_trig2exp)},
{"trigcos",13,9,0,*((unsigned longlong *) at_trigcos)},
{"trigexpand",13,9,0,*((unsigned longlong *) at_trigexpand)},
{"trigsin",13,9,0,*((unsigned longlong *) at_trigsin)},
{"trigtan",13,9,0,*((unsigned longlong *) at_trigtan)},
{"trn",13,9,0,*((unsigned longlong *) at_trn)},
{"trunc",13,9,0,*((unsigned longlong *) at_trunc)},
{"truncate",13,9,0,*((unsigned longlong *) at_truncate)},
{"tsimplify",13,9,0,*((unsigned longlong *) at_tsimplify)},
{"type",13,9,0,*((unsigned longlong *) at_type)},
{"ufactor",13,9,0,*((unsigned longlong *) at_ufactor)},
{"unapply",13,9,0,*((unsigned longlong *) at_unapply)| 1},
{"unarchive",13,9,0,*((unsigned longlong *) at_unarchive)},
{"unarchive_ti",13,9,0,*((unsigned longlong *) at_unarchive_ti)},
{"unitV",13,9,0,*((unsigned longlong *) at_unitV)},
{"unquote",13,9,0,*((unsigned longlong *) at_unquote)},
{"usimplify",13,9,0,*((unsigned longlong *) at_usimplify)},
{"valuation",13,9,0,*((unsigned longlong *) at_valuation)},
{"vandermonde",13,9,0,*((unsigned longlong *) at_vandermonde)},
{"variance",13,9,0,*((unsigned longlong *) at_variance)},
{"vector",13,9,0,*((unsigned longlong *) at_vector)},
{"vers",13,126,0,*((unsigned longlong *) at_vers)},
{"version",13,9,0,*((unsigned longlong *) at_version)},
{"vertices",13,9,0,*((unsigned longlong *) at_vertices)},
{"vertices_abc",13,9,0,*((unsigned longlong *) at_vertices_abc)},
{"vertices_abca",13,9,0,*((unsigned longlong *) at_vertices_abca)},
{"vpotential",13,9,0,*((unsigned longlong *) at_vpotential)| 1},
{"watch",13,9,0,*((unsigned longlong *) at_watch)| 1},
{"whattype",13,9,0,*((unsigned longlong *) at_whattype)},
{"when",13,9,0,*((unsigned longlong *) at_when)| 1},
{"white",13,2,0,*((unsigned longlong *) at_white)},
{"widget_size",13,9,0,*((unsigned longlong *) at_widget_size)},
{"with_sqrt",13,9,0,*((unsigned longlong *) at_with_sqrt)},
{"write",13,9,0,*((unsigned longlong *) at_write)| 1},
{"writergb",13,9,0,*((unsigned longlong *) at_writergb)},
{"writewav",13,9,0,*((unsigned longlong *) at_writewav)},
{"xcas_mode",13,9,0,*((unsigned longlong *) at_xcas_mode)},
{"xyztrange",13,9,0,*((unsigned longlong *) at_xyztrange)},
{"yellow",13,2,0,*((unsigned longlong *) at_yellow)},
{"zeros",13,9,0,*((unsigned longlong *) at_zeros)| 1},
{"zip",13,9,0,*((unsigned longlong *) at_zip)},
{"ztrans",13,9,0,*((unsigned longlong *) at_ztrans)},
{"ΔLIST",13,-124,0,*((unsigned longlong *) at_DELTALIST)},
{"ΠLIST",13,-124,0,*((unsigned longlong *) at_PILIST)},
{"Σ",13,-124,0,*((unsigned longlong *) at_HPSUM)| 1},
{"ΣLIST",13,-124,0,*((unsigned longlong *) at_SIGMALIST)},
{"∂",13,-124,0,*((unsigned longlong *) at_HPDIFF)| 1},
{"∫",13,-124,0,*((unsigned longlong *) at_HPINT)| 1}
