#!/bin/sh
# Goes through the building, packing and installer creating procedure.
# Has the same purpose like buildggbXX.

# 1. Start and loading configuration
test -r autobuild.conf || {
 echo "$0: Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 # exit 1
 }
test -r autobuild.conf && . ./autobuild.conf

# 2. Setting defaults
if [ "$SVNDIR" = "" ]; then
 ORIGDIR=`dirname $0`
 WORKDIR=`cd $ORIGDIR/../..; pwd`
else
 WORKDIR=`cd $SVNDIR/geogebra/desktop; pwd`
 fi

CLEAN=0
GRAMMAR=1
VERBOSE=0
CLASSES=1
PURGE=1
DELSRC=1
LOGFILE=/tmp/build-pack-installer.log
JOGL=1
STOPONECJERR=1
TESTURL="http://dev.geogebra.org/~build/www-autobuild"
THIRDPARTY=1
INSTALLERS=1
if [ "$WWWDIR" = "" ]; then
 WWWDIR=/home/build/www-autobuild
 fi

# 3. Reading command line arguments
while [ $# -gt 0 ]; do
 case $1 in
  -h | -help | --help)
   echo "This script goes through the building, packing and installer creation procedure."
   echo
   echo "Usage: $0 [options]"
   echo " Where options can be (defaults in parentheses):"
   echo "  -h, -help, --help         This help"
   echo "  -J [version]              Set JOGL version ($JOGL)"
   echo "  -j [dir]                  Set JAVA_HOME to dir"
   echo "  -np, --no-purge           Do not purge certain directories before SVN update"
   echo "  -nd, --no-delete-src      Do not delete sources before SVN update"
   echo "  -ng, --no-grammar         Do not compile grammar with javacc"
   echo "  -nc, --no-classes         Do not (re)compile classes"
   echo "  -ne, --no-ecj-err         Do not stop on an ecj error"
   echo "  -nt, --no-third-party     Do not download any third-party components"
   echo "  -ni, --no-installers      Do not create installers"
   echo "  -tu [url]                 Test URL ($TESTURL), points to WWWDIR ($WWWDIR)"
   echo "  -r [revision]             Use revision instead of latest"
   echo "  -l [logfile]              Use logfile instead of /tmp/build-pack-installer.log"
   echo "  -v, --verbose             Be verbose whenever possible"
   exit 0
   ;;

  -J)
   shift
   JOGL="$1"
   ;;

  -j)
   shift
   JAVA_HOME="$1"
   ;;

  -ng | --no-grammar)
   GRAMMAR=0
   ;;
   
  -nd | --no-delete-src)
   DELSRC=0
   ;;
   
  -np | --no-purge)
   PURGE=0
   ;;
   
  -nc | --no-classes)
   CLASSES=0
   ;;

  -ne | --no-ecj-err)
   STOPONECJERR=0
   ;;

  -nt | --no-third-party)
   THIRDPARTY=0
   ;;

  -ni | --no-installers)
   INSTALLERS=0
   ;;

  -r)
   shift
   REVISION="$1"
   REVISION_PARAM=" -r $1 "
   ;;
   
  -l)
   shift
   LOGFILE="$1"
   ;;
   
  -tu)
   shift
   TESTURL="$1"
   ;;
   
  -v | --verbose)
   VERBOSE=1
   ;;

  *)
   echo "Unknown parameter: $1. Use \"$0 -h\" for help."
   exit 1
   ;;

  esac
 shift
 done

log() {
 NOW=`date`
 echo "$NOW $*" >> $LOGFILE
 echo "$NOW $*"
}

appendlog() {
 LINES=`wc -l $1 | awk '{print $1}'`
 log "Appending logfile with $1 ($LINES lines)"
 echo "-------- 8< $1 TOP --------" >> $LOGFILE
 cat $1 >> $LOGFILE
 echo "-------- 8< $1 BOTTOM --------" >> $LOGFILE
}

runstep() {
 EXITCODE=$1
 shift
 STEPLOG=$1
 shift
 STEPLOGMESS=$1
 shift
 PROBLEM=0
 log "$STEPLOGMESS"
 $* >$STEPLOG 2>&1 || PROBLEM=$?
 appendlog $STEPLOG
 if [ $PROBLEM != 0 ]; then
  log "Exited with exit code $PROBLEM, see $STEPLOG for more details"
  echo "-------- 8< tail $STEPLOG TOP --------"
  tail $STEPLOG
  echo "-------- 8< tail $STEPLOG BOTTOM --------"
  exit $EXITCODE
  fi
}


# 4. Some more settings
PROJECT=geogebra3D
MYDIR=test50

if [ "$WWWDIR" = "" ]; then
 echo "WWWDIR is not set, exiting for safety reasons"
 exit 2
 fi

export JAVA_HOME
export JDK_HOME=$JAVA_HOME
export JAVACMD=$JAVA_HOME/bin/java
export ANT_OPTS="-Xmx1024m"

log "START, verbose log is written to $LOGFILE"

cd $WORKDIR
umask 0002 # trying to ensure g+w rights for all created files automatically

# 5/1. Updating source files
if [ $PURGE = 1 ]; then
 log "Purge: removing some problematic directories before SVN update"
 rm -fR org # not sure why SVN cannot handle this properly (org/mathpiper), http://stackoverflow.com/questions/1608836/folders-skipped-when-updating-svn
 fi

if [ $DELSRC = 1 ]; then
 runstep 51 .delete-sources "Deleting sources" ant -f pack.xml delete-sources # FIXME: delete-sources must work for common as well
 fi

runstep 51 .svn-update "SVN update" $SVN_COMMAND $REVISION_PARAM update --accept theirs-full --force .. org
$SVN_COMMAND info | grep Revision | awk '{print $2}' > scripts/autobuild/.revision

# 5/2. Downloading newest 3rd party libraries and installer tools
if [ "$THIRDPARTY" = 1 ]; then
runstep 52 .kickstart "Downloading build/pack tools" ant -f kickstart.xml geogebra5-packager-commandline
if [ "$INSTALLERS" = 1 ]; then
 cd installer
 runstep 52 .installer "Downloading installer tools" ant
 fi

# 5/3. Downloading/updating JOGL
cd ../jogl$JOGL
runstep 53 .svn-update "SVN update" $SVN_COMMAND $REVISION_PARAM update --accept theirs-full
runstep 53 .kickstart "Downloading/updating JOGL$JOGL" ant -f kickstart.xml
runstep 53 .get-all "Downloading all JOGL$JOGL related packages" ./get-all

# 5/4. Downloading OpenNI and jd2xx
# This might be moved to kickstart.xml...
cd $WORKDIR/lib
DL=http://dev.geogebra.org/download/lib
runstep 54 .openni "Downloading OpenNI" \
 wget -N $DL/kinect-OpenNI/openni.jar $DL/kinect-OpenNI/openni64.jar $DL/kinect-OpenNI/opennimac.jar
runstep 54 .jd2xx "Downloading JD2XX" \
 wget -N $DL/ftdi/jd2xx.jar $DL/ftdi/jd2xx64.jar
fi

# 6. Invoking make-vanilla-jars
cd $WORKDIR/scripts/autobuild
runstep 6 .build "Building" ./make-vanilla-jars -c -J $JOGL
cd $WORKDIR
ECJRESULT=`tail -1 .ecjlog`
log "Eclipse Compiler for Java (ecj) found $ECJRESULT"
appendlog .ecjlog
if [ $STOPONECJERR = 1 ]; then
 echo "$ECJRESULT" | grep --silent error && exit 6
 fi

# 7/1. Doing the rest (packing)
runstep 71 .pack "Packing" ant -f pack.xml -Djogl=$JOGL $PROJECT-aftervanilla

# 7/2. Copying geogebra.map to unpacked
cp $WORKDIR/geogebra.map $WORKDIR/build/unpacked/geogebra-map.txt

# 7/3. Testing packed jars
cd $WORKDIR/scripts/autobuild
runstep 72 .jartest "Testing packed JARs" ./test-packed-jars 
cd $WORKDIR

# 8. Creating Windows and Mac OS X installer
if [ "$INSTALLERS" = 1 ]; then
 runstep 8 .installer "Creating installers" ant -f installer.xml
 fi

# 9/1. Copying and text replacing
log "Recreating $WWWDIR/$MYDIR directory"
MYVER=`cat build/unpacked/version.txt`
cd $WORKDIR/build
test -d $WWWDIR/$MYDIR && rm -fR $WWWDIR/$MYDIR
mkdir -p $WWWDIR/$MYDIR || exit 4
chmod g+rwx $WWWDIR/$MYDIR || exit 4

# 10/1. Copying dynamically generated files (autobuild)
log "Generating dynamic files"
cp -R * $WWWDIR/$MYDIR || exit 4

# 10/2. Copying static files
log "Copying static files"
cp -R $WORKDIR/webstart/5.0/* $WWWDIR/$MYDIR || exit 4
cp $WORKDIR/geogebra/gui/images/geogebra64.png $WWWDIR/$MYDIR || exit 4
mkdir -p $WWWDIR/$MYDIR/usb
cp $WORKDIR/lib/vernier_ccsd* $WWWDIR/$MYDIR/usb || exit 4

# 10/3. Rewriting *.html and *.jnlp to static URLs:
# http://www.geogebra.org/webstart/4.2/unsigned -> http://www.geogebra.org/webstart/$MYDIR/unsigned/unpacked
# http://www.geogebra.org/webstart/4.2/usb-gomotion.ggb -> http://www.geogebra.org/webstart/$MYDIR/usb-gomotion.ggb
# http://www.geogebra.org/webstart/4.2/debug -> http://www.geogebra.org/webstart/$MYDIR/debug
# http://www.geogebra.org/webstart/4.2/jnlp/ -> http://www.geogebra.org/webstart/$MYDIR/unpacked/
# </title> -> ($MYVER) </title>

# The 1st and 4th change is needed to prevent testing the packed version.

# In addition, removing those lines which have the "association mime-type" text.

log "Rewriting HTML and JNLP files"
cd $WWWDIR/$MYDIR
TESTURLSED=`echo $TESTURL | sed s/"\/"/"\\\\\\\\\/"/g`
for i in `ls -1 *.html *.jnlp 2>/dev/null`; do
    cat $i | \
     sed s/"http:\/\/www.geogebra.org\/webstart\/5.0\/unsigned"/"$TESTURLSED\/$MYDIR\/unsigned\/unpacked"/g | \
     sed s/"http:\/\/www.geogebra.org\/webstart\/5.0\/usb-gomotion"/"$TESTURLSED\/$MYDIR\/usb-gomotion.ggb"/g | \
     sed s/"http:\/\/www.geogebra.org\/webstart\/5.0\/debug"/"$TESTURLSED\/$MYDIR\/debug"/g | \
     sed s/"http:\/\/www.geogebra.org\/webstart\/5.0\/jnlp\/"/"$TESTURLSED\/$MYDIR\/unpacked\/"/g | \
     sed s/"http:\/\/www.geogebra.org\/webstart\/5.0\/"/"$TESTURLSED\/$MYDIR\/"/g | \
     sed s/"<\/title>"/" ($MYVER)<\/title>"/g | \
     grep -v "association mime-type" | \
     grep -v packEnabled \
     > $i.work
    mv $i.work $i || exit 4
    done

# 10/4. Copying unsigned geogebra.jar and geogebra_main.jar to $WWWDIR/$MYDIR/minimal:
log "Copying files to minimal/"
mkdir -p $WWWDIR/$MYDIR/minimal
for i in geogebra geogebra_main; do
 cp $WORKDIR/build/unsigned/unpacked/$i.jar $WWWDIR/$MYDIR/minimal
 done

# 10/5. Removing .svn subdirectories from $WWWDIR
find $WWWDIR -name .svn | xargs rm -fR

# 10/6. Copying JNLP's to debug as well:
for i in jogl1 jogl2 no3d; do
 cat $WWWDIR/$MYDIR/geogebra-50-$i.jnlp | sed s/unpacked/debug/g |\
  sed s/"\" href=\"geogebra-50"/"debug\/\" href=\"geogebra-50"/ \
  > $WWWDIR/$MYDIR/debug/geogebra-50-$i.jnlp
 done

# Disabling since the build server should offer http access:
# 11. rsync-www on demand
# if [ "$WWW_REMOTEDIR" != "" ]; then
#  cd $WORKDIR/scripts/autobuild
#   runstep 11 .rsyncwww "Copying all files to $WWW_REMOTEDIR" ./rsync-www
#  fi

log "END"
