#!/bin/sh
# Checks out GeoGebra from the SVN repository
# @author Zoltan Kovacs <zoltan@geogebra.org>

# For proguard we need the java150-rt.jar file in the .. directory.
# This jar may come from different places on different operating systems.

test -r autobuild.conf || {
 echo "Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 exit 1
 }
. ./autobuild.conf

UNIX_RT_JAR=$JAVA_HOME/jre/lib/rt.jar
MACOSX_RT_JAR=/System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Classes/classes.jar

umask 0002 # trying to ensure g+w rights for all created files automatically

cd $SVNDIR
svn co --force $REPO
cd geogebra

test -r $UNIX_RT_JAR && cp $UNIX_RT_JAR ../java150-rt.jar
test -r $MACOSX_RT_JAR && cp $MACOSX_RT_JAR ../java150-rt.jar

# This is needed for signjar:
cp $P12DIR/igi-keystore.p12 ..
chmod o-rwx ../igi-keystore.p12
