#!/bin/sh
# Deploys numbered version of GeoGebra into directory 5.0
# @author Zoltan Kovacs <zoltan@geogebra.org>

# 1. Start and loading configuration
date
echo "$0: start"

# May be overridden
WWW_SERVER_LOGIN=www-refresh@www.geogebra.org
GGT_APP_INI_FILE=/home/GeoGebraTube/application/configs/application.ini

test -r autobuild.conf || {
 echo "$0: Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 exit 1
 }
. ./autobuild.conf
cd $SVNDIR/geogebra/desktop

# 2. Setting local variables
export MYVER=`cat build/unpacked/version.txt`
MYDIR=5.0

umask 0002 # trying to ensure g+w rights for all created files automatically

# 3. (Re)creating $WWWDIR/$MYDIR directory
if [ "$WWWDIR" = "" ]; then
 echo "$0: Fatal error, WWWDIR=$WWWDIR, exiting for safety reasons"
 exit 2
 fi
cd build
echo "$0: removing and creating $WWWDIR/$MYDIR directory"
rm -fR $WWWDIR/$MYDIR || exit 4 # Be careful!
mkdir -p $WWWDIR/$MYDIR || exit 3
chmod g+rwx $WWWDIR/$MYDIR || exit 3

# 4/1. Copying static files (common code with buildggb50)
rm -fR $WWWDIR/history/$MYVER || exit 4
mkdir -p $WWWDIR/history/$MYVER || exit 4
chmod g+rwx $WWWDIR/history/$MYVER || exit 4
for i in $WWWDIR/$MYDIR $WWWDIR/history/$MYVER; do
 cp -R $SVNDIR/geogebra/desktop/webstart/5.0/* $i || exit 4
 cp $SVNDIR/geogebra/desktop/geogebra/gui/images/geogebra64.png $i || exit 4
 find $i -name .svn | xargs rm -fR
 done
echo "$0: static files copied"

# 4/2. Copying/overwriting JAR files to 5.0 and history/$MYVER:
cd $SVNDIR/geogebra/desktop/build
find . -name '*.jar' -or -name '*.jar.pack.gz' -or -name version.txt -or -name geogebra-map.txt -or -name preload.html -or -name '*.var' | while read filename; do
 directory=`dirname $filename`
 mkdir -p $WWWDIR/$MYDIR/$directory $WWWDIR/history/$MYVER/$directory || exit 5
 chmod g+rwx $WWWDIR/$MYDIR/$directory $WWWDIR/history/$MYVER/$directory || exit 5
 cp $filename $WWWDIR/$MYDIR/$filename || exit 6
 cp $filename $WWWDIR/history/$MYVER/$filename || exit 6
 done

# 4/3. Rewriting *.html and *.jnlp files
# (currently the version number is not written at <\/title>"):
for dir in $WWWDIR/$MYDIR $WWWDIR/history/$MYVER; do
 cd $dir
 find . -name '*.jnlp' | while read i; do
  cat $i | \
   sed s/"\$LONGVERSION"/"$MYVER"/g | \
   sed s/"\/jnlp\/"/"\/unpacked\/"/g \
   > $i.work
  mv $i.work $i || exit 6
  
  if [ "$dir" = "$WWWDIR/history/$MYVER" ]; then
   sed -i s/"webstart\/5.0"/"webstart\/history\/$MYVER"/g $i
   fi
  
  done

 # 4/4. Copying JNLP's to debug as well:
 for i in 1 2; do
  cat $dir/geogebra-50-jogl$i.jnlp | sed s/unpacked/debug/g |\
   sed s/"\" href=\"geogebra-50"/"debug\/\" href=\"geogebra-50"/ \
   > $dir/debug/geogebra-50-jogl$i.jnlp
  done

 done # dir

# 4/5. Running jogler:
cd $SVNDIR/geogebra/desktop/scripts/autobuild
./jogler -l /tmp/deployggb50-`date +%Y%m%d%H%M`.log -t 5.0\
 -u "http://jars.geogebra.org/webstart/5.0"
./jogler -l /tmp/deployggb50-`date +%Y%m%d%H%M`.log -t history/$MYVER\
 -u "http://www.geogebra.org/webstart/5.0/history/$MYVER"

echo "$0: JAR files copied to 5.0 and history/$MYVER"

# 4/6. Rewriting main JNLP's to use jars.geogebra.org instead of www.geogebra.org
# (take care of spaces in the JNLP file!):
cd $WWWDIR/$MYDIR
for i in 1 2; do
 sed -i s/" \(href=\"http:\/\/\)www\(.geogebra.org\/webstart\)"/" \1jars\2"/g \
  geogebra-50-jogl$i.jnlp
 done

# 5. Finally, making sure that all files have group writable permissions:
WARNINGS=`chmod -R g+rw $WWWDIR/$MYDIR $WWWDIR/history 2>&1 | wc -l | awk '{print $1}'`
echo "$WARNINGS warnings during chmod'ing web files"

### TODO: Copy the missing parts here from deployggb4* ###

# 8. Copying the Windows installer version to Google Code:
if [ "$GC_USER" != "" -a "$GC_PASS" != "" ]; then

 # A significant difference to 4.2 that we create the Windows installer here
 # (not during the build step):

 # Backing up unjogled build directory:
 cd $SVNDIR/geogebra/desktop
 test -d build.unjogled && rm -fR build.unjogled
 mv build build.unjogled

 # Creating jogled build directory:
 cd $SVNDIR/geogebra/desktop/scripts/autobuild
 ./jogler -l /tmp/deployggb50-`date +%Y%m%d%H%M`.log -t build -w . -nj

 # Running installer creator:
 cd $SVNDIR/geogebra/desktop
 ant -f installer.xml installer-clean installer-windows
 cd $SVNDIR/geogebra/desktop/build/installer

 # Copying to Google Code:
 WINDOWS_INSTALLER_EXE=GeoGebra-Windows-Installer-`echo $MYVER | tr . -`.exe
 $SVNDIR/geogebra/desktop/scripts/autobuild/googlecode_upload.py -s "GeoGebra $MYVER installer for Windows" \
  -p geogebra -u $GC_USER -w "$GC_PASS" -l Test $WINDOWS_INSTALLER_EXE
 fi

### TODO: Copy the missing parts here from deployggb4* ###

# 9/1. rsync-www on demand:
if [ "$WWW_REMOTEDIR" != "" ]; then
 echo "$0: Copying all files to $WWW_REMOTEDIR"
 cd $SVNDIR/geogebra/desktop/scripts/autobuild
 ./rsync-www 2>&1 >.rsync-www
 fi

# 9/2. Push to mirrors:
cd $SVNDIR/geogebra/desktop/scripts/autobuild
./push-to-mirrors
./push-to-mirrors-rsync

# 10. Sending an email to geogebra-dev:
REVISION=`cat $SVNDIR/geogebra/desktop/scripts/autobuild/.revision`
MAIL="New version of GeoGebra 5.0 has just been uploaded: $MYVER\nhttp://dev.geogebra.org/trac/log/trunk?rev=$REVISION\nAutomatic message, do not reply"
echo $MAIL | mail -s "deployggb50 report" geogebra-dev@googlegroups.com

# 11. Updating GeoGebraTube application.ini
# (not very elegant, but works --- FIXME: implement it with a sed one-liner in place)
scp -P $WWW_SERVER_PORT -i $WWW_SERVER_KEY $WWW_SERVER_LOGIN:$GGT_APP_INI_FILE .ggt-app.ini
cat .ggt-app.ini | awk '{
if ($1=="geogebra.version50")
 print "geogebra.version50 = " ENVIRON["MYVER"]
else
 print $0
}' > .ggt-app.ini.new
scp -P $WWW_SERVER_PORT -i $WWW_SERVER_KEY .ggt-app.ini.new $WWW_SERVER_LOGIN:$GGT_APP_INI_FILE

date
echo "$0: end"
