#!/bin/sh
# Allows a Google Code upload if version number is an X.Y.Z.W
# and Z is a multiple of 10.
# Input: the version number
# Output: 0 if allowed, 1 if not.

Z=`echo $1 | cut -f3 -d.`
if [ "$Z" != "" ]; then
 if [ `expr $Z % 10` = 0 ]; then
  exit 0
  fi
 fi
exit 1
