#!/bin/sh
# Explodes properties files from ggbtrans and inserts them into SVN.
# SVN can confuse itself on file deletion and re-addition, so
# we use a workaround by running the ./svnsync script.
# Hopefully this will do the trick! Fingers crossed. ;-)

# @author Zoltan Kovacs <zoltan@geogebra.org>

# Edit these variables if needed:
GGBTRANS_DIR=/home/ggbtrans/svn/ggbtrans
BRANCHES_DIR=/home/ggbtrans/svn/branches
SVNSYNC=`pwd`/svnsync

# Updating SVN:
# cd $BRANCHES_DIR/ggb40
# svn update --force
cd $BRANCHES_DIR/ggb42
svn update --force

cd $BRANCHES_DIR/wiki
svn update --force

# Deleting old properties files:
# cd $BRANCHES_DIR/ggb40/geogebra/geogebra/properties
# rm -f *.properties
cd $BRANCHES_DIR/ggb42/geogebra/desktop/geogebra/properties
rm -f *.properties

cd $BRANCHES_DIR/wiki/geogebra/properties
rm -f *.properties

# Explode the properties files and commit:
# $GGBTRANS_DIR/export.py 4.0 $BRANCHES_DIR/ggb40/geogebra/geogebra/properties
$GGBTRANS_DIR/export.py 4.2 $BRANCHES_DIR/ggb42/geogebra/desktop/geogebra/properties
cd $BRANCHES_DIR/ggb42/geogebra/desktop/geogebra/properties
cp $BRANCHES_DIR/ggb42/geogebra/desktop/geogebra/properties/*.properties $BRANCHES_DIR/wiki/geogebra/properties

### Arnaud's hacks for GWT translations... ###
# This section is mostly copy-pasted from ggbtrans-to-svn #

# Delete the GWT properties directory:
GWTPROP_DIR=$BRANCHES_DIR/ggb42/geogebra/web/src/geogebra/web/properties
rm -rf $GWTPROP_DIR

# Delete properties_keys.js
JS_DIR=$BRANCHES_DIR/ggb42/geogebra/web/src/geogebra/resources/js
JSKEYS=properties_keys.js
JSKEYS_PATH=$JS_DIR/$JSKEYS
rm -f $JSKEYS_PATH

# XXX This is currently done by ggbtrans at 22.00 daily XXX
# Make a snapshot of ggbtransdb for export
# $GGBTRANS_DIR/export.py setup

# Generate properties_keys.js
$GGBTRANS_DIR/export.py gwtjs $JS_DIR
# Create localizations
$GGBTRANS_DIR/export.py gwtjs4.2 $JS_DIR

`$SVNSYNC`
svn commit -m "ggb42: GWT JS translations automatically updated from ggbtrans"

### End of Arnaud's hacks ###

# cd $BRANCHES_DIR/ggb40/geogebra/geogebra/properties
# `$SVNSYNC`
# svn commit -m "ggb40: *.properties files automatically updated from ggbtrans"

$GGBTRANS_DIR/export.py wiki $BRANCHES_DIR/wiki/geogebra/properties
cd $BRANCHES_DIR/wiki/geogebra/properties
`$SVNSYNC`
svn commit -m "wiki: *.properties files automatically updated from ggbtrans"
