#!/bin/sh
# Explodes properties files from ggbtrans and inserts them into SVN.
# SVN can confuse itself on file deletion and re-addition, so
# we use a workaround by running the ./svnsync script.
# Hopefully this will do the trick! Fingers crossed. ;-)

# @author Zoltan Kovacs <zoltan@geogebra.org>

# Edit these variables if needed:
GGBTRANS_DIR=/home/ggbtrans/svn/ggbtrans
BRANCHES_DIR=/home/ggbtrans/svn/branches
SVNSYNC=`pwd`/svnsync

# Updating SVN:
# cd $BRANCHES_DIR/ggb40
# svn update --force
cd $BRANCHES_DIR/ggb42
svn update --force

cd $BRANCHES_DIR/wiki
svn update --force

# Deleting old properties files:
# cd $BRANCHES_DIR/ggb40/geogebra/geogebra/properties
# rm -f *.properties
cd $BRANCHES_DIR/ggb42/geogebra/desktop/geogebra/properties
rm -f *.properties

cd $BRANCHES_DIR/wiki/geogebra/properties
rm -f *.properties

# Explode the properties files and commit:
# $GGBTRANS_DIR/export.py 4.0 $BRANCHES_DIR/ggb40/geogebra/geogebra/properties
$GGBTRANS_DIR/export.py 4.2 $BRANCHES_DIR/ggb42/geogebra/desktop/geogebra/properties
cd $BRANCHES_DIR/ggb42/geogebra/desktop/geogebra/properties
cp $BRANCHES_DIR/ggb42/geogebra/desktop/geogebra/properties/*.properties $BRANCHES_DIR/wiki/geogebra/properties

`$SVNSYNC`
svn commit -m "ggb42: *.properties files automatically updated from ggbtrans"

# cd $BRANCHES_DIR/ggb40/geogebra/geogebra/properties
# `$SVNSYNC`
# svn commit -m "ggb40: *.properties files automatically updated from ggbtrans"

$GGBTRANS_DIR/export.py wiki $BRANCHES_DIR/wiki/geogebra/properties
cd $BRANCHES_DIR/wiki/geogebra/properties
`$SVNSYNC`
svn commit -m "wiki: *.properties files automatically updated from ggbtrans"
