#!/bin/sh
# Explodes properties files from ggbtrans and uploads them to www.geogebra.org.

# The 'tube' keys go to Library/WebServer/GeoGebraTube/languages/,
# the 'navigation' keys go to /Library/WebServer/GeoGebra/navigation/
# (see http://www.geogebra.org/trac/ticket/1628 for details).

# @author Zoltan Kovacs <zoltan@geogebra.org>

# Edit these variables if needed (you can override them by use settings from autobuild.conf):
GGBTRANS_DIR=/home/ggbtrans/svn/ggbtrans
TUBE_REMOTEDIR=www.geogebra.org:/tmp/rsync-www-test-tube
NAV_REMOTEDIR=www.geogebra.org:/tmp/rsync-www-test-nav

test -r autobuild.conf || {
 echo "Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 exit 1
 }
. ./autobuild.conf

# Remove the previous working directory:
PROP_DIR=properties
rm -fR $PROP_DIR

# Explode the properties files:
for i in tube nav; do
 mkdir -p $PROP_DIR/$i
 $GGBTRANS_DIR/export.py $i $PROP_DIR/$i
 done

# Tube files must be renamed:
MYDIR=`pwd`
cd $PROP_DIR/tube
mv tube_no_NO.properties nb.properties
mv tube_no_NO_NY.properties nn.properties
for i in tube_*.properties; do
 NAME=`echo $i | sed s/^tube_//`
 mv $i $NAME
 done
mv tube.properties en.properties
# 0 length files must be deleted:
find -name '*.properties' -size 0 | xargs rm
cd $MYDIR

# Rsync files to www:
rsync -avPO --rsh="ssh -p $WWW_SERVER_PORT -i $WWW_SERVER_KEY" \
 $PROP_DIR/tube/* $WWW_SERVER_LOGIN:$TUBE_REMOTEDIR 2>&1 | grep -v failed | grep -v "were not transferred"
rsync -avPO --rsh="ssh -p $WWW_SERVER_PORT -i $WWW_SERVER_KEY" \
 $PROP_DIR/nav/* $WWW_SERVER_LOGIN:$NAV_REMOTEDIR 2>&1 | grep -v failed | grep -v "were not transferred"

# The script should also remove all files
# /home/GeoGebra/navigation/cache/* and
# /home/GeoGebraTube/tmp/cache/zend_cache---Zend_Translate_*
# so that the properties are really used.
ssh -p $WWW_SERVER_PORT -i $WWW_SERVER_KEY $WWW_SERVER_LOGIN \
 "cd /home/GeoGebra/navigation/cache && find . -name '*.php' | xargs rm"
ssh -p $WWW_SERVER_PORT -i $WWW_SERVER_KEY $WWW_SERVER_LOGIN \
 "cd /home/GeoGebraTube/tmp/cache && find . -name 'zend_cache---Zend_Translate*' | xargs rm"
# It is important to make sure that during copying the user should have enough privileges.

date
echo "$0: end"
