#!/bin/sh
# Explodes properties files from ggbtrans and inserts them into SVN.
# Since SVN can confuse itself on file deletion and re-addition,
# here we use Ralf Hemmecke's idea instead: working on a git
# clone of the SVN repository, do the changes, and push (rebase)
# the changes into the SVN repository back.

# For Ralf's original script (suggested for MathPiper update)
# see http://groups.google.com/group/geogebra-dev/browse_thread/thread/64f155a0ae709c39/c34c3c027d2342fb

# @author Zoltan Kovacs <zoltan@geogebra.org>
# Modifications by Arnaud Delobelle and Zbynek Konecny

# Edit these variables if needed:
GGBTRANS_DIR=/home/ggbtrans/svn/ggbtrans
GITCLONE_DIR=../geogebra

# Remove the previous working copy of the git clone:
rm -fR geogebra

# Copy the git-svn clone here:
cp -a $GITCLONE_DIR .

# Update this working directory to latest GeoGebra trunk:
cd geogebra
git svn rebase

# Delete the properties directory:
PROP_DIR=desktop/geogebra/properties
git rm -rf $PROP_DIR

### Arnaud's hacks for GWT translations... ###

# Delete the GWT properties directory:
GWTPROP_DIR=web/src/geogebra/web/properties
git rm -rf $GWTPROP_DIR

# Delete properties_keys.js
JS_DIR=web/src/geogebra/resources/js
JSKEYS=properties_keys.js
JSKEYS_PATH=$JS_DIR/$JSKEYS
git rm $JSKEYS_PATH

# XXX This is currently done by ggbtrans at 22.00 daily XXX
# Make a snapshot of ggbtransdb for export
# $GGBTRANS_DIR/export.py setup

# Explode the properties files:
mkdir -p $PROP_DIR
$GGBTRANS_DIR/export.py trunk $PROP_DIR

# Explode the GWT properties files
mkdir -p $GWTPROP_DIR
$GGBTRANS_DIR/export.py gwt $GWTPROP_DIR

# Generate the java interfaces
$GGBTRANS_DIR/export.py gwtjava $GWTPROP_DIR

# Generate properties_keys.js
$GGBTRANS_DIR/export.py gwtjs $JS_DIR
# Create localizations
$GGBTRANS_DIR/export.py gwtjs5.0 $JS_DIR

### End of Arnaud's hacks ###

# Generate interlingua related properties (Zbynek's hack)
cd ..
./interlingua
cd geogebra

# Add new files (with directory):
git add $PROP_DIR
git add $GWTPROP_DIR
git add $JS_DIR

git commit -m "properties files and related resources automatically updated from ggbtrans"

# Commit to official GeoGebra SVN:
git svn dcommit
