#!/bin/sh
#
# GeoGebra - Dynamic Mathematics for Everyone
# http://www.geogebra.org
#
# This file is part of GeoGebra.
#
# This program is free software; you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by 
# the Free Software Foundation.
#
# Script for generating properties files which allow translators
# to display property keys insted of values. The key is prefixed
# with filename and all %0,%1 references are appended to the end.
#
# Example:
#
# CircleWithCenterAandRadiusB=Circle with center %0 and radius %1
#
# goes to
#
# CircleWithCenterAandRadiusB=CircleWithCenterAandRadiusB_plain:%0,%1
#
# @author Zbynek Konecny <zbynek@geogebra.org>
# @author Ralf Hemmecke <ralf@hemmecke.de>

# The sed expression below does the following:
# h                         -- store the line
# s/\([^%]\)[0-9]/\1/g      -- remove digits not prepended by %
# s/[^%0-9]//g              -- only leave % and digits on the line
# s/%/,%/g                  -- %0%1 ==> ,%0,%1
# x                         -- exchange buffer with saved line
# s/\([^=]*\)=.*/\1=\1_$f/  -- A=something ==> A=A_plain
# G                         -- append the ,%0,%1 buffer
# s/\n,/:/                  -- ==> A=A_plain:%0,%1
# s/:$//                    -- remove colon if there were no %0 in the line
# The script assumes that %0, %1, etc. are in the right order, i.e.
#   foo=move %1 to %0
# on input will give
#   foo=foo:%1,%0
# instead of
#   foo=foo:%0,%1

cd ../desktop/geogebra/properties
for f in menu colors symbols error command plain; do
    grep -v '^[ \t]*#' $f.properties \
    | sed "h;s/\([^%]\)[0-9]/\1/g;s/[^%0-9]//g;s/%/,%/g;x;s/\([^=]*\)=.*/\1=\1_$f/;G;s/\n,/:/;s/:$//" \
    | grep = \
    > $f"_ia.properties"
done
