#!/bin/sh
# The JOGL juggler. Creates a mixture of build directory from JOGL1 and JOGL2 builds.

MYDIR=test50
CV=5.0
COMPILE=0
WWWDIR=/home/build/www-autobuild
JNLP=1
JH="" # contains -j $JAVA_HOME if $JAVA_HOME is not empty
JT=""

ORIGDIR=`dirname $0`
cd $ORIGDIR
ORIGDIR=`pwd`

# 1/1. Start and loading configuration
test -r autobuild.conf || {
 echo "$0: Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 # exit 1
 }
test -r autobuild.conf && . ./autobuild.conf

# 1/2. Reading command line arguments
while [ $# -gt 0 ]; do
 case $1 in
  -h | -help | --help)
   echo "This script jogles GeoGebra 5 files."
   echo
   echo "Usage: $0 [options]"
   echo " Where options can be (defaults in parentheses):"
   echo "  -h, -help, --help         This help"
   echo "  -c                        Compile first (runs build-pack-installer)"
   echo "  -l [file]                 Logging to file (passed to build-pack-installer)"
   echo "  -u [url]                  Target URL (passed to build-pack-installer)"
   echo "  -nt                       Do not download third-party components (passed to build-pack-installer)"
   echo "  -ne                       Do not stop on an ecj error (passed to build-pack-installer)"
   echo "  -j [dir]                  Set JAVA_HOME to dir (passed to build-pack-installer)"
   echo "  -nj                       Do not create JNLP files"
   echo "  -nt                       Do not run jartest"
   echo "  -t [dir]                  Target directory ($MYDIR)"
   echo "  -w [dir]                  Target directory root folder, absolute path to target URL ($WWWDIR)"
   echo "                            (Final target will be $WWWDIR/$MYDIR, set by -w and -t."
   echo "                            Use '-t .' if you want to jogle a single directory.)"
   exit 0
   ;;

  -l)
   shift
   L="-l $1"
   ;;

  -u)
   shift
   TESTURL="$1"
   TU="-tu $TESTURL"
   ;;

  -j)
   shift
   JH="-j $1"
   ;;

  -t)
   shift
   MYDIR="$1"
   ;;

  -w)
   shift
   WWWDIR="$1"
   ;;

  -c)
   COMPILE=1
   ;;

  -nt)
   TP="-nt"
   ;;

  -ne)
   EE="-ne"
   ;;

  -nj)
   JNLP=0
   ;;

  -nt)
   JT="-nt"
   ;;

  *)
   echo "Unknown parameter: $1. Use \"$0 -h\" for help."
   exit 32
   ;;

  esac
 shift
 done

# 2. Compilation
if [ $COMPILE = 1 ]; then
 for i in 1 2; do
  cd $ORIGDIR
  ./build-pack-installer -l /tmp/jogler.log $L $TU -cv 5.0 -J $i $TP $EE -ni $JH $JT || exit $?
  cd ../..
  rm -fR build-jogl$i
  cp -a build build-jogl$i
  done
 fi

# 3. Copying files
cd $ORIGDIR/../..

copyover () {
JOGL=$1; FILENAME=$2; NEWNAME=$3
find build-jogl$JOGL -name $FILENAME | while read FILE; do
 DIR=`dirname $FILE`
 DIR2=`echo $DIR | sed s/build-jogl$JOGL//`
 COMMAND="cp $FILE $WWWDIR/$MYDIR/$DIR2/$NEWNAME"
 echo $COMMAND
 $COMMAND
 done
}

for i in jar jar.pack.gz; do
 copyover 1 geogebra.$i geogebra-jogl1.$i
 copyover 1 gluegen-rt.$i gluegen-rt-jogl1.$i
 copyover 1 geogebra_3d.$i geogebra_3d-jogl1.$i
 copyover 2 geogebra.$i geogebra-jogl2.$i
 copyover 2 geogebra_3d.$i geogebra_3d-jogl2.$i
 done

# 3/2. Copying over jogl.jar and jogl1-*.jar
find build-jogl1 -name jogl.jar -or -name 'jogl1-*.jar' | while read FILE; do
 DIR=`dirname $FILE`
 DIR2=`echo $DIR | sed s/build-jogl1//`
 COMMAND="cp $FILE $WWWDIR/$MYDIR/$DIR2"
 echo $COMMAND
 $COMMAND
 done

# 4. Deleting unnecessary files
find $WWWDIR/$MYDIR -name geogebra.jar -or -name geogebra_3d.jar | xargs rm

# 5. Changing JNLP files
if [ "$JNLP" = 0 ]; then
 exit 0
 fi

for i in . debug; do
 sed -i -e s/"geogebra\.jar"/geogebra-jogl1.jar/g \
  -e s/"geogebra_3d\.jar"/geogebra_3d-jogl1.jar/g \
  -e s/"gluegen-rt\.jar"/gluegen-rt-jogl1.jar/g \
  $WWWDIR/$MYDIR/$i/geogebra-50-jogl1.jnlp

 sed -i -e s/"geogebra\.jar"/geogebra-jogl2.jar/g \
  -e s/"geogebra_3d\.jar"/geogebra_3d-jogl2.jar/g \
  $WWWDIR/$MYDIR/$i/geogebra-50-jogl2.jnlp

 sed -i -e s/"geogebra\.jar"/geogebra-jogl1.jar/g \
  $WWWDIR/$MYDIR/$i/geogebra-50-no3d.jnlp

 done
