#!/bin/sh
# Pushes files to be deployed towards all mirror servers --- rsync version.
# To use it, set up remote mirror servers described at http://www.geogebra.org/trac/wiki/MirrorServers,
# create an rsync login there with username and password.
# Edit details for each mirror server in mirrors-rsync.conf.
# The remote server must ensure that http://$IP/webstart
# is the same directory which is accessed with
# "RSYNC_PASSWORD=$RSYNC_PASSWORD rsync -a webstart rsync://$RUSER@$IP:$PORT/$DIR/"

# @author Zoltan Kovacs <zoltan@geogebra.org>

# 1. Start and loading configuration
date
echo "$0: start"

test -r autobuild.conf || {
 echo "$0: Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 exit 1
 }
. ./autobuild.conf

# 2. Setting local variables

# FIXME: Assuming the local directory is already created in the directory RSYNC_LOCALDIR variable
if [ "$RSYNC_LOCALDIR" = "" ]; then
 echo "RSYNC_LOCALDIR is not set, exiting"
 exit 2
 fi

if [ ! -r mirrors-rsync.conf ]; then
 echo "mirrors-rsync.conf is missing, exiting"
 exit 2
 fi

MYDIR=5.0
cd $WWWDIR/$MYDIR
MYVER=`cat unpacked/version.txt`

cd $RSYNC_LOCALDIR

cat $SVNDIR/geogebra/desktop/scripts/autobuild/mirrors-rsync.conf | grep -v "^#" | grep -v "^$" | while read IP PORT RUSER DIR RSYNC_PASSWORD; do
 echo "Copying files to rsync://$RUSER@$IP:$PORT/$DIR..."
 RSYNC_PASSWORD=$RSYNC_PASSWORD rsync -avILK --delete webstart rsync://$RUSER@$IP:$PORT/$DIR/

 # TODO: Automatic check (by wget)

 done

date
echo "$0: end"
