#!/bin/sh
# Runs rsync to copy all required files to www.geogebra.org
# @author Zoltan Kovacs <zoltan@geogebra.org>

# 1. Start and loading configuration
date
echo "$0: start"

test -r autobuild.conf || {
 echo "Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 exit 1
 }
. ./autobuild.conf

# 2. rsync'ing
WWW_SERVER_USER=`echo $WWW_SERVER_LOGIN | cut -f1 -d@`
WWW_REMOTEDIR=`echo $WWW_SERVER_LOGIN | cut -f2 -d@`
rsync -avPO -e "ssh -p $WWW_SERVER_PORT -i $WWW_SERVER_KEY -l $WWW_SERVER_USER" \
 $WWWDIR/* $WWW_REMOTEDIR 2>&1 | grep -v failed | grep -v "were not transferred"

date
echo "$0: end"
