#!/bin/sh
# Runs rsync to copy all required files to www.geogebra.org
# @author Zoltan Kovacs <zoltan@geogebra.org>

# 1. Start and loading configuration
date
echo "$0: start"

WWW_REMOTEDIR=www.geogebra.org:/tmp/rsync-www-test

test -r autobuild.conf || {
 echo "Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 exit 1
 }
. ./autobuild.conf

# 2. rsync'ing
rsync -avPO --rsh=ssh $WWWDIR/* $WWW_REMOTEDIR 2>&1 | grep -v failed | grep -v "were not transferred"

date
echo "$0: end"
