#!/bin/sh
# This program is a simple workaround to synchronize the remote SVN
# directory with the current contents of the working directory.
# No input (currently), output: the suggested SVN commands.
# FIXME: No recursion is implemented yet.

# @author Zoltan Kovacs <zoltan@geogebra.org>

# 1. Creating temporary files for contents
REMOTE_CONTENTS=`tempfile`
LOCAL_CONTENTS=`tempfile`
DIFFFILE=`tempfile`
TO_REMOVE=`tempfile`
TO_ADD=`tempfile`

# 2. Download and sort the SVN remote files:
svn ls | sed s/"\/\$"// | sort > $REMOTE_CONTENTS

# 3. Create file for local contents:
ls -1 -a --color=no | grep -v ^.svn$ | grep -v ^.$ | grep -f ^..$ | sort > $LOCAL_CONTENTS

# 4. Diffing and sorting out files:
diff $REMOTE_CONTENTS $LOCAL_CONTENTS > $DIFFFILE
cat $DIFFFILE | grep ^"<" > $TO_REMOVE
cat $DIFFFILE | grep ^">" > $TO_ADD

# 5. Outputting the required SVN commands
if [ -s $TO_REMOVE ]; then
 echo -n "svn remove"
 cat $TO_REMOVE | awk '{printf(" %s",substr($0,3))}'
 echo
 fi
if [ -s $TO_ADD ]; then
 echo -n "svn add"
 cat $TO_ADD | awk '{printf(" %s",substr($0,3))}'
 echo
 fi

# 6. Cleanup:
rm -f $REMOTE_CONTENTS $LOCAL_CONTENTS $DIFFFILE $TO_DELETE $TO_ADD
