#!/bin/sh
test -r autobuild.conf || {
 echo "Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 # exit 1
 }
test -r autobuild.conf && . ./autobuild.conf

cd $SVNDIR/geogebra/desktop/build/packed
mkdir temp
for i in *.jar.pack.gz; do
 j=`basename $i .pack.gz`
 /bin/echo -n "$j: " # /bin/echo is needed for Mac OS X
 $JAVA_HOME/bin/unpack200 $i temp/$j
 $JAVA_HOME/bin/jarsigner --verify temp/$j || exit $?
 done
rm -fR temp
