/* Generated By:JavaCC: Do not edit this line. PolynomialParserConstants.java */
package geogebra.common.kernel.prover.polynomial;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface PolynomialParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int VARIABLE = 6;
  /** RegularExpression Id. */
  int STARTFACTLIST = 7;
  /** RegularExpression Id. */
  int ANYFACTLIST = 8;
  /** RegularExpression Id. */
  int INDEXPOLY = 9;
  /** RegularExpression Id. */
  int COMMA = 10;
  /** RegularExpression Id. */
  int PLUS = 11;
  /** RegularExpression Id. */
  int MINUS = 12;
  /** RegularExpression Id. */
  int TIMES = 13;
  /** RegularExpression Id. */
  int POWER = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NUMBER>",
    "<VARIABLE>",
    "\"[1]:\"",
    "<ANYFACTLIST>",
    "<INDEXPOLY>",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"^\"",
  };

}
