package geogebra.web.properties;
import com.google.gwt.i18n.client.ConstantsWithLookup;

/**
 * THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT THIS FILE!
 * Error interface
 * GWT implementation of Error internationalization.
 * @author ggbtrans
 *
 */
public interface ErrorConstants extends ConstantsWithLookup {

    @DefaultStringValue("Every angle has to be constant")
    String AngleMustBeConstant();

    @DefaultStringValue("Please close the browser window to exit GeoGebra")
    String AppletWindowClosing();

    @DefaultStringValue("Free objects may not be overwritten by dependent objects")
    String AssignmentDependentToFree();

    @DefaultStringValue("Dependent objects may not be overwritten")
    String AssignmentToDependent();

    @DefaultStringValue("Fixed objects may not be changed")
    String AssignmentToFixed();

    @DefaultStringValue("Sorry, something went wrong. Please check your input")
    String CAS_GeneralErrorMessage();

    @DefaultStringValue("One or more references are invalid")
    String CAS_InvalidReferenceError();

    @DefaultStringValue("Please check the structure of your selection")
    String CAS_SelectionStructureError();

    @DefaultStringValue("Calculation took too long and was aborted")
    String CAS_TimeoutError();

    @DefaultStringValue("Attempt to assign dynamic reference")
    String CAS_VariableIsDynamicReference();

    @DefaultStringValue("Dependent objects may not be changed")
    String ChangeDependent();

    @DefaultStringValue("Circular definition")
    String CircularDefinition();

    @DefaultStringValue("Coordinates have to be constant")
    String CoordinatesMustBeConstant();

    @DefaultStringValue("Every divisor has to be constant")
    String DivisorMustBeConstant();

    @DefaultStringValue("Error")
    String Error();

    @DefaultStringValue("Every exponent has to be constant")
    String ExponentMustBeConstant();

    @DefaultStringValue("Every exponent has to be an integer")
    String ExponentMustBeInteger();

    @DefaultStringValue("Sorry, the geogebra_export.jar file is missing or corrupt")
    String ExportJarMissing();

    @DefaultStringValue("Please upgrade to a newer version of GeoGebra\nThis file format is not supported")
    String FileFormatNewer();

    @DefaultStringValue("Unknown file format")
    String FileFormatUnknown();

    @DefaultStringValue("Data file is too large")
    String FileIsTooLarge();

    @DefaultStringValue("File not found")
    String FileNotFound();

    @DefaultStringValue("Function expected")
    String FunctionExpected();

    @DefaultStringValue("Could not find online help")
    String HelpNotFound();

    @DefaultStringValue("Illegal addition")
    String IllegalAddition();

    @DefaultStringValue("Illegal argument")
    String IllegalArgument();

    @DefaultStringValue("Illegal number of arguments")
    String IllegalArgumentNumber();

    @DefaultStringValue("Illegal assignment")
    String IllegalAssignment();

    @DefaultStringValue("Illegal Boolean operation")
    String IllegalBoolean();

    @DefaultStringValue("Illegal comparison")
    String IllegalComparison();

    @DefaultStringValue("Illegal complex multiplication")
    String IllegalComplexMultiplication();

    @DefaultStringValue("Illegal division")
    String IllegalDivision();

    @DefaultStringValue("Illegal exponent")
    String IllegalExponent();

    @DefaultStringValue("Illegal list operation")
    String IllegalListOperation();

    @DefaultStringValue("Illegal multiplication")
    String IllegalMultiplication();

    @DefaultStringValue("Illegal subtraction")
    String IllegalSubtraction();

    @DefaultStringValue("Illegal variable")
    String IllegalVariable();

    @DefaultStringValue("Incomplete equation:\nPlease enter both sides of the equation")
    String IncompleteEquation();

    @DefaultStringValue("Invalid equation:\nPlease enter a polynomial equation in x and y")
    String InvalidEquation();

    @DefaultStringValue("Invalid function:\nPlease enter an explicit function in x")
    String InvalidFunction();

    @DefaultStringValue("Invalid inequality:\nPlease enter a linear inequality in x and y")
    String InvalidInequality();

    @DefaultStringValue("Invalid input")
    String InvalidInput();

    @DefaultStringValue("Every length has to be constant")
    String LengthMustBeConstant();

    @DefaultStringValue("Opening file failed")
    String LoadFileFailed();

    @DefaultStringValue("This label is already in use")
    String NameUsed();

    @DefaultStringValue("Number expected")
    String NumberExpected();

    @DefaultStringValue("Sorry - couldn't paste bitmap from the clipboard")
    String PasteImageFailed();

    @DefaultStringValue("Rename failed")
    String RenameFailed();

    @DefaultStringValue("Redefinition failed")
    String ReplaceFailed();

    @DefaultStringValue("Saving file failed")
    String SaveFileFailed();

    @DefaultStringValue("Command name is already used by another tool")
    String Tool_CommandNameTaken();

    @DefaultStringValue("Tool could not be created")
    String Tool_CreationFailed();

    @DefaultStringValue("Following tools were used to create selected objects and cannot be deleted:")
    String Tool_DeleteUsed();

    @DefaultStringValue("Input object is not needed")
    String Tool_InputNotNeeded();

    @DefaultStringValue("Output object does not depend on input objects")
    String Tool_OutputNotDependent();

    @DefaultStringValue("Opening URL failed")
    String URLnotFound();

    @DefaultStringValue("Undefined variable")
    String UndefinedVariable();

    @DefaultStringValue("Unknown command")
    String UnknownCommand();

    @DefaultStringValue("The chosen look and feel is not available on your computer")
    String UnsupportedLAF();

    @DefaultStringValue("Point or vector expected")
    String VectorExpected();


}
