/*
 * GeoGebra - Dynamic Mathematics for Everyone
 * Copyright (c) GeoGebra GmbH, Altenbergerstr. 69, 4040 Linz, Austria
 * https://www.geogebra.org
 *
 * This file is licensed by GeoGebra GmbH under the EUPL 1.2 licence and
 * may be used under the EUPL 1.2 in compatible projects (see Article 5
 * and the Appendix of EUPL 1.2 for details).
 * You may obtain a copy of the licence at:
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Note: The overall GeoGebra software package is free to use for
 * non-commercial purposes only.
 * See https://www.geogebra.org/license for full licensing details
 */

package org.geogebra.common.kernel.geos;

import org.geogebra.common.kernel.Path;
import org.geogebra.common.kernel.Transform;

/**
 * Represents geos with endpoints (segment, ray, arc, etc.)
 *
 */
public interface LimitedPath extends Path {

	/**
	 * Returns whether intersection points with this path are allowed that lie
	 * on the extension of this path.
	 * 
	 * @return true iff outlying intersection should be allowed
	 */
	public boolean allowOutlyingIntersections();

	/**
	 * Sets whether intersection points with this path are allowed that lie on
	 * the extension of this path.
	 * 
	 * @param flag
	 *            true iff outlying intersection should be allowed
	 */
	public void setAllowOutlyingIntersections(boolean flag);

	/**
	 * Returns true iff the intersection point P lies on this limited path.
	 * 
	 * @param P
	 *            intersection point
	 * @param eps
	 *            epsilon precision for testing
	 * @return true iff the intersection point P lies on this limited path.
	 * 
	 */
	public boolean isIntersectionPointIncident(GeoPoint P, double eps);

	/**
	 * Returns whether a geometric transform of this path should yield an object
	 * of the same kind (i.e. segment becomes segment).
	 * 
	 * @return true iff the geo keeps type on transform
	 */
	public boolean keepsTypeOnGeometricTransform();

	/**
	 * Sets whether a geometric transform of this path should yield an object of
	 * the same kind (i.e. segment becomes segment).
	 * 
	 * @param flag
	 *            true when a geometric transform of this path should yield an
	 *            object of the same kind
	 */
	public void setKeepTypeOnGeometricTransform(boolean flag);

	/**
	 * Creates a new object using the geometrical transform of the given type.
	 * 
	 * @param t
	 *            transform
	 * @param label
	 *            label for new object
	 * @return array of elements generated by transform
	 */
	public GeoElement[] createTransformedObject(Transform t, String label);

	/**
	 * Returns true iff all endpoints are labeled
	 * 
	 * @return true iff all endpoints are labeled
	 */
	public boolean isAllEndpointsLabelsSet();

}
