package org.geogebra.common.gui.menu;

/**
 * The icons that the menu items can show.
 */
public enum Icon {
	CLEAR, SAVE, HOURGLASS_EMPTY, GEOGEBRA, SETTINGS, HELP, PRINT, SEARCH, EXPORT_FILE,
	EXPORT_IMAGE, ASSIGNMENT, SCHOOL, BUG_REPORT, PRIVACY_POLICY, INFO, SIGN_IN, SIGN_OUT,
	USER_ICON, DOWNLOAD, SAVE_ONLINE, FOLDER
}
