package org.geogebra.common.plugin;

public enum ActionType {
	REMOVE, ADD, UPDATE,
	CLEAR_PAGE, REMOVE_PAGE, ADD_PAGE, PASTE_PAGE, MOVE_PAGE, RENAME_PAGE,
	EMBEDDED_PRUNE_STATE_LIST, REDO, SET_CONTENT, UNDO,
	SPLIT_STROKE, MERGE_STROKE, UPDATE_ORDERING
}
