/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package javagiac;

public final class gen_comp_subtypes {
  public final static gen_comp_subtypes _SEQ__VECT = new gen_comp_subtypes("_SEQ__VECT", 1);
  public final static gen_comp_subtypes _SET__VECT = new gen_comp_subtypes("_SET__VECT", 2);
  public final static gen_comp_subtypes _RPN_FUNC__VECT = new gen_comp_subtypes("_RPN_FUNC__VECT", 3);
  public final static gen_comp_subtypes _RPN_STACK__VECT = new gen_comp_subtypes("_RPN_STACK__VECT", 4);
  public final static gen_comp_subtypes _GROUP__VECT = new gen_comp_subtypes("_GROUP__VECT", 5);
  public final static gen_comp_subtypes _LINE__VECT = new gen_comp_subtypes("_LINE__VECT", 6);
  public final static gen_comp_subtypes _VECTOR__VECT = new gen_comp_subtypes("_VECTOR__VECT", 7);
  public final static gen_comp_subtypes _PNT__VECT = new gen_comp_subtypes("_PNT__VECT", 8);
  public final static gen_comp_subtypes _CURVE__VECT = new gen_comp_subtypes("_CURVE__VECT", 8);
  public final static gen_comp_subtypes _HALFLINE__VECT = new gen_comp_subtypes("_HALFLINE__VECT", 9);
  public final static gen_comp_subtypes _POLY1__VECT = new gen_comp_subtypes("_POLY1__VECT", 10);
  public final static gen_comp_subtypes _MATRIX__VECT = new gen_comp_subtypes("_MATRIX__VECT", 11);
  public final static gen_comp_subtypes _RUNFILE__VECT = new gen_comp_subtypes("_RUNFILE__VECT", 12);
  public final static gen_comp_subtypes _ASSUME__VECT = new gen_comp_subtypes("_ASSUME__VECT", 13);
  public final static gen_comp_subtypes _SPREAD__VECT = new gen_comp_subtypes("_SPREAD__VECT", 14);
  public final static gen_comp_subtypes _CELL__VECT = new gen_comp_subtypes("_CELL__VECT", 15);
  public final static gen_comp_subtypes _EQW__VECT = new gen_comp_subtypes("_EQW__VECT", 16);
  public final static gen_comp_subtypes _HIST__VECT = new gen_comp_subtypes("_HIST__VECT", 17);
  public final static gen_comp_subtypes _TILIST__VECT = new gen_comp_subtypes("_TILIST__VECT", 0);
  public final static gen_comp_subtypes _FOLDER__VECT = new gen_comp_subtypes("_FOLDER__VECT", 18);
  public final static gen_comp_subtypes _SORTED__VECT = new gen_comp_subtypes("_SORTED__VECT", 19);
  public final static gen_comp_subtypes _POINT__VECT = new gen_comp_subtypes("_POINT__VECT", 20);
  public final static gen_comp_subtypes _POLYEDRE__VECT = new gen_comp_subtypes("_POLYEDRE__VECT", 21);
  public final static gen_comp_subtypes _RGBA__VECT = new gen_comp_subtypes("_RGBA__VECT", 22);
  public final static gen_comp_subtypes _LIST__VECT = new gen_comp_subtypes("_LIST__VECT", 23);
  public final static gen_comp_subtypes _LOGO__VECT = new gen_comp_subtypes("_LOGO__VECT", 24);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static gen_comp_subtypes swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + gen_comp_subtypes.class + " with value " + swigValue);
  }

  private gen_comp_subtypes(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private gen_comp_subtypes(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private gen_comp_subtypes(String swigName, gen_comp_subtypes swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static gen_comp_subtypes[] swigValues = { _SEQ__VECT, _SET__VECT, _RPN_FUNC__VECT, _RPN_STACK__VECT, _GROUP__VECT, _LINE__VECT, _VECTOR__VECT, _PNT__VECT, _CURVE__VECT, _HALFLINE__VECT, _POLY1__VECT, _MATRIX__VECT, _RUNFILE__VECT, _ASSUME__VECT, _SPREAD__VECT, _CELL__VECT, _EQW__VECT, _HIST__VECT, _TILIST__VECT, _FOLDER__VECT, _SORTED__VECT, _POINT__VECT, _POLYEDRE__VECT, _RGBA__VECT, _LIST__VECT, _LOGO__VECT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

