package geogebra.common.euclidian;
@SuppressWarnings("javadoc")
/**
 * Replacement for isInstance checks
 * @author kondr
 *
 */
public enum Test {
	MOVEABLE, ROTATEMOVEABLE, 
	TRANSFORMABLE, DILATEABLE, GEOPOINTND, 
	GEOVECTOR, GEONUMERIC, GEOLIST, GEOAXIS, GEOLINE, GEOCONIC, GEOFUNCTION, GEOPOLYGON, 
	GEOPOLYLINE, GEOPOINT2, GEOVECTORND, GEOLINEND, GEOSEGMENTND, GEOIMPLICITPOLY, 
	GEOCURVECARTESIAN, GEOIMAGE, NUMBERVALUE, GEOELEMENT, PATH, TRANSLATEABLE, 
	DIRECTIONND, GEOCONICND, GEOCOORDSYS2D, GEOQUADRICND, 
	GEOQUADRIC3D, GEOPOLYGON3D, GEOCOORDSYS1D, REGION3D
}