#!/bin/sh

# Creates all needed portable versions of GeoGebra.
# Requires python3 with zlib support and ImageMagick convert.
# Please put all Java Runtime Environments to ../../../../.. (jre*.bin),
# they can be downloaded from http://www.oracle.com/technetwork/java/javase/downloads/jre-6u26-download-400751.html.
# The result .tar.gz will be put into ../../../../build/.

# @author Zoltan Kovacs <zoltan@geogebra.org>

. ../../autobuild.conf

TARGET_DIR=$WWWDIR/installer
mkdir -p $TARGET_DIR

# 1. Testing prerequisities
VERSION_STRING=`cat ../../../../build/unpacked/version.txt`
if [ "$VERSION_STRING" = "" ]; then
 echo "Please build GeoGebra first."
 exit 1
 fi

if [ "$PYTHON3" = "" ]; then
 PYTHON3=`which python3 2>/dev/null`
 if [ "$PYTHON3" = "" ]; then
  echo "Python3 is required to run this script."
  exit 1
  fi
 fi

umask 0002 # trying to ensure g+w rights for all created files automatically

IMAGE_DIR=../../../../geogebra/gui/images/
# This is no longer needed, because geogebra.png is present in repository:
# convert $IMAGE_DIR/geogebra32.png png:$IMAGE_DIR/geogebra.png || {
#     echo ImageMagick convert is required to run this script.
#     exit 1
#     }

# 2. Packaging
for i in ../../../../installer/jre/jre*.bin; do
    chmod a+x $i
    python3 ./create_geogebra_portable.py \
     $VERSION_STRING \
     $i \
      ../../../../build/unpacked \
      $IMAGE_DIR/geogebra.png \
      ../geogebra \
      ../../../../build
     done

# 3. Copying to installer/ directory (deploying):
cd ../../../../build
for i in GeoGebra-Linux-*-Portable*.tar.gz; do
 chmod g+w $i
 cp $i $TARGET_DIR
 
 # Copying to Google Code:
 if [ "$GC_USER" != "" -a "$GC_PASS" != "" ]; then
  EXTRA=""
  echo $i | grep x86_64 && EXTRA=" (64 bit)"
  # TEMPORARILY DISABLED
  # $SVNDIR/geogebra/desktop/scripts/autobuild/googlecode_upload.py -s "GeoGebra Portable $VERSION_STRING for Linux$EXTRA" \
  #  -p geogebra -u $GC_USER -w "$GC_PASS" -l Test,,OpSys-Linux,Type-Archive $i
  fi
 done

