#!/bin/sh

# Creates all needed portable versions of GeoGebra.
# Requires python3 with zlib support and ImageMagick convert.
# Please put all Java Runtime Environments to ../../../../.. (jre*.bin),
# they can be downloaded from http://www.oracle.com/technetwork/java/javase/downloads/jre-6u26-download-400751.html.
# The result .tar.bz2 will be put into ../../../../build/.

# @author Zoltan Kovacs <zoltan@geogebra.org>

. ../../autobuild.conf

TARGET_DIR=$WWWDIR/installer
mkdir -p $TARGET_DIR

# 1. Testing prerequisities
VERSION_STRING=`cat ../../../../build/unpacked/version.txt`
if [ "$VERSION_STRING" = "" ]; then
 echo "Please build GeoGebra first."
 exit 1
 fi

if [ "$PYTHON3" = "" ]; then
 PYTHON3=`which python3 2>/dev/null`
 if [ "$PYTHON3" = "" ]; then
  echo "Python3 is required to run this script."
  exit 1
  fi
 fi

umask 0002 # trying to ensure g+w rights for all created files automatically

IMAGE_DIR=../../../../geogebra/gui/images/
# This is no longer needed, because geogebra.png is present in repository:
# convert $IMAGE_DIR/geogebra32.png png:$IMAGE_DIR/geogebra.png || {
#     echo ImageMagick convert is required to run this script.
#     exit 1
#     }

# 2. Packaging
# 2/1. Copying to a temporary directory and removing unnecessary files
rm -fR unpacked
cp -a ../../../../build/unpacked unpacked
cd unpacked
rm -f *windows* *macosx* vernier* javagiac-win*.jar javagiac-mac*.jar *.jnilib *.dylib jd2xx*.jar
unzip -o javagiac-linux32.jar libjavagiac.so
unzip -o javagiac-linux64.jar libjavagiac64.so
rm javagiac-linux*.jar # Preserving the .so files only
cd ..

# 2/2. Calling Christian's script for packaging
python3 ./create_geogebra_portable.py \
     $VERSION_STRING \
     ../../../../installer/jre \
     unpacked \
     $IMAGE_DIR/geogebra.png \
     ../geogebra \
     ./remove-jre-unused \
     ../../../../build

# 3. Copying to installer/ directory (deploying):
cd ../../../../build
i=`ls -1 GeoGebra-Linux-Portable*.tar.bz2`
chmod g+w $i
cp $i $TARGET_DIR

# Copying to Google Code:
if [ "$GC_USER" != "" -a "$GC_PASS" != "" ]; then
 $SVNDIR/geogebra/desktop/scripts/autobuild/googlecode_upload.py -s "GeoGebra Portable $VERSION_STRING for Linux" \
  -p geogebra -u $GC_USER -w "$GC_PASS" -l Test,,OpSys-Linux,Type-Archive $i
 fi
