pipeline {
    agent {label 'electron'}
    triggers { 
        cron('H 10,19 * * 1-5') 
    }
    stages {
        stage('Get Web JS'){
            steps {
                sh "bash get-from-autotest.sh ${env.GIT_BRANCH}"
            }
        }

        stage('Build') {
            steps {
                sh '''
                   npm install
                   npx http-server -p 8888 content & npx wait-on http://localhost:8888
                   npx cypress run --env userAgent="Chrome iPad" --spec="cypress/integration/**/*-iPad.spec.js" || true
                   npx cypress run || true
                   '''
            }
            post {
                always {
                    junit '**/ui-tests.*.xml' 
                    archiveArtifacts 'cypress/videos/**'
                }
            }
        }
    }

    post {
        always { cleanAndNotify() }
    }
}