#!/bin/sh

WIXDIR=../wix35 # You can override this by using a default value in autobuild.conf

./create-license
./create-wxs

test -r ../../autobuild.conf || {
 echo "Cannot find ../../autobuild.conf (make sure you edit autobuild.conf.dist first)"
 exit 1
 }
. ../../autobuild.conf

test -r $WIXDIR/candle.exe || {
 echo WiX is not installed into $WIXDIR
 exit 1
 }
 
# Don't hack here. Assume the Wine version is OK.
# WINEVERSION=`wine --version | sed s/"\."/""/g | sed s/wine\-//`
# VERSIONOK=`expr $WINEVERSION '>=' 1320`
#
# if [ "$VERSIONOK" != "1" ]; then
#  echo Wine is almost surely too old to run this program, get at least 1.3.20
#  exit 2
#  fi

test -r ../../../../build/installer/windows/GeoGebra.exe || {
 echo GeoGebra Windows Install does not seem to be built, run../../buildggb42 first
 }

# Copying needed files here:
cp ../../../../build/unpacked/* .
cp ../../../../installer/geogebra.ico .
cp ../../../../build/installer/windows/GeoGebra.exe .
cp ../../../../installer/by-nc-sa-3.0.txt .
cp ../../../../installer/forum.ico .
cp ../../../../installer/gpl-3.0.txt .
mkdir -p unsigned
cp ../../../../build/unsigned/unpacked/* unsigned

GGBVERSION=`cat ../../../../build/unpacked/version.txt`
GGBVERSION_DASHED=`echo $GGBVERSION | tr . -`
MSIFILE=GeoGebra-Windows-Installer-$GGBVERSION_DASHED.msi

wine $WIXDIR/candle.exe -ext WiXUtilExtension GeoGebra.wxs
wine $WIXDIR/light.exe -sval -ext WixUIExtension -ext WiXUtilExtension GeoGebra.wixobj

mv GeoGebra.msi $MSIFILE

if [ "$MSISIGN" = 1 ]; then
 # Copying the unsigned MSI file and signatures to the Windows box:
 ncftpput -u $MSIFTPUSER -p $MSIFTPPASS -P $MSIFTPPORT $MSISERVER $MSIFTPDIR $MSIFILE
 # Assuming that a PVX key already created.
 # Signing the file in Windows by using signtool.exe:
 ssh -p $MSISSHPORT -i $MSISSHKEY $MSISSHUSER@$MSISERVER cmd /c "$MSIMSSDKDIR\\signtool.exe" \
  sign /f "$MSIFTPDIRFULL\\igi-keystore.pfx" $MSIFTPDIRFULL\\$MSIFILE
 # Copying the signed file back to here:
 rm $MSIFILE
 ncftpget -u $MSIFTPUSER -p $MSIFTPPASS -P $MSIFTPPORT $MSISERVER . $MSIFTPDIR/$MSIFILE
 fi

echo "Now you can run 'msiexec /i $MSIFILE' to test GeoGebra Windows Installer on Unix"

