#!/bin/sh
# Creates the wix-license.rtf file automatically.
F=wix-license.rtf

# Creating workfile:
cat head.rtf > $F

# Appending the license file to the RTF:
cat ../../../../geogebra/gui/_license.txt | awk '{printf ("%s\\par\r\n", $0)}' >> $F
/usr/bin/printf "}\x0d\n\00" >> $F
