function touch(){var Z='',W=' top: -1000px;',ub='" for "gwt:onLoadErrorFn"',sb='" for "gwt:onPropertyErrorFn"',db='");',vb='#',Ub='.cache.js',xb='/',Db='//',Rb='5C6D31C9167ABD15B10AD0244DD34399',Tb=':',Sb=':1',mb='::',bc=':moduleBase',Hb=';',Y='<!doctype html>',$='<html><head><\/head><body><\/body><\/html>',pb='=',wb='?',rb='Bad handler "',X='CSS1Compat',bb='Chrome',ab='DOMContentLoaded',R='DUMMY',Kb='Unexpected exception in locale detection, using default: ',Jb='_',ac='__gwtDevModeHook:touch',Ib='__gwt_Locale',Qb='ar',Cb='base',Ab='baseUrl',M='begin',S='body',L='bootstrap',zb='clear.cache.gif',ob='content',Fb='default',_b='end',cb='eval("',N='gwt.codesvr.touch=',O='gwt.codesvr=',$b='gwt/clean/clean-2.css',tb='gwt:onLoadErrorFn',qb='gwt:onPropertyErrorFn',nb='gwt:property',ib='head',Yb='href',T='iframe',yb='img',fb='javascript',U='javascript:""',Vb='link',Zb='loadExternalRefs',Eb='locale',Gb='locale=',jb='meta',Lb='mobile.user.agent',Mb='mobilesafari',hb='moduleRequested',gb='moduleStartup',kb='name',Nb='not_mobile',V='position:absolute; width:0; height:0; border:none; left: -1000px;',Wb='rel',eb='script',Ob='selectingPermutation',Q='startup',Xb='stylesheet',P='touch',Pb='touch.devmode.js',Bb='touch.nocache.js',lb='touch::',_='undefined';var p=window;var q=document;s(L,M);function r(){var a=p.location.search;return a.indexOf(N)!=-1||a.indexOf(O)!=-1}
function s(a,b){if(p.__gwtStatsEvent){p.__gwtStatsEvent({moduleName:P,sessionId:p.__gwtStatsSessionId,subSystem:Q,evtGroup:a,millis:(new Date).getTime(),type:b})}}
touch.__sendStats=s;touch.__moduleName=P;touch.__errFn=null;touch.__moduleBase=R;touch.__softPermutationId=0;touch.__computePropValue=null;touch.__getPropMap=null;touch.__gwtInstallCode=function(){};touch.__gwtStartLoadingFragment=function(){return null};var t=function(){return false};var u=function(){return null};__propertyErrorFunction=null;var v=p.__gwt_activeModules=p.__gwt_activeModules||{};v[P]={moduleName:P};var w;function x(){z();return w}
function y(){z();return w.getElementsByTagName(S)[0]}
function z(){if(w){return}var a=q.createElement(T);a.src=U;a.id=P;a.style.cssText=V+W;a.tabIndex=-1;q.body.appendChild(a);w=a.contentDocument;if(!w){w=a.contentWindow.document}w.open();var b=document.compatMode==X?Y:Z;w.write(b+$);w.close()}
function A(k){function l(a){function b(){if(typeof q.readyState==_){return typeof q.body!=_&&q.body!=null}return /loaded|complete/.test(q.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(q.removeEventListener){q.removeEventListener(ab,d,false)}if(e){clearInterval(e)}}}
if(q.addEventListener){q.addEventListener(ab,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=y();var f=x();var g;if(navigator.userAgent.indexOf(bb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(cb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(db));g=f.createElement(eb);g.language=fb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(eb);g.language=fb;g.text=c[i];e.appendChild(g);d(e,g)}}}
touch.onScriptDownloaded=function(a){l(function(){m(a)})};s(gb,hb);var n=q.createElement(eb);n.src=k;q.getElementsByTagName(ib)[0].appendChild(n)}
touch.__startLoadingFragment=function(a){return D(a)};touch.__installRunAsyncCode=function(a){var b=y();var c=x().createElement(eb);c.language=fb;c.text=a;b.appendChild(c);b.removeChild(c)};function B(){var c={};var d;var e;var f=q.getElementsByTagName(jb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(kb),k;if(j){j=j.replace(lb,Z);if(j.indexOf(mb)>=0){continue}if(j==nb){k=i.getAttribute(ob);if(k){var l,m=k.indexOf(pb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=Z}c[j]=l}}else if(j==qb){k=i.getAttribute(ob);if(k){try{d=eval(k)}catch(a){alert(rb+k+sb)}}}else if(j==tb){k=i.getAttribute(ob);if(k){try{e=eval(k)}catch(a){alert(rb+k+ub)}}}}}u=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;touch.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(vb);if(b==-1){b=a.length}var c=a.indexOf(wb);if(c==-1){c=a.length}var d=a.lastIndexOf(xb,Math.min(c,b));return d>=0?a.substring(0,d+1):Z}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=q.createElement(yb);b.src=a+zb;a=e(b.src)}return a}
function g(){var a=u(Ab);if(a!=null){return a}return Z}
function h(){var a=q.getElementsByTagName(eb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Bb)!=-1){return e(a[b].src)}}return Z}
function i(){var a=q.getElementsByTagName(Cb);if(a.length>0){return a[a.length-1].href}return Z}
function j(){var a=q.location;return a.href==a.protocol+Db+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==Z){k=h()}if(k==Z){k=i()}if(k==Z&&j()){k=e(q.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return touch.__moduleBase+a}
function E(){var h=[];var i;function j(a,b){var c=h;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var k=[];var l=[];function m(a){var b=l[a](),c=k[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
l[Eb]=function(){var b=null;var c=Fb;try{if(!b){var d=q.cookie;var e=d.indexOf(Gb);if(e>=0){var f=d.indexOf(Hb,e);if(f<0){f=d.length}b=d.substring(e+7,f)}}if(!b){b=p[Ib]}if(b){c=b}while(b&&!t(Eb,b)){var g=b.lastIndexOf(Jb);if(g<0){b=null;break}b=b.substring(0,g)}}catch(a){alert(Kb+a)}p[Ib]=c;return b||Fb};k[Eb]={ar:0,'default':1};l[Lb]=function(){return /(android|iphone|ipod|ipad)/i.test(window.navigator.userAgent)?Mb:Nb};k[Lb]={mobilesafari:0,not_mobile:1};t=function(a,b){return b in k[a]};touch.__getPropMap=function(){var a={};for(var b in k){if(k.hasOwnProperty(b)){a[b]=m(b)}}return a};touch.__computePropValue=m;p.__gwt_activeModules[P].bindings=touch.__getPropMap;s(L,Ob);if(r()){return D(Pb)}var n;try{j([Qb,Nb],Rb);j([Fb,Nb],Rb+Sb);n=h[m(Eb)][m(Lb)];var o=n.indexOf(Tb);if(o!=-1){i=parseInt(n.substring(o+1),10);n=n.substring(0,o)}}catch(a){}touch.__softPermutationId=i;return D(n+Ub)}
function F(){if(!p.__gwt_stylesLoaded){p.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=q.createElement(Vb);b.setAttribute(Wb,Xb);b.setAttribute(Yb,D(a));q.getElementsByTagName(ib)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
s(Zb,M);c($b);s(Zb,_b)}
B();touch.__moduleBase=C();v[P].moduleBase=touch.__moduleBase;var G=E();if(p){p.__gwt_activeModules[P].canRedirect=true}var H=ac;var I=p.sessionStorage[H];if(I&&!p[H]){p[H]=true;var J=q.createElement(eb);p[H+bc]=C();J.src=I;var K=q.getElementsByTagName(ib)[0];K.insertBefore(J,K.firstElementChild||K.children[0]);return false}F();s(L,_b);A(G);return true}
touch.succeeded=touch();