function touch(){var Y='',V=' top: -1000px;',tb='" for "gwt:onLoadErrorFn"',rb='" for "gwt:onPropertyErrorFn"',cb='");',ub='#',gc='.cache.js',wb='/',Cb='//',fc=':',lb='::',kc=':moduleBase',Gb=';',X='<!doctype html>',Z='<html><head><\/head><body><\/body><\/html>',ob='=',vb='?',qb='Bad handler "',W='CSS1Compat',ab='Chrome',_='DOMContentLoaded',Q='DUMMY',ec="GWT module 'touch' may need to be (re)compiled",Jb='Unexpected exception in locale detection, using default: ',Ib='_',jc='__gwtDevModeHook:touch',Hb='__gwt_Locale',Lb='android',Bb='base',zb='baseUrl',L='begin',Pb='blackberry',R='body',K='bootstrap',yb='clear.cache.gif',nb='content',Eb='default',ic='end',bb='eval("',Qb='file://',_b='gecko',ac='gecko1_8',M='gwt.codesvr.touch=',N='gwt.codesvr=',sb='gwt:onLoadErrorFn',pb='gwt:onPropertyErrorFn',mb='gwt:property',hb='head',$b='ie6',Zb='ie8',Yb='ie9',S='iframe',xb='img',Mb='ipad',Ob='iphone',Nb='ipod',eb='javascript',T='javascript:""',hc='loadExternalRefs',Db='locale',Fb='locale=',ib='meta',gb='moduleRequested',fb='moduleStartup',Xb='msie',jb='name',Sb='no',Ub='opera',Kb='phonegap.env',U='position:absolute; width:0; height:0; border:none; left: -1000px;',Wb='safari',db='script',cc='selectingPermutation',P='startup',O='touch',dc='touch.devmode.js',Ab='touch.nocache.js',kb='touch::',$='undefined',bc='unknown',Tb='user.agent',Vb='webkit',Rb='yes';var o=window;var p=document;r(K,L);function q(){var a=o.location.search;return a.indexOf(M)!=-1||a.indexOf(N)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:O,sessionId:o.__gwtStatsSessionId,subSystem:P,evtGroup:a,millis:(new Date).getTime(),type:b})}}
touch.__sendStats=r;touch.__moduleName=O;touch.__errFn=null;touch.__moduleBase=Q;touch.__softPermutationId=0;touch.__computePropValue=null;touch.__getPropMap=null;touch.__gwtInstallCode=function(){};touch.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[O]={moduleName:O};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(R)[0]}
function y(){if(v){return}var a=p.createElement(S);a.src=T;a.id=O;a.style.cssText=U+V;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==W?X:Y;v.write(b+Z);v.close()}
function z(k){function l(a){function b(){if(typeof p.readyState==$){return typeof p.body!=$&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(_,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(_,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(ab)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(bb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(cb));g=f.createElement(db);g.language=eb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(db);g.language=eb;g.text=c[i];e.appendChild(g);d(e,g)}}}
touch.onScriptDownloaded=function(a){l(function(){m(a)})};r(fb,gb);var n=p.createElement(db);n.src=k;p.getElementsByTagName(hb)[0].appendChild(n)}
touch.__startLoadingFragment=function(a){return C(a)};touch.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(db);c.language=eb;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(ib);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(jb),k;if(j){j=j.replace(kb,Y);if(j.indexOf(lb)>=0){continue}if(j==mb){k=i.getAttribute(nb);if(k){var l,m=k.indexOf(ob);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=Y}c[j]=l}}else if(j==pb){k=i.getAttribute(nb);if(k){try{d=eval(k)}catch(a){alert(qb+k+rb)}}}else if(j==sb){k=i.getAttribute(nb);if(k){try{e=eval(k)}catch(a){alert(qb+k+tb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;touch.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(ub);if(b==-1){b=a.length}var c=a.indexOf(vb);if(c==-1){c=a.length}var d=a.lastIndexOf(wb,Math.min(c,b));return d>=0?a.substring(0,d+1):Y}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(xb);b.src=a+yb;a=e(b.src)}return a}
function g(){var a=t(zb);if(a!=null){return a}return Y}
function h(){var a=p.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Ab)!=-1){return e(a[b].src)}}return Y}
function i(){var a=p.getElementsByTagName(Bb);if(a.length>0){return a[a.length-1].href}return Y}
function j(){var a=p.location;return a.href==a.protocol+Cb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==Y){k=h()}if(k==Y){k=i()}if(k==Y&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return touch.__moduleBase+a}
function D(){var h=[];var i;var j=[];var k=[];function l(a){var b=k[a](),c=j[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
k[Db]=function(){var b=null;var c=Eb;try{if(!b){var d=p.cookie;var e=d.indexOf(Fb);if(e>=0){var f=d.indexOf(Gb,e);if(f<0){f=d.length}b=d.substring(e+7,f)}}if(!b){b=o[Hb]}if(b){c=b}while(b&&!s(Db,b)){var g=b.lastIndexOf(Ib);if(g<0){b=null;break}b=b.substring(0,g)}}catch(a){alert(Jb+a)}o[Hb]=c;return b||Eb};j[Db]={ar:0,'default':1};k[Kb]=function(){{var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Lb)!=-1||(a.indexOf(Mb)!=-1||(a.indexOf(Nb)!=-1||(a.indexOf(Ob)!=-1||a.indexOf(Pb)!=-1)))){var b=document.location.href;if(b.indexOf(Qb)===0){return Rb}}return Sb}};j[Kb]={no:0,yes:1};k[Tb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Ub)!=-1}())return Ub;if(function(){return b.indexOf(Vb)!=-1}())return Wb;if(function(){return b.indexOf(Xb)!=-1&&p.documentMode>=9}())return Yb;if(function(){return b.indexOf(Xb)!=-1&&p.documentMode>=8}())return Zb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return $b;if(function(){return b.indexOf(_b)!=-1}())return ac;return bc};j[Tb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};s=function(a,b){return b in j[a]};touch.__getPropMap=function(){var a={};for(var b in j){if(j.hasOwnProperty(b)){a[b]=l(b)}}return a};touch.__computePropValue=l;o.__gwt_activeModules[O].bindings=touch.__getPropMap;r(K,cc);if(q()){return C(dc)}var m;try{alert(ec);return;var n=m.indexOf(fc);if(n!=-1){i=parseInt(m.substring(n+1),10);m=m.substring(0,n)}}catch(a){}touch.__softPermutationId=i;return C(m+gc)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(hc,L);r(hc,ic)}
A();touch.__moduleBase=B();u[O].moduleBase=touch.__moduleBase;var F=D();if(o){o.__gwt_activeModules[O].canRedirect=true}var G=jc;var H=o.sessionStorage[G];if(H&&!o[G]){o[G]=true;var I=p.createElement(db);o[G+kc]=B();I.src=H;var J=p.getElementsByTagName(hb)[0];J.insertBefore(I,J.firstElementChild||J.children[0]);return false}E();r(K,ic);z(F);return true}
touch.succeeded=touch();