package org.geogebra.common.kernel.geos;

public enum GProperty {
	FONT, COLOR, POSITION, CAPTION, COMBINED, ANGLE_INTERVAL, COLOR_BG, LINE_STYLE, POINT_STYLE, VISIBLE, LAYER, ANGLE_STYLE, LABEL_STYLE, LENGTH
}
