/*
 * GeoGebra - Dynamic Mathematics for Everyone
 * Copyright (c) GeoGebra GmbH, Altenbergerstr. 69, 4040 Linz, Austria
 * https://www.geogebra.org
 *
 * This file is licensed by GeoGebra GmbH under the EUPL 1.2 licence and
 * may be used under the EUPL 1.2 in compatible projects (see Article 5
 * and the Appendix of EUPL 1.2 for details).
 * You may obtain a copy of the licence at:
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Note: The overall GeoGebra software package is free to use for
 * non-commercial purposes only.
 * See https://www.geogebra.org/license for full licensing details
 */

package org.geogebra.web.linker;

/**
 * A custom linker that generates an app cache manifest with the files generated
 * by the GWT compiler and the static files used by this application.
 * <p>
 * Before using this approach with production code be sure that you understand
 * the limitations of {@link AppCacheLinker}, namely that it sends all
 * permutations to the client.
 *
 * @see AppCacheLinker
 */
public class AppCacheLinkerSettings {
	/**
	 * @return URLs to cache for files not generated by GWT
	 */
	protected static String[] otherCachedFiles() {
		return new String[] {
			"https://www.geogebra.org/apps/deployggb.js",
			"https://www.geogebra.org/3d",
			"https://www.geogebra.org/scientific",
			"https://www.geogebra.org/cas",
			"https://www.geogebra.org/classic",
			"https://www.geogebra.org/geometry",
			"https://www.geogebra.org/graphing",
			"https://www.geogebra.org/notes"
		};
	}
}
