function touch(){var jb='',V=' top: -1000px;',sb='" for "gwt:onLoadErrorFn"',qb='" for "gwt:onPropertyErrorFn"',cb='");',tb='#',Qb='.cache.js',vb='/',Bb='//',Pb=':',kb='::',Zb=':moduleBase',Fb=';',W='<html><head><\/head><body><\/body><\/html>',nb='=',ub='?',pb='Bad handler "',ab='Chrome',_='DOMContentLoaded',Q='DUMMY',Ob="GWT module 'touch' may need to be (re)compiled",Ib='Unexpected exception in locale detection, using default: ',Hb='_',Yb='__gwtDevModeHook:touch',Gb='__gwt_Locale',Ab='base',yb='baseUrl',L='begin',R='body',K='bootstrap',xb='clear.cache.gif',mb='content',Db='default',Xb='end',bb='eval("',M='gwt.codesvr.touch=',N='gwt.codesvr=',Wb='gwt/clean/clean-2.css',rb='gwt:onLoadErrorFn',ob='gwt:onPropertyErrorFn',lb='gwt:property',fb='head',Ub='href',S='iframe',wb='img',Y='javascript',T='javascript:""',Rb='link',Vb='loadExternalRefs',Cb='locale',Eb='locale=',gb='meta',Jb='mobile.user.agent',Kb='mobilesafari',eb='moduleRequested',db='moduleStartup',hb='name',Lb='not_mobile',U='position:absolute; width:0; height:0; border:none; left: -1000px;',Sb='rel',X='script',Mb='selectingPermutation',P='startup',Tb='stylesheet',O='touch',Nb='touch.devmode.js',zb='touch.nocache.js',ib='touch::',$='undefined',Z='var $wnd = window.parent;';var o=window;var p=document;r(K,L);function q(){var a=o.location.search;return a.indexOf(M)!=-1||a.indexOf(N)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:O,sessionId:o.__gwtStatsSessionId,subSystem:P,evtGroup:a,millis:(new Date).getTime(),type:b})}}
touch.__sendStats=r;touch.__moduleName=O;touch.__errFn=null;touch.__moduleBase=Q;touch.__softPermutationId=0;touch.__computePropValue=null;touch.__getPropMap=null;touch.__gwtInstallCode=function(){};touch.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[O]={moduleName:O};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(R)[0]}
function y(){if(v){return}var a=p.createElement(S);a.src=T;a.id=O;a.style.cssText=U+V;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();v.write(W);v.close();var b=v.getElementsByTagName(R)[0];var c=v.createElement(X);c.language=Y;var d=Z;c.text=d;b.appendChild(c)}
function z(k){function l(a){function b(){if(typeof p.readyState==$){return typeof p.body!=$&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(_,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(_,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(ab)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(bb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(cb));g=f.createElement(X);g.language=Y;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(X);g.language=Y;g.text=c[i];e.appendChild(g);d(e,g)}}}
touch.onScriptDownloaded=function(a){l(function(){m(a)})};r(db,eb);var n=p.createElement(X);n.src=k;p.getElementsByTagName(fb)[0].appendChild(n)}
touch.__startLoadingFragment=function(a){return C(a)};touch.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(X);c.language=Y;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(gb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(hb),k;if(j){j=j.replace(ib,jb);if(j.indexOf(kb)>=0){continue}if(j==lb){k=i.getAttribute(mb);if(k){var l,m=k.indexOf(nb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=jb}c[j]=l}}else if(j==ob){k=i.getAttribute(mb);if(k){try{d=eval(k)}catch(a){alert(pb+k+qb)}}}else if(j==rb){k=i.getAttribute(mb);if(k){try{e=eval(k)}catch(a){alert(pb+k+sb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;touch.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(tb);if(b==-1){b=a.length}var c=a.indexOf(ub);if(c==-1){c=a.length}var d=a.lastIndexOf(vb,Math.min(c,b));return d>=0?a.substring(0,d+1):jb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(wb);b.src=a+xb;a=e(b.src)}return a}
function g(){var a=t(yb);if(a!=null){return a}return jb}
function h(){var a=p.getElementsByTagName(X);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(zb)!=-1){return e(a[b].src)}}return jb}
function i(){var a=p.getElementsByTagName(Ab);if(a.length>0){return a[a.length-1].href}return jb}
function j(){var a=p.location;return a.href==a.protocol+Bb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==jb){k=h()}if(k==jb){k=i()}if(k==jb&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return touch.__moduleBase+a}
function D(){var h=[];var i;var j=[];var k=[];function l(a){var b=k[a](),c=j[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
k[Cb]=function(){var b=null;var c=Db;try{if(!b){var d=p.cookie;var e=d.indexOf(Eb);if(e>=0){var f=d.indexOf(Fb,e);if(f<0){f=d.length}b=d.substring(e+7,f)}}if(!b){b=o[Gb]}if(b){c=b}while(b&&!s(Cb,b)){var g=b.lastIndexOf(Hb);if(g<0){b=null;break}b=b.substring(0,g)}}catch(a){alert(Ib+a)}o[Gb]=c;return b||Db};j[Cb]={ar:0,'default':1};k[Jb]=function(){return /(android|iphone|ipod|ipad)/i.test(window.navigator.userAgent)?Kb:Lb};j[Jb]={mobilesafari:0,not_mobile:1};s=function(a,b){return b in j[a]};touch.__getPropMap=function(){var a={};for(var b in j){a[b]=l(b)}return a};touch.__computePropValue=l;o.__gwt_activeModules[O].bindings=touch.__getPropMap;r(K,Mb);if(q()){return C(Nb)}var m;try{alert(Ob);return;var n=m.indexOf(Pb);if(n!=-1){i=parseInt(m.substring(n+1),10);m=m.substring(0,n)}}catch(a){}touch.__softPermutationId=i;return C(m+Qb)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(Rb);b.setAttribute(Sb,Tb);b.setAttribute(Ub,C(a));p.getElementsByTagName(fb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(Vb,L);c(Wb);r(Vb,Xb)}
A();touch.__moduleBase=B();u[O].moduleBase=touch.__moduleBase;var F=D();if(o){o.__gwt_activeModules[O].canRedirect=true}var G=Yb;var H=o.sessionStorage[G];if(H&&!o[G]){o[G]=true;var I=p.createElement(X);o[G+Zb]=B();I.src=H;var J=p.getElementsByTagName(fb)[0];J.insertBefore(I,J.firstElementChild);return false}E();r(K,Xb);z(F);return true}
touch.succeeded=touch();