package org.geogebra.common.gui;

public enum AccessibilityGroup {
	ALGEBRA_ITEM, ALGEBRA_CLOSE, UNDO, REDO, RESET_BUTTON,
	SETTINGS_BUTTON, ZOOM_NOTES_DRAG_VIEW,
	ZOOM_NOTES_PLUS, ZOOM_NOTES_MINUS,
	ZOOM_NOTES_HOME, PLAY_BUTTON, ZOOM_PANEL_HOME,
	ZOOM_PANEL_PLUS, ZOOM_PANEL_MINUS, FULL_SCREEN, PAGE_LIST_OPEN,
	NOTES_TOOLBAR_HEADER, NOTES_TOOL_SELECT, NOTES_TOOL_TOOLS, NOTES_TOOL_MEDIA,
	NOTES_COLOR_PANEL, NOTES_COLOR_CUSTOM, NOTES_PEN_THICKNESS_SLIDER,
	GEO_ELEMENT, MENU, SPEECH;
}
