package org.geogebra.test.commands;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class CommandSignatures {
	private static HashMap<String, List<Integer>> syntaxes = new HashMap<>();

	static {

		addSyntax("Mod", 2, 2);
		addSyntax("Div", 2, 2);
		addSyntax("Min", 1, 2, 1, 2, 3);
		addSyntax("Max", 1, 2, 1, 2, 3);
		addSyntax("LCM", 1, 2);
		addSyntax("GCD", 1, 2);
		addSyntax("Expand", 1);
		addSyntax("Factor", 1);
		addSyntax("Simplify", 1, 1);
		addSyntax("PrimeFactors", 1);
		addSyntax("CompleteSquare", 1);
		addSyntax("ToBase", 2);
		addSyntax("FromBase", 2);
		addSyntax("Division", 2, 2);
		addSyntax("Divisors", 1);
		addSyntax("DivisorsList", 1);
		addSyntax("DivisorsSum", 1);
		addSyntax("IsPrime", 1);
		addSyntax("LeftSide", 1);
		addSyntax("NextPrime", 1);
		addSyntax("RightSide", 1);
		addSyntax("PreviousPrime", 1);
		addSyntax("Line", 2, 2, 2);
		addSyntax("Ray", 2, 2);
		addSyntax("AngularBisector", 2, 3);
		addSyntax("OrthogonalLine", 2, 2, 2);
		addSyntax("Tangent", 2, 2, 2, 2, 2, 2);
		addSyntax("Segment", 2, 2);
		addSyntax("Slope", 1);
		addSyntax("Angle", 1, 2, 2, 3, 3);
		addSyntax("InteriorAngles", 1);
		addSyntax("Direction", 1);
		addSyntax("Point", 1, 2, 2, 1);
		addSyntax("Midpoint", 1, 1, 1, 2);
		addSyntax("LineBisector", 1, 2);
		addSyntax("Intersect", 2, 3, 3, 4, 4);
		addSyntax("IntersectPath", 2, 2);
		addSyntax("Distance", 2, 2, 2);
		addSyntax("Length", 1, 3, 3, 3, 3);
		addSyntax("Radius", 1);
		addSyntax("CircleArc", 3);
		addSyntax("Arc", 3, 3, 3, 3);
		addSyntax("Sector", 3, 3);
		addSyntax("CircleSector", 3);
		addSyntax("CircumcircleSector", 3);
		addSyntax("CircumcircleArc", 3);
		addSyntax("Polygon", 1, 3, 3);
		addSyntax("RigidPolygon", 1, 3, 3);
		addSyntax("Area", 1, 1, 3);
		addSyntax("Circumference", 1);
		addSyntax("Perimeter", 1, 1, 1);
		addSyntax("Locus", 2, 2, 2, 2);
		addSyntax("Centroid", 1);
		addSyntax("TriangleCenter", 4);
		addSyntax("Barycenter", 2);
		addSyntax("Trilinear", 6);
		addSyntax("Cubic", 4);
		addSyntax("TriangleCurve", 4);
		addSyntax("Vertex", 1, 1, 1, 2, 2);
		addSyntax("PolyLine", 1, 3);
		addSyntax("PointIn", 1);
		addSyntax("AffineRatio", 3);
		addSyntax("CrossRatio", 4);
		addSyntax("ClosestPoint", 2, 2);
		addSyntax("ClosestPointRegion", 2);
		addSyntax("Prove", 1);
		addSyntax("ProveDetails", 1);
		addSyntax("AreCollinear", 3);
		addSyntax("AreParallel", 2);
		addSyntax("AreConcyclic", 4);
		addSyntax("ArePerpendicular", 2);
		addSyntax("AreEqual", 2);
		addSyntax("AreConcurrent", 3);
		addSyntax("AreCongruent", 2);
		addSyntax("IsTangent", 2);
		addSyntax("LocusEquation", 1, 2, 2);
		addSyntax("Envelope", 2);
		addSyntax("Volume", 1);
		addSyntax("Difference", 2);
		addSyntax("Text", 1, 2, 2, 3, 4);
		addSyntax("LaTeX", 1, 2, 3);
		addSyntax("LetterToUnicode", 1);
		addSyntax("TextToUnicode", 1);
		addSyntax("UnicodeToText", 1);
		addSyntax("UnicodeToLetter", 1);
		addSyntax("FractionText", 1, 1);
		addSyntax("SurdText", 1, 1, 2);
		addSyntax("ScientificText", 1, 2);
		addSyntax("TableText", 3, 4);
		addSyntax("VerticalText", 1, 2);
		addSyntax("RotateText", 2);
		addSyntax("Ordinal", 1);
		addSyntax("ContinuedFraction", 1, 2, 3);
		addSyntax("If", 2, 3);
		addSyntax("CountIf", 2, 3);
		addSyntax("IsInteger", 1);
		addSyntax("KeepIf", 2, 3);
		addSyntax("Relation", 1, 2);
		addSyntax("Defined", 1);
		addSyntax("IsInRegion", 2);
		addSyntax("Root", 1, 2, 3);
		addSyntax("Roots", 3);
		addSyntax("TurningPoint", 1);
		addSyntax("Polynomial", 1, 1);
		addSyntax("Function", 3, 1);
		addSyntax("Extremum", 1, 3);
		addSyntax("CurveCartesian", 5);
		addSyntax("ParametricDerivative", 1);
		addSyntax("Derivative", 1, 1, 2, 2, 2, 3);
		addSyntax("NDerivative", 1);
		addSyntax("Integral", 1, 2, 3, 4);
		addSyntax("IntegralBetween", 4, 5);
		addSyntax("LowerSum", 4);
		addSyntax("LeftSum", 4);
		addSyntax("RectangleSum", 5);
		addSyntax("TaylorSeries", 3);
		addSyntax("UpperSum", 4);
		addSyntax("TrapezoidalSum", 4);
		addSyntax("Limit", 2);
		addSyntax("LimitBelow", 2);
		addSyntax("LimitAbove", 2);
		addSyntax("Factors", 1, 1);
		addSyntax("Degree", 1);
		addSyntax("Coefficients", 1, 1);
		addSyntax("PartialFractions", 1);
		addSyntax("Numerator", 1, 1);
		addSyntax("Denominator", 1, 1);
		addSyntax("ComplexRoot", 1);
		addSyntax("SolveODE", 1, 2, 5, 6, 8);
		addSyntax("SlopeField", 1, 2, 3, 7);
		addSyntax("Iteration", 3, 4);
		addSyntax("PathParameter", 1);
		addSyntax("Asymptote", 1);
		addSyntax("CurvatureVector", 2);
		addSyntax("Curvature", 2);
		addSyntax("OsculatingCircle", 2);
		addSyntax("IterationList", 3, 4);
		addSyntax("RootList", 1);
		addSyntax("ImplicitCurve", 1, 1);
		addSyntax("ImplicitDerivative", 1);
		addSyntax("NSolveODE", 4);
		addSyntax("Spline", 1, 2, 3);
		addSyntax("Normalize", 1, 1);
		addSyntax("SVD", 1);
		addSyntax("Ellipse", 3, 3, 3);
		addSyntax("Hyperbola", 3, 3, 3);
		addSyntax("SecondAxisLength", 1);
		addSyntax("SecondAxis", 1);
		addSyntax("Directrix", 1);
		addSyntax("Diameter", 2, 2);
		addSyntax("Conic", 5, 6);
		addSyntax("FirstAxis", 1);
		addSyntax("Circle", 2, 2, 2, 3);
		addSyntax("Incircle", 3);
		addSyntax("Semicircle", 2);
		addSyntax("FirstAxisLength", 1);
		addSyntax("Parabola", 2);
		addSyntax("Focus", 1);
		addSyntax("Parameter", 1);
		addSyntax("Center", 1);
		addSyntax("Polar", 2, 2);
		addSyntax("Excentricity", 1);
		addSyntax("Eccentricity", 1);
		addSyntax("Axes", 1);
		addSyntax("Sort", 1, 2);
		addSyntax("First", 1, 1, 2, 2, 2);
		addSyntax("Last", 1, 1, 2, 2);
		addSyntax("Take", 3, 2, 3, 2);
		addSyntax("RemoveUndefined", 1);
		addSyntax("Reverse", 1);
		addSyntax("Element", 2, 3, 4);
		addSyntax("IndexOf", 2, 2, 3, 3);
		addSyntax("Append", 2, 2);
		addSyntax("Join", 1, 3);
		addSyntax("Flatten", 1);
		addSyntax("Insert", 3, 3);
		addSyntax("Sequence", 1, 2, 3, 4, 5);
		addSyntax("SelectedElement", 1);
		addSyntax("SelectedIndex", 1);
		addSyntax("RandomElement", 1);
		addSyntax("Product", 1, 2, 2, 4);
		addSyntax("Frequency", 1, 2, 2, 2, 3, 4, 5);
		addSyntax("Unique", 1);
		addSyntax("Classes", 2, 3);
		addSyntax("Zip", 6);
		addSyntax("Intersection", 2);
		addSyntax("PointList", 1);
		addSyntax("OrdinalRank", 1);
		addSyntax("TiedRank", 1);
		addSyntax("Union", 2, 2);
		addSyntax("Remove", 2);
		addSyntax("BarChart", 2, 3, 3, 3, 6, 7);
		addSyntax("BoxPlot", 3, 4, 5, 7);
		addSyntax("Histogram", 2, 4, 5);
		addSyntax("HistogramRight", 2, 4, 5);
		addSyntax("DotPlot", 3);
		addSyntax("StemPlot", 1, 2);
		addSyntax("ResidualPlot", 2);
		addSyntax("FrequencyPolygon", 2, 4, 5);
		addSyntax("NormalQuantilePlot", 1);
		addSyntax("FrequencyTable", 2, 2, 2, 3, 4, 5);
		addSyntax("StickGraph", 1, 2, 2, 3);
		addSyntax("StepGraph", 1, 2, 2, 3, 3, 4);
		addSyntax("ContingencyTable", 2, 3, 3, 4);
		addSyntax("Sum", 1, 2, 2, 4);
		addSyntax("Mean", 1, 2);
		addSyntax("mean", 1, 2);
		addSyntax("Variance", 1, 2);
		addSyntax("SD", 1, 2);
		addSyntax("stdev", 1, 2);
		addSyntax("MAD", 1, 2);
		addSyntax("mad", 1, 2);
		addSyntax("SampleVariance", 1, 2);
		addSyntax("SampleSD", 1, 2);
		addSyntax("stdevp", 1, 2);
		addSyntax("Median", 1, 2);
		addSyntax("Q1", 1, 2);
		addSyntax("Q3", 1, 2);
		addSyntax("Mode", 1);
		addSyntax("SigmaXX", 1, 1, 2);
		addSyntax("SigmaXY", 1, 2);
		addSyntax("SigmaYY", 1);
		addSyntax("Covariance", 1, 2);
		addSyntax("SXY", 1, 2);
		addSyntax("SXX", 1, 1);
		addSyntax("SYY", 1);
		addSyntax("MeanX", 1);
		addSyntax("MeanY", 1);
		addSyntax("PMCC", 1, 2);
		addSyntax("SampleSDX", 1);
		addSyntax("SampleSDY", 1);
		addSyntax("SDX", 1);
		addSyntax("SDY", 1);
		addSyntax("FitLineY", 1);
		addSyntax("FitLineX", 1);
		addSyntax("FitPoly", 2, 2);
		addSyntax("FitExp", 1);
		addSyntax("FitLog", 1);
		addSyntax("FitPow", 1);
		addSyntax("Fit", 2, 2);
		addSyntax("FitGrowth", 1);
		addSyntax("FitSin", 1);
		addSyntax("FitLogistic", 1);
		addSyntax("SumSquaredErrors", 2);
		addSyntax("RSquare", 2);
		addSyntax("Sample", 2, 3);
		addSyntax("Shuffle", 1);
		addSyntax("FitImplicit", 2);
		addSyntax("Spearman", 1, 2);
		addSyntax("TTest", 3, 5);
		addSyntax("ZProportionTest", 4);
		addSyntax("ZProportion2Test", 5);
		addSyntax("ZProportionEstimate", 3);
		addSyntax("ZProportion2Estimate", 5);
		addSyntax("ZMeanEstimate", 3, 4);
		addSyntax("ZMean2Estimate", 5, 7);
		addSyntax("ZMeanTest", 4, 5);
		addSyntax("ZMean2Test", 5, 7);
		addSyntax("TTestPaired", 3);
		addSyntax("TTest2", 4, 8);
		addSyntax("TMeanEstimate", 2, 4);
		addSyntax("TMean2Estimate", 4, 8);
		addSyntax("ChiSquaredTest", 1, 2, 2);
		addSyntax("ANOVA", 3);
		addSyntax("Percentile", 2);
		addSyntax("GeometricMean", 1);
		addSyntax("HarmonicMean", 1);
		addSyntax("RootMeanSquare", 1);
		addSyntax("Random", 2, 3);
		addSyntax("RandomNormal", 2);
		addSyntax("RandomUniform", 2, 3);
		addSyntax("RandomBinomial", 2);
		addSyntax("RandomPoisson", 1);
		addSyntax("Normal", 3, 4, 4);
		addSyntax("LogNormal", 3, 4, 4);
		addSyntax("Logistic", 3, 4, 4);
		addSyntax("InverseLogistic", 3);
		addSyntax("InverseNormal", 3);
		addSyntax("nCr", 2);
		addSyntax("Binomial", 2);
		addSyntax("BinomialDist", 2, 3, 4);
		addSyntax("Bernoulli", 2);
		addSyntax("InverseBinomial", 3);
		addSyntax("TDistribution", 2, 3, 3);
		addSyntax("InverseTDistribution", 2);
		addSyntax("FDistribution", 3, 4, 4);
		addSyntax("InverseFDistribution", 3);
		addSyntax("Gamma", 3, 4, 4);
		addSyntax("InverseGamma", 3);
		addSyntax("Cauchy", 3, 4, 4);
		addSyntax("InverseCauchy", 3);
		addSyntax("ChiSquared", 2, 3, 3);
		addSyntax("InverseChiSquared", 2);
		addSyntax("Exponential", 2, 3, 3);
		addSyntax("InverseExponential", 2);
		addSyntax("HyperGeometric", 3, 4, 5);
		addSyntax("InverseHyperGeometric", 4);
		addSyntax("Pascal", 2, 3, 4);
		addSyntax("InversePascal", 3);
		addSyntax("Poisson", 1, 2, 3);
		addSyntax("InversePoisson", 2);
		addSyntax("Weibull", 3, 4, 4);
		addSyntax("InverseWeibull", 3);
		addSyntax("Zipf", 2, 3, 4);
		addSyntax("InverseZipf", 3);
		addSyntax("Triangular", 4, 5, 5);
		addSyntax("Uniform", 3, 4, 4);
		addSyntax("Erlang", 3, 4, 4);
		addSyntax("InverseLogNormal", 3);
		addSyntax("RandomPolynomial", 3);
		addSyntax("RandomDiscrete", 2);
		addSyntax("RandomPointIn", 1, 1, 4);
		addSyntax("ApplyMatrix", 2);
		addSyntax("UnitVector", 1);
		addSyntax("Vector", 1, 2);
		addSyntax("UnitOrthogonalVector", 1, 1, 1);
		addSyntax("OrthogonalVector", 1, 1, 1);
		addSyntax("Invert", 1, 1);
		addSyntax("Transpose", 1);
		addSyntax("ReducedRowEchelonForm", 1);
		addSyntax("Determinant", 1);
		addSyntax("Identity", 1);
		addSyntax("Dimension", 1);
		addSyntax("MatrixRank", 1);
		addSyntax("Mirror", 2, 2, 2);
		addSyntax("Dilate", 2, 3);
		addSyntax("Rotate", 2, 3);
		addSyntax("Translate", 2, 2);
		addSyntax("Shear", 3);
		addSyntax("Stretch", 2, 3);
		addSyntax("CellRange", 2);
		addSyntax("Row", 1);
		addSyntax("Column", 1);
		addSyntax("ColumnName", 1);
		addSyntax("FillRow", 2);
		addSyntax("FillColumn", 2);
		addSyntax("FillCells", 2, 2, 2);
		addSyntax("Cell", 2);
		addSyntax("Rate", 6);
		addSyntax("Periods", 5);
		addSyntax("Payment", 5);
		addSyntax("FutureValue", 5);
		addSyntax("PresentValue", 5);
		addSyntax("CopyFreeObject", 1);
		addSyntax("DataFunction", 2);
		addSyntax("SetColor", 2, 4);
		addSyntax("SetBackgroundColor", 1, 2, 3, 4);
		addSyntax("SetDecoration", 2);
		addSyntax("SetDynamicColor", 4, 5);
		addSyntax("SetConditionToShowObject", 2);
		addSyntax("SetFilling", 2);
		addSyntax("SetLevelOfDetail", 2);
		addSyntax("SetLineThickness", 2);
		addSyntax("SetLineStyle", 2);
		addSyntax("SetPointStyle", 2);
		addSyntax("SetPointSize", 2);
		addSyntax("SetFixed", 2, 3);
		addSyntax("SetTrace", 2);
		addSyntax("Rename", 2);
		addSyntax("HideLayer", 1);
		addSyntax("ShowLayer", 1);
		addSyntax("SetCoords", 3, 4);
		addSyntax("Pan", 2);
		addSyntax("CenterView", 1);
		addSyntax("ZoomIn", 1, 2, 4);
		addSyntax("SetSeed", 1);
		addSyntax("ZoomOut", 1, 2);
		addSyntax("SetActiveView", 1, 1);
		addSyntax("SelectObjects", 0, 3);
		addSyntax("SetLayer", 2);
		addSyntax("SetCaption", 2);
		addSyntax("SetLabelMode", 2);
		addSyntax("SetTooltipMode", 2);
		addSyntax("UpdateConstruction", 0, 1);
		addSyntax("SetValue", 2, 2, 3);
		addSyntax("PlaySound", 1, 1, 3, 5);
		addSyntax("ReadText", 1);
		addSyntax("ParseToNumber", 2);
		addSyntax("ParseToFunction", 2);
		addSyntax("StartAnimation", 0, 1, 3, 4);
		addSyntax("Delete", 1);
		addSyntax("Slider", 9);
		addSyntax("Checkbox", 0, 1, 1, 2);
		addSyntax("Textfield", 0, 1);
		addSyntax("Button", 0, 1);
		addSyntax("Execute", 1, 4);
		addSyntax("GetTime", 0, 1);
		addSyntax("ShowLabel", 2);
		addSyntax("SetAxesRatio", 2);
		addSyntax("SetVisibleInView", 3);
		addSyntax("ShowAxes", 0, 1, 2);
		addSyntax("ShowGrid", 0, 1, 2);
		addSyntax("AttachCopyToView", 2, 6);
		addSyntax("RunClickScript", 1);
		addSyntax("RunUpdateScript", 1);
		addSyntax("SetPerspective", 1);
		addSyntax("StartLogging", 5);
		addSyntax("StopLogging", 0);
		addSyntax("StartRecord", 0, 1);
		addSyntax("Repeat", 4);
		addSyntax("Voronoi", 1);
		addSyntax("ConvexHull", 1);
		addSyntax("MinimumSpanningTree", 1);
		addSyntax("DelauneyTriangulation", 1);
		addSyntax("TravelingSalesman", 1);
		addSyntax("ShortestDistance", 4);
		addSyntax("Corner", 1, 2, 2, 2);
		addSyntax("AxisStepX", 0);
		addSyntax("AxisStepY", 0);
		addSyntax("ConstructionStep", 0, 1);
		addSyntax("Object", 1);
		addSyntax("Name", 1);
		addSyntax("SlowPlot", 1, 2);
		addSyntax("ToolImage", 1, 2, 3);
		addSyntax("DynamicCoordinates", 3, 4);
		addSyntax("SetConstructionStep", 1);
		addSyntax("Maximize", 2, 2);
		addSyntax("Minimize", 2, 2);
		addSyntax("ExportImage", 4);
		addSyntax("Bottom", 1);
		addSyntax("Cone", 2, 3, 3);
		addSyntax("Cube", 1, 3, 3);
		addSyntax("Cylinder", 2, 3);
		addSyntax("Dodecahedron", 1, 3, 3);
		addSyntax("Ends", 1);
		addSyntax("Icosahedron", 1, 3, 3);
		addSyntax("Octahedron", 1, 3, 3);
		addSyntax("Plane", 1, 1, 2, 2, 2, 3, 3);
		addSyntax("QuadricSide", 1);
		addSyntax("Surface", 2, 3, 9);
		addSyntax("Tetrahedron", 1, 3, 3);
		addSyntax("Top", 1);
		addSyntax("Sphere", 2, 2);
		addSyntax("Prism", 2, 2, 3);
		addSyntax("Pyramid", 2, 2, 5);
		addSyntax("PlaneBisector", 1, 2);
		addSyntax("OrthogonalPlane", 2, 2);
		addSyntax("InfiniteCone", 3, 3, 3);
		addSyntax("InfiniteCylinder", 2, 3, 3);
		addSyntax("IntersectConic", 2, 2);
		addSyntax("Height", 1);
		addSyntax("Net", 2, 6);
		addSyntax("SetViewDirection", 0, 1, 2);
		addSyntax("SetSpinSpeed", 1);
		addSyntax("Turtle", 0);
		addSyntax("TurtleForward", 2);
		addSyntax("TurtleBack", 2);
		addSyntax("TurtleLeft", 2);
		addSyntax("TurtleRight", 2);
		addSyntax("TurtleUp", 1);
		addSyntax("TurtleDown", 1);
		addSyntax("IFactor", 1);
		addSyntax("CommonDenominator", 2);
		addSyntax("Cross", 2);
		addSyntax("Dot", 2);
		addSyntax("Eliminate", 2);
		addSyntax("GroebnerLex", 1, 2);
		addSyntax("GroebnerDegRevLex", 1, 2);
		addSyntax("GroebnerLexDeg", 1, 2);
		addSyntax("NIntegral", 1, 3);
		addSyntax("NInvert", 1);
		addSyntax("NSolve", 1);
		addSyntax("NSolutions", 1);
		addSyntax("Solutions", 1);
		addSyntax("Solve", 1);
		addSyntax("Laplace", 1, 2, 3);
		addSyntax("InverseLaplace", 1, 2, 3);
		addSyntax("ToComplex", 1);
		addSyntax("ToPolar", 1, 1);
		addSyntax("ToPoint", 1);
		addSyntax("TrigExpand", 1, 2);
		addSyntax("TrigSimplify", 1);
		addSyntax("TrigCombine", 1, 2);
	}

	private static void addSyntax(String string, int... lengths) {
		ArrayList<Integer> list = new ArrayList<>();
		for(int l: lengths){
			list.add(l);
		}
		syntaxes.put(string, list);
	}

	/**
	 * @param cmdName
	 *            command name
	 * @return numbers of arguments per syntax
	 */
	public static List<Integer> getSigneture(String cmdName) {
		return syntaxes.get(cmdName);
	}
}
