#!/bin/bash

# A wrapper to run nodegiac.js from this folder.
# You may need to fine tune this script if some settings/folders
# are different on your system.

# Support for Bash on Windows
# https://stackoverflow.com/a/38859331/1044586
if grep -q Microsoft /proc/version; then
 NODE="/mnt/c/Program Files (x86)/nodejs/node.exe"
 dirname=`dirname $0`
 dirname1=`readlink -f $dirname`
 dirname2=${dirname1:6} # Removing /mnt/c
 "$NODE" "$dirname2/nodegiac.js" $*
else
# Support other systems as well
 dirname="$(cd "$(dirname "$0")" && pwd -P)"
 node "$dirname/nodegiac.js" $*
fi
