package org.geogebra.common.gui.menu;

/**
 * The icons that the menu items can show.
 */
public enum Icon {
	APP_CLASSIC, APP_GRAPHING, APP_SCIENTIFIC, APP_GEOMETRY, APP_CAS_CALCULATOR, APP_GRAPHING3D,
	CLEAR, SAVE, HOURGLASS_EMPTY, GEOGEBRA, SETTINGS, HELP, PRINT, SEARCH, EXPORT_FILE,
	EXPORT_IMAGE, ASSIGNMENT, SCHOOL, QUESTION_ANSWER, BUG_REPORT, INFO, SIGN_IN, SIGN_OUT,
	USER_ICON, DOWNLOAD, FOLDER
}
