package org.geogebra.common.gui.menu;

public enum Icon {
	APP_CLASSIC, APP_GRAPHING, APP_SCIENTIFIC, APP_GEOMETRY, APP_CAS_CALCULATOR, APP_GRAPHING3D,
	CLEAR, HOURGLASS_EMPTY, GEOGEBRA, SETTINGS, HELP,
	SEARCH, EXPORT_FILE, EXPORT_IMAGE, ASSIGNMENT,
	SCHOOL, QUESTION_ANSWER, BUG_REPORT, INFO,
	EXIT_TO_APP, SIGN_OUT, USER_ICON
}
