function web(){var $='',hb='" for "gwt:onLoadErrorFn"',fb='" for "gwt:onPropertyErrorFn"',ib='#',tb='&',Db='.cache.js',kb='/',Ab='7715566BF595128F5039A8A101776A9F',Cb=':',_='::',O='<html><head><\/head><body><\/body><\/html>',cb='=',jb='?',Bb='B9C72353E2D483BCCCF5C706E512BA1B',eb='Bad handler "',T='DOMContentLoaded',J='DUMMY',wb='Unexpected exception in locale detection, using default: ',vb='_',ub='__gwt_Locale',pb='base',nb='baseUrl',E='begin',K='body',D='bootstrap',mb='clear.cache.gif',bb='content',zb='default',rb='en',Kb='end',F='gwt.codesvr.web=',G='gwt.codesvr=',Jb='gwt/clean/clean.css',gb='gwt:onLoadErrorFn',db='gwt:onPropertyErrorFn',ab='gwt:property',W='head',Hb='href',L='iframe',lb='img',Q='javascript',M='javascript:""',Eb='link',Ib='loadExternalRefs',qb='locale',sb='locale=',X='meta',V='moduleRequested',U='moduleStartup',Y='name',N='position:absolute; width:0; height:0; border:none; left: -1000px; top: -1000px; !important',Fb='rel',P='script',xb='selectingPermutation',I='startup',Gb='stylesheet',S='undefined',R='var $wnd = window.parent;',H='web',yb='web.devmode.js',ob='web.nocache.js',Z='web::';var q=window;var r=document;t(D,E);function s(){var a=q.location.search;return a.indexOf(F)!=-1||a.indexOf(G)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:H,sessionId:q.__gwtStatsSessionId,subSystem:I,evtGroup:a,millis:(new Date).getTime(),type:b})}}
web.__sendStats=t;web.__moduleName=H;web.__errFn=null;web.__moduleBase=J;web.__softPermutationId=0;web.__computePropValue=null;var u=function(){return false};var v=function(){return null};__propertyErrorFunction=null;function w(f){var g;function h(){j();return g}
function i(){j();return g.getElementsByTagName(K)[0]}
function j(){if(g){return}var a=r.createElement(L);a.src=M;a.id=H;a.style.cssText=N;a.tabIndex=-1;r.body.appendChild(a);g=a.contentDocument;if(!g){g=a.contentWindow.document}g.open();g.write(O);g.close();var b=g.getElementsByTagName(K)[0];var c=g.createElement(P);c.language=Q;var d=R;c.text=d;b.appendChild(c)}
function k(a){function b(){if(typeof r.readyState==S){return typeof r.body!=S&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=false;if(b()){c=true;a()}var d;function e(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(T,e,false)}if(d){clearInterval(d)}}}
if(r.addEventListener){r.addEventListener(T,function(){e()},false)}var d=setInterval(function(){if(b()){e()}},50)}
function l(a){var b=i();var c=h().createElement(P);c.language=Q;c.text=a;b.appendChild(c);b.removeChild(c)}
web.onScriptDownloaded=function(a){k(function(){l(a)})};t(U,V);var m=r.createElement(P);m.src=f;r.getElementsByTagName(W)[0].appendChild(m)}
function x(){var c={};var d;var e;var f=r.getElementsByTagName(X);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(Y),k;if(j){j=j.replace(Z,$);if(j.indexOf(_)>=0){continue}if(j==ab){k=i.getAttribute(bb);if(k){var l,m=k.indexOf(cb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=$}c[j]=l}}else if(j==db){k=i.getAttribute(bb);if(k){try{d=eval(k)}catch(a){alert(eb+k+fb)}}}else if(j==gb){k=i.getAttribute(bb);if(k){try{e=eval(k)}catch(a){alert(eb+k+hb)}}}}}v=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;web.__errFn=e}
function y(){function e(a){var b=a.lastIndexOf(ib);if(b==-1){b=a.length}var c=a.indexOf(jb);if(c==-1){c=a.length}var d=a.lastIndexOf(kb,Math.min(c,b));return d>=0?a.substring(0,d+1):$}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(lb);b.src=a+mb;a=e(b.src)}return a}
function g(){var a=v(nb);if(a!=null){return a}return $}
function h(){var a=r.getElementsByTagName(P);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(ob)!=-1){return e(a[b].src)}}return $}
function i(){var a=r.getElementsByTagName(pb);if(a.length>0){return a[a.length-1].href}return $}
var j=g();if(j==$){j=h()}if(j==$){j=i()}if(j==$){j=e(r.location.href)}j=f(j);return j}
function z(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return web.__moduleBase+a}
function A(){var i=[];var j;function k(a,b){var c=i;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
m[qb]=function(){var b=null;var c=rb;try{if(!b){var d=location.search;var e=d.indexOf(sb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(tb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=v(qb)}if(!b){b=q[ub]}if(b){c=b}while(b&&!u(qb,b)){var h=b.lastIndexOf(vb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(wb+a)}q[ub]=c;return b||rb};l[qb]={'default':0,en:1};u=function(a,b){return b in l[a]};web.__computePropValue=n;t(D,xb);if(s()){return z(yb)}var o;try{k([zb],Ab);k([rb],Bb);o=i[n(qb)];var p=o.indexOf(Cb);if(p!=-1){j=o.substring(p+1);o=o.substring(0,p)}}catch(a){}web.__softPermutationId=j;return z(o+Db)}
function B(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=r.createElement(Eb);b.setAttribute(Fb,Gb);b.setAttribute(Hb,z(a));r.getElementsByTagName(W)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
t(Ib,E);c(Jb);t(Ib,Kb)}
x();web.__moduleBase=y();var C=A();B();t(D,Kb);w(C)}
web();