#!/bin/sh
# Updates GeoGebra from SVN repository
# @author Zoltan Kovacs <zoltan@geogebra.org>

if [ "$0" != "./buildggb42" ]; then
 echo "Usage:
  ./buildggb42 [revision]  Compiles and installs numbered version into test42"
  exit 1
  fi

# 1. Start and loading configuration
date
echo "$0: start"

test -r autobuild.conf || {
 echo "$0: Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 exit 1
 }
. ./autobuild.conf
cd $SVNDIR/geogebra

umask 0002 # trying to ensure g+w rights for all created files automatically

if [ "$1" != "" ]; then
 REVISION_PARAM=" -r $1 "
 echo "$0: Using revision $1"
 fi

# 2. Updating source files
rm -fR org # not sure why SVN cannot handle this properly (org/mathpiper), http://stackoverflow.com/questions/1608836/folders-skipped-when-updating-svn
ant delete-sources
$SVN_COMMAND $REVISION_PARAM update --accept theirs-full --force > .svn-update
$SVN_COMMAND info | grep Revision | awk '{print $2}' > scripts/autobuild/.revision
WARNINGS=`chmod -R g+rw $SVNDIR/geogebra 2>&1 | wc -l | awk '{print $1}'`
echo "$0: $WARNINGS warnings during chmod'ing source files"

# 3. Setting global variables
export JAVA_HOME
export JDK_HOME=$JAVA_HOME
export JAVACMD=$JAVA_HOME/bin/java
export ANT_OPTS="-Xmx1024m"

# 4. Building

# 4/1. Deleting *.class files and compiling grammar with javacc
ant delete-classes compile-grammar-cl || exit 3

# 4/2. Setting classpath for ecj (required for Java 5)
CP=`cd $SVNDIR/geogebra/scripts/autobuild; ./classpath`

# 4/3. Setting bootclasspath
BCP=../java150-rt.jar

# 4/4. Creating *.class files
echo "$0: Creating class files"
$JAVACMD $ANT_OPTS -jar lib/build/ecj-3.6.2.jar -1.5 -source 1.5 -target 1.5 -classpath $CP -bootclasspath $BCP\
 -time -proceedOnError -g .  > .ecjlog 2>&1
tail -1 .ecjlog
echo ", see .ecjlog for more details" # .ecjlog has no \n before EOF

# 4/5. Packaging
ant geogebra || exit 3

# 4/6. Testing packed jars
cd $SVNDIR/geogebra/scripts/autobuild
./test-packed-jars
cd $SVNDIR/geogebra

# 4/7. Creating Windows and Mac OS X installer
ant -f installer.xml # installer-clean installer-macosx

# Making sure that all files have group writable permissions
WARNINGS=`chmod -R g+rw $SVNDIR/geogebra 2>&1 | wc -l | awk '{print $1}'`
echo "$0: $WARNINGS warnings during chmod'ing build files"

# 5. Setting local variables
MYVER=`cat build/unpacked/version.txt`
MYDIR=test42

if [ "$MYDIR" = "" -o "$WWWDIR" = "" ]; then
 echo "$0: Fatal error, MYDIR=$MYDIR, WWWDIR=$WWWDIR, exiting for safety reasons"
 exit 2
 fi

# 6. Copying and text replacing
cd build
if [ "$MYDIR" != "4.2" ]; then
 rm -fR $WWWDIR/$MYDIR || exit 4 # Be careful!
 fi
mkdir -p $WWWDIR/$MYDIR || exit 4
chmod g+rwx $WWWDIR/$MYDIR || exit 4

echo "$0: (re)creating $WWWDIR/$MYDIR directory"

# 6/1. Copying dynamically generated files (autobuild)
cp -R * $WWWDIR/$MYDIR || exit 4
echo "$0: dynamically generated files copied"

# 6/2. Copying static files
cp -R $SVNDIR/geogebra/webstart/4.2/* $WWWDIR/$MYDIR || exit 4
mkdir -p $WWWDIR/$MYDIR/usb
cp $SVNDIR/geogebra/lib/vernier_ccsd* $WWWDIR/$MYDIR/usb || exit 4
echo "$0: static files copied"

# 6/3. Moving *.html and *.jnlp to unpacked/ and rewriting static URLs:
# http://www.geogebra.org/webstart/4.2/unsigned -> http://www.geogebra.org/webstart/$MYDIR/unsigned/unpacked
# http://www.geogebra.org/webstart/4.2/usb-gomotion.ggb -> http://www.geogebra.org/webstart/$MYDIR/usb-gomotion.ggb
# http://www.geogebra.org/webstart/4.2/debug -> http://www.geogebra.org/webstart/$MYDIR/debug
# http://www.geogebra.org/webstart/4.2/ -> http://www.geogebra.org/webstart/$MYDIR/unpacked/
# </title> -> ($MYVER) </title>

# The 1st and 4th change is needed to prevent testing the packed version.

# In addition, removing those lines which have the "association mime-type" text.

cd $WWWDIR/$MYDIR
for i in *.html *.jnlp; do
    cat $i | \
     sed s/"http:\/\/www.geogebra.org\/webstart\/4.2\/unsigned"/"http:\/\/www.geogebra.org\/webstart\/$MYDIR\/unsigned\/unpacked"/g | \
     sed s/"http:\/\/www.geogebra.org\/webstart\/4.2\/usb-gomotion"/"http:\/\/www.geogebra.org\/webstart\/$MYDIR\/usb-gomotion.ggb"/g | \
     sed s/"http:\/\/www.geogebra.org\/webstart\/4.2\/debug"/"http:\/\/www.geogebra.org\/webstart\/$MYDIR\/debug"/g | \
     sed s/"http:\/\/www.geogebra.org\/webstart\/4.2\/"/"http:\/\/www.geogebra.org\/webstart\/$MYDIR\/unpacked"/g | \
     sed s/"<\/title>"/" ($MYVER)<\/title>"/g | \
     grep -v "association mime-type" \
     > unpacked/$i
    rm $i || exit 4
    cp unpacked/$i $i || exit 4 # Some files in some subdirectories may still refer to the original file.
    echo "$0: $i is rewritten"
    done

# 6/4. Copying unsigned geogebra.jar and geogebra_main.jar to $WWWDIR/$MYDIR/minimal:
mkdir -p $WWWDIR/$MYDIR/minimal
for i in geogebra geogebra_main; do
 cp $SVNDIR/geogebra/build/unsigned/unpacked/$i.jar $WWWDIR/$MYDIR/minimal
 done
 
# 7. Finally, making sure that all files have group writable permissions
WARNINGS=`chmod -R g+rw $WWWDIR/$MYDIR 2>&1 | wc -l | awk '{print $1}'`
echo "$0: $WARNINGS warnings during chmod'ing web files"

# 8. rsync-www on demand
if [ "$WWW_REMOTEDIR" != "" ]; then
 echo "$0: Copying all files to $WWW_REMOTEDIR"
 cd $SVNDIR/geogebra/scripts/autobuild
 ./rsync-www 2>&1 >.rsync-www
 fi

date
echo "$0: end"
