#!/bin/sh
# Compares two directories with JAR files.
#
# Usage:
#   cmp-jars DIR1 DIR2
#
# It is assumed that DIR1 and DIR2 do not contain subdirectores.
# The script assumes that both directories contain jar files with
# identical names. If they don't the script stops with an error.

# @author Ralf Hemmecke <hemmecke@gmail.com>
# License: GPLv3+

d1=$1
d2=$2
jars=$(cd $d1; find . -type f -name '*.jar')
if test -n "$( ((cd $d1; find . -type f -name '*.jar'); (cd $d2; find . -type f -name '*.jar'))|sort|uniq -u)"; then
    echo "Directories do not contain identical jar file names."
    exit 1;
fi

# Every jar file will be extracted to a temporary directory under /tmp.
TDIR=/tmp/D$$
D1=$TDIR/d1
D2=$TDIR/d2
rm -rf $TDIR # just in case there are leftovers
for jar in $jars; do
    echo === $jar ===
    rm -rf $D1 $D2
    mkdir -p $D1 $D2
    unzip $d1/$jar -d $D1 >/dev/null 2>&1
    unzip $d2/$jar -d $D2 >/dev/null 2>&1
    (cd $D1; find . -type f -exec cmp {} $D2/{} \;)
    missing="$( ((cd $D1; find .); (cd $D2; find .))|sort|uniq -u)"
    if test -n "$missing"; then
	echo "Files that are not in both jars: $missing"
    fi
done

# clean up
rm -rf $TDIR
