#!/bin/sh
# Pushes files to be deployed towards all mirror servers.
# To use it, set up remote mirror servers described at http://www.geogebra.org/trac/wiki/MirrorServers,
# create an ssh login there, and create an private/public key-pair by using ssh-keygen.
# Copy the public part to the remote machine by adding it to .ssh/authorized_keys2.
# This will provide automatic file copying between the host running this script
# and the remote machine.
# Edit details for each mirror server in mirrors.conf.
# The remote server must ensure that http://$IP/webstart
# is the same directory as "ssh -p $PORT $RUSER@$IP; cd $DIR".

# @author Zoltan Kovacs <zoltan@geogebra.org>

# 1. Start and loading configuration
date
echo "$0: start"

test -r autobuild.conf || {
 echo "$0: Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 exit 1
 }
. ./autobuild.conf

# 2. Setting local variables
MYDIR=4.2
cd $WWWDIR/$MYDIR
MYVER=`cat unpacked/version.txt`

cat $SVNDIR/geogebra/scripts/autobuild/mirrors.conf | grep -v "^#" | grep -v "^$" | while read IP PORT RUSER DIR; do
 echo "Copying files to $RUSER@$IP:$PORT/$DIR..."
 # (Re)creating directories (-n is important to prevent reading data from cat):
 ssh -n -l $RUSER -p $PORT $IP "mkdir -p $DIR; cd $DIR; mkdir -p $MYDIR; cd $MYDIR; mkdir -p jnlp packed unpacked unsigned/packed unsigned/unpacked usb"
 # Copying files to root directory:
 scp -P $PORT forum.gif wiki.jpg geogebra64.gif *.var $RUSER@$IP:$DIR/$MYDIR
 # Copying files to packed directory:
 scp -P $PORT packed/*.jar.pack.gz $RUSER@$IP:$DIR/$MYDIR/packed
 # Copying files to packed directory:
 scp -P $PORT unpacked/*.jar $RUSER@$IP:$DIR/$MYDIR/unpacked
 # Copying files to unsigned directory:
 scp -P $PORT unsigned/*.jar.var $RUSER@$IP:$DIR/$MYDIR/unsigned
 # Copying files to unsigned/packed directory:
 scp -P $PORT unsigned/packed/*.jar.pack.gz $RUSER@$IP:$DIR/$MYDIR/unsigned/packed
 # Copying files to unsigned/unpacked directory:
 scp -P $PORT unsigned/unpacked/*.jar $RUSER@$IP:$DIR/$MYDIR/unsigned/unpacked
 # Copying files to usb/ directory:
 scp -P $PORT usb/*.jar $RUSER@$IP:$DIR/$MYDIR/usb
 # Symlinking files into jnlp/ for fast webstart:
 ssh -n -l $RUSER -p $PORT $IP "cd $DIR/$MYDIR/unpacked; for i in *.jar; do cd; cd $DIR/$MYDIR/jnlp; rm -f \$i; ln -s ../unpacked/\$i; ln -s ../packed/\$i.pack.gz; done"

 # TODO: Automatic check (by wget)

 done

date
echo "$0: end"
