#!/bin/sh
# Creates a zip file containing geogebra.properties from SVN repository
# Also puts geogebratube translations into the zip.
# @author Zoltan Kovacs <zoltan@geogebra.org>

ZIPDIR=/Users/zoltan/source/translation/gui
DATE=`date +%Y%m%d`
ZIPFILE=geogebra_prop_40_$DATE.zip
TUBE_REPO=file:///opt/repos/tube/trunk # not used yet, but assumed
NAVDIR=/Users/zoltan/navigation

date
echo "$0: start"

test -r autobuild.conf || {
 echo "Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
 exit 1
 }
. ./autobuild.conf

# Updating GeoGebraTube and copy files to the properties directory:
cd $SVNDIR/tube/trunk/languages
$SVN_COMMAND update --accept theirs-full --force
for i in *.properties; do
 NEWNAME=tube_$i
 if [ "$i" = "en.properties" ]; then
  NEWNAME=tube.properties
  fi
 cp $i $SVNDIR/ggb40/geogebra/geogebra/properties/$NEWNAME # renaming
 done
 
# Copying navigation properties to the properties directory:
cd $NAVDIR
for i in *.properties; do
 cp $i $SVNDIR/ggb40/geogebra/geogebra/properties
 done

# Updating GeoGebra properties:
cd $SVNDIR/ggb40/geogebra/geogebra/properties
$SVN_COMMAND update --accept theirs-full --force
cd ../gui
$SVN_COMMAND update --accept theirs-full --force
cp _license.txt ..
cd ..

# Moving old zip file to old/:
mkdir -p $ZIPDIR/old
mv $ZIPDIR/*.zip $ZIPDIR/old

# Zipping:
zip -r $ZIPFILE properties _license.txt -x properties/.svn/\*

# Deploying:
mv $ZIPFILE $ZIPDIR

date
echo "$0: end"
