#!/bin/sh
REPOS="$1"
TXN="$2"
SVNLOOK=/usr/local/bin/svnlook
LOG=/tmp/pre-commit.log

COMMIT_TEXT=`$SVNLOOK log -t $TXN $REPOS`
CHANGED_TEXT=`$SVNLOOK changed -t $TXN $REPOS`
CHANGED_TEXT_CLASS=`$SVNLOOK changed -t $TXN $REPOS | grep ^A | grep "\\.class$\|\\.dll$\|\\.so$\|\\.jnilib$\|\\.db$\|\\.jar$\|\\.ggt$\|\\.userlibraries$|\\.a$|giac\\.js$"`
CHANGED_TEXT_LIB=`$SVNLOOK changed -t $TXN $REPOS | grep ^A | grep trunk/geogebra/desktop/lib`

date >> $LOG
echo "pre-commit tests for $TXN $REPOS" >> $LOG
echo "commit log: $COMMIT_TEXT
committed files: $CHANGED_TEXT" >> $LOG

if [ "$COMMIT_TEXT" = "" ]; then
  echo "" 1>&2
  echo "*** Your commit has been blocked because you did not give any log message." 1>&2
  echo "Please write a log message describing the purpose of your changes and then try committing again." 1>&2
  echo "REJECTED: NO LOG MESSAGE" >> $LOG
  exit 1
 fi

if [ "$CHANGED_TEXT_CLASS" != "" ]; then
  echo "" 1>&2
  echo "*** Your commit has been blocked because you tried to upload a file which type is not allowed." 1>&2
  echo "Such types are: .class, .dll, .so, .jnilib, .db, .jar, .ggt, .userlibraries, .a and giac.js." 1>&2
  echo "Binary files in general should not be part of the repository." 1>&2
  echo "If you think this is an error, please consult the geogebra-dev-tech@googlegroups.com tech mailing list." 1>&2
  echo "REJECTED: CLASS" >> $LOG
  exit 1
 fi

if [ "$CHANGED_TEXT_LIB" != "" ]; then
  echo "" 1>&2
  echo "*** Your commit has been blocked because you tried to upload a file into the trunk/geogebra/desktop/lib directory." 1>&2
  echo "Binary files in general should not be part of the repository." 1>&2
  echo "If you think this is an error, please consult the geogebra-dev-tech@googlegroups.com tech mailing list." 1>&2
  echo "REJECTED: LIB" >> $LOG
  exit 1
 fi
