#!/bin/sh
MYDIR=`pwd`
SVNROOT=../../../../..

find $SVNROOT -name svnignore.txt | sed s/svnignore.txt$//g | sort | while read NAME; do
 cd $MYDIR
 cd $NAME
 echo Processing $NAME
 svn propset -R svn:ignore -F svnignore.txt . > /dev/null
 done

cd $SVNROOT
svn commit -m "Automatic update of propset svn:ignore via for svnignore.txt's by svnignore"
