#!/bin/sh

# Creates a general Linux version of GeoGebra.
# Requires python3.
# The result .tar.gz will be put into ../../../../build/.

# @author Zoltan Kovacs <zoltan@geogebra.org>

. ../../autobuild.conf

TARGET_DIR=$WWWDIR/installer
mkdir -p $TARGET_DIR

# 1. Testing prerequisities:
VERSION_STRING=`cat ../../../../build/unpacked/version.txt`
if [ "$VERSION_STRING" = "" ]; then
 echo "Please build GeoGebra first."
 exit 1
 fi

if [ "$PYTHON3" = "" ]; then
 PYTHON3=`which python3 2>/dev/null`
 if [ "$PYTHON3" = "" ]; then
  echo "Python3 is required to run this script."
  exit 1
  fi
 fi

umask 0002 # trying to ensure g+w rights for all created files automatically

# 2. Packaging hicolor icons:
cd ../../../../icons
tar czf $SVNDIR/geogebra/desktop/scripts/autobuild/linux/generic/hicolor.tgz hicolor
cd $SVNDIR/geogebra/desktop/scripts/autobuild/linux/generic
chmod g+w hicolor.tgz

# 3. Creating package file:
$PYTHON3 ./create_geogebra_linux.py \
 $VERSION_STRING \
 ../../../../build/unpacked \
 ../geogebra \
 ../../../../_LICENSE.txt \
 geogebra.xml \
 geogebra.desktop \
 hicolor.tgz \
 install.sh \
 uninstall.sh \
 install-sh \
 README \
 ../../../../build

# 4. Copying to installer/ directory (deploying):
cd ../../../../build
LINUX_TGZ=geogebra-$VERSION_STRING.tar.gz
chmod g+w $LINUX_TGZ
cp $LINUX_TGZ $TARGET_DIR
# geogebra-3.9.209.0.tar.gz -> GeoGebra-Unixlike-Installer-3-9-209-0.tar.gz
LINUX_TGZ_FINAL=GeoGebra-Unixlike-Installer-$VERSION_STRING.tar.gz
mv $LINUX_TGZ $LINUX_TGZ_FINAL

# 5. Copying to Google Code:
if [ "$GC_USER" != "" -a "$GC_PASS" != "" ]; then
 $SVNDIR/geogebra/desktop/scripts/autobuild/googlecode_upload.py -s "GeoGebra $VERSION_STRING for Linux, Solaris, FreeBSD and other POSIX" \
  -p geogebra -u $GC_USER -w "$GC_PASS" -l Test,OpSys-Linux,Type-Installer $LINUX_TGZ_FINAL
 fi

