#!/bin/bash
#---------------------------------------------
# Script to install GeoGebra Icons for Oxygen Icon Theme
#---------------------------------------------

#---------------------------------------------
# Used environment variables:
#
# INSTALL=<path of install macro> # If unset, './install-sh' will be used. (Distributors may want to set their own install macro.)
#
# CHMOD=<path of chmod macro> # If unset, 'chmod' will be used. (Distributors may want to set their own chmod macro.)
#
# BINDIR=<path for executable binary files> # If unset, 'usr/bin' will be used.
#
# DATADIR=<path for data files> # If unset, '/usr/share' will be used.
#
# DOCDIR=<path for doc files> # If unset, '/usr/share/doc' will be used.
#
# CREATE_UNINSTALLER=<boolean> # If unset, 'false' will be used. (Distributors normally have their own uninstaller.)
#
# VERBOSE_MODE=<boolean> # If unset, 'false' will be used.

#---------------------------------------------
# If $INSTALL not set, use './install-sh'.

if [ -z "$INSTALL" ]; then
	INSTALL="./install-sh"
fi

#---------------------------------------------
# If $CHMOD not set, use 'chmod'.

if [ -z "$CHMOD" ]; then
	CHMOD="chmod"
fi

#---------------------------------------------
# If $BINDIR not set, use '/usr/bin'.

if [ -z "$BINDIR" ]; then
	BINDIR="/usr/bin"
fi

#---------------------------------------------
# If $DATADIR not set, use '/usr/share'.

if [ -z "$DATADIR" ]; then
	DATADIR="/usr/share"
fi

#---------------------------------------------
# If $DOCDIR not set, use '/usr/share/doc'.

if [ -z "$DOCDIR" ]; then
	DOCDIR='/usr/share/doc'
fi

#---------------------------------------------
# If $CREATE_UNINSTALLER not set, use 'false'.

if [ -z "$CREATE_UNINSTALLER" ]; then
	CREATE_UNINSTALLER="false"
fi

#---------------------------------------------
# If $VERBOSE_MODE not set, use 'false'.

if [ -z "$VERBOSE_MODE" ]; then
	VERBOSE_MODE='false'
fi

#---------------------------------------------
# Install everything.

"$INSTALL" -d -m 755 "$DOCDIR"
"$INSTALL" -d -m 755 "$DOCDIR/packages"
"$INSTALL" -d -m 755 "$DOCDIR/packages/geogebra-oxygen-icons"
"$INSTALL" -m 644 "icons/oxygen/COPYING" "$DOCDIR/packages/geogebra-oxygen-icons"
"$INSTALL" -m 644 "icons/oxygen/README" "$DOCDIR/packages/geogebra-oxygen-icons"
"$INSTALL" -d -m 755 "$DATADIR"
"$INSTALL" -d -m 755 "$DATADIR/icons"
"$INSTALL" -d -m 755 "$DATADIR/icons/oxygen"
for SIZE in 16x16 22x22 32x32 48x48 64x64 128x128 256x256; do
	"$INSTALL" -d -m 755 "$DATADIR/icons/oxygen/$SIZE"
	"$INSTALL" -d -m 755 "$DATADIR/icons/oxygen/$SIZE/mimetypes"
	"$INSTALL" -m 644 "icons/oxygen/$SIZE/mimetypes/application-vnd.geogebra.file.png" "$DATADIR/icons/oxygen/$SIZE/mimetypes"
	cp -d "icons/oxygen/$SIZE/mimetypes/application-vnd.geogebra.tool.png" "$DATADIR/icons/oxygen/$SIZE/mimetypes"
done

# Create uninstall script, if $CREATE_UNINSTALLER is not set 'false':
if [ "$CREATE_UNINSTALLER" != "false" ]; then
	"$INSTALL" -d -m 755 "$BINDIR"
	cat > "$BINDIR/uninstall-geogebra-oxygen-icons" << EOF
#!/bin/bash
#---------------------------------------------
# Script to uninstall GeoGebra Icons for Oxygen Icon Theme
#---------------------------------------------

# Define usage function:
func_usage()
{
cat << _USAGE
Usage: uninstall-geogebra-oxygen-icons [Options]

Uninstall GeoGebra Icons for Oxygen Icon Theme

Options:
  --help         Print this help message
  --force        Uninstall without asking questions
_USAGE
}

# Check for options:
FORCE="false"
for i in "\$@"; do
	case "\$i" in
	--help | --hel | --he | --h )
		func_usage; exit 0 ;;
	esac
	if [ "\$i" = '--force' ]; then
		FORCE="true"
	fi
done

# Ask to continue, if option --force is not used:
if [ "\$FORCE" = "false" ]; then
	KDIALOG_possible="false"
	QDBUS_possible="false"
	ZENITY_possible="false"
	XDIALOG_possible="false"
	if [ "\$UID" != "0" ]; then
		KDIALOG_possible="true"
		QDBUS_possible="false"
		ZENITY_possible="false"
		XDIALOG_possible="false"
		type -P kdialog &>/dev/null || KDIALOG_possible="false"
		if [ "\$KDIALOG_possible" = "true" ]; then
			QDBUS_possible="true"
			type -P qdbus &>/dev/null || QDBUS_possible="false"
		else
			ZENITY_possible="true"
			type -P zenity &>/dev/null || ZENITY_possible="false"
			if [ "\$ZENITY_possible" = "false" ]; then
				XDIALOG_possible="true"
				type -P Xdialog &>/dev/null || XDIALOG_possible="false"
			fi
		fi
	fi
	ANSWER=1
	if [ "\$KDIALOG_possible" = "true" ]; then
		kdialog --caption "GeoGebra Icons for Oxygen Icon Theme" --warningcontinuecancel "This will uninstall GeoGebra Icons for Oxygen Icon Theme."
		ANSWER=\$?
	elif [ "\$ZENITY_possible" = "true" ]; then
		zenity --title="GeoGebra Icons for Oxygen Icon Theme" --warning --text="This will uninstall GeoGebra Icons for Oxygen Icon Theme."
		ANSWER=\$?
	elif [ "\$XDIALOG_possible" = "true" ]; then
		Xdialog --title "GeoGebra Icons for Oxygen Icon Theme" --yesno "This will uninstall GeoGebra Icons for Oxygen Icon Theme.\n\nDo you want to continue?" 0 0
		ANSWER=\$?
	else
		echo "This will uninstall GeoGebra Icons for Oxygen Icon Theme."
		tput bold
		read -p "Do you want to continue? [y/n]: "
		tput sgr0
		case "\$REPLY" in
		y | Y | yes | Yes | YES )
			ANSWER=0 ;;
		esac
	fi
	if [ \$ANSWER != 0 ]; then
		exit 0
	fi
fi

# Uninstall files and show progressbar during installation, if possible and option --force is not used:
if [ "\$KDIALOG_possible" = "true" -a "\$QDBUS_possible" = "true" -a "\$FORCE" = "false" ]; then
	DBUSREF=\`kdialog --caption "GeoGebra Icons for Oxygen Icon Theme" --progressbar "Uninstalling GeoGebra Icons for Oxygen Icon Theme." 1\`
fi
if [ -w "$DOCDIR/packages/geogebra-oxygen-icons/COPYING" ]; then
	rm -f "$DOCDIR/packages/geogebra-oxygen-icons/COPYING"
fi
if [ -w "$DOCDIR/packages/geogebra-oxygen-icons/README" ]; then
	rm -f "$DOCDIR/packages/geogebra-oxygen-icons/README"
fi
rmdir --ignore-fail-on-non-empty "$DOCDIR/packages/geogebra-oxygen-icons"
for SIZE in 16x16 22x22 32x32 48x48 64x64 128x128 256x256; do
	if [ -w "$DATADIR/icons/oxygen/\$SIZE/mimetypes/application-vnd.geogebra.file.png" ]; then
		rm -f "$DATADIR/icons/oxygen/\$SIZE/mimetypes/application-vnd.geogebra.file.png"
	fi
	if [ -w "$DATADIR/icons/oxygen/\$SIZE/mimetypes/application-vnd.geogebra.tool.png" ]; then
		rm -f "$DATADIR/icons/oxygen/\$SIZE/mimetypes/application-vnd.geogebra.tool.png"
	fi
done
if [ "\$KDIALOG_possible" = "true" -a "\$QDBUS_possible" = "true" -a "\$FORCE" = "false" ]; then
	qdbus \$DBUSREF Set "" value 1 >/dev/null
	qdbus \$DBUSREF setLabelText "Uninstallation completed." >/dev/null
	qdbus \$DBUSREF close >/dev/null
fi

# Selfdestruction:
if [ -w "$BINDIR/uninstall-geogebra-oxygen-icons" ]; then
	rm -f "$BINDIR/uninstall-geogebra-oxygen-icons"
fi
EOF
	"$CHMOD" 755 "$BINDIR/uninstall-geogebra-oxygen-icons"
fi

# List pathes of installed files and of files included in installed
# directories, if $VERBOSE_MODE is not set 'false':
if [ "$VERBOSE_MODE" != "false" ]; then
	echo "`tput smul`Files of package 'geogebra-oxygen-icons'`tput sgr0`"
	if [ -e "$BINDIR/uninstall-geogebra-oxygen-icons" ]; then
		echo "$BINDIR/uninstall-geogebra-oxygen-icons"
	fi
	if [ -e "$DOCDIR/packages/geogebra-oxygen-icons/COPYING" ]; then
		echo "$DOCDIR/packages/geogebra-oxygen-icons/COPYING"
	fi
	if [ -e "$DOCDIR/packages/geogebra-oxygen-icons/README" ]; then
		echo "$DOCDIR/packages/geogebra-oxygen-icons/README"
	fi
	for SIZE in 16x16 22x22 32x32 48x48 64x64 128x128 256x256; do
		if [ -e "$DATADIR/icons/oxygen/$SIZE/mimetypes/application-vnd.geogebra.file.png" ]; then
			echo "$DATADIR/icons/oxygen/$SIZE/mimetypes/application-vnd.geogebra.file.png"
		fi
		if [ -e "$DATADIR/icons/oxygen/$SIZE/mimetypes/application-vnd.geogebra.tool.png" ]; then
			echo "$DATADIR/icons/oxygen/$SIZE/mimetypes/application-vnd.geogebra.tool.png"
		fi
	done
fi
