/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package javagiac;

public class SWIGTYPE_p_f_r_q_const__giac__gen_p_q_const__giac__context__giac__gen {
  private long swigCPtr;

  protected SWIGTYPE_p_f_r_q_const__giac__gen_p_q_const__giac__context__giac__gen(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_r_q_const__giac__gen_p_q_const__giac__context__giac__gen() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_r_q_const__giac__gen_p_q_const__giac__context__giac__gen obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

