#!/bin/sh
# Checks if the current build works properly (basic checks) and alarms, if not

# 1. Start and loading configuration
test -r autotest.conf || {
 echo "$0: Cannot find autotest.conf (make sure you edit autotest.conf.dist first)"
 exit 127
 }
test -r autotest.conf && . ./autotest.conf

REVISION=`svn info | grep Revision: | awk '{print $2}'`

./simpletest
RESULT=$?

if [ $RESULT = 1 ]; then
 MESSAGE="A build problem occurred at revision $REVISION"
 fi

if [ $RESULT = 2 ]; then
 MESSAGE="JAR file creation problem at revision $REVISION"
 fi

if [ $RESULT = 3 ]; then
 MESSAGE="There is a problem with the output of simpletest at revision $REVISION"
 fi

if [ $RESULT = 0 ]; then
 MESSAGE="Everything is OK at revision $REVISION"
 # exit 0 # Not sending an email
 fi

# Sending an email to geogebra-dev:
echo $MESSAGE | ssh $REMOTEUSER@www.geogebra.org mail -s "autotest/alarm report" $RECIPIENT
