#!/bin/sh
# If the latest version was not built yet, it builds desktop and web

# 1. Start and loading configuration
test -r autotest.conf || {
 echo "$0: Cannot find autotest.conf (make sure you edit autotest.conf.dist first)"
 exit 127
 }
test -r autotest.conf && . ./autotest.conf

MYDIR=$SVNDIR/geogebra/test/scripts/autotest

./check-if-latest || {
 cd $SVNDIR/geogebra
 find -name '*.gwt.xml' -delete
 $SVN_COMMAND --force update --accept theirs-full
 cd desktop; ant -f kickstart.xml geogebra5-developer-commandline; cd ..
 cd jogl1; ant -f kickstart.xml; cd ..
 cd web; ant -f kickstart.xml geogebraweb-developer-commandline; cd ..
 cd $MYDIR
 ./build-desktop
 ./build-web

 REVISION=`./myrevision`
 echo "The latest revision ($REVISION) has been built now"
 
 cd $REVDIR
 rm -f latest
 ln -s $REVISION latest
 
 exit 0
 }

echo "The latest revision has already been built, no action needed"
exit 1
