#!/bin/sh
# Builds GeoGebraWeb and copies it into $REVDIR/REVISION for testing purposes.

# 1. Start and loading configuration
test -r autotest.conf || {
 echo "$0: Cannot find autotest.conf (make sure you edit autotest.conf.dist first)"
 exit 127
 }
test -r autotest.conf && . ./autotest.conf

WEB_AUTOBUILDDIR=../../../web
WEB_BUILDDIR=war
REVISION=`svn info | grep Revision: | awk '{print $2}'`
mkdir -p $REVDIR/$REVISION
cd $WEB_AUTOBUILDDIR
./build -s OBFUSCATED -c -cg -nl -i $REVDIR/$REVISION/war -- -localWorkers 2 > .buildlog 2>&1 || {
 RESULT=$?
 cp .buildlog $REVDIR/$REVISION/weberrors
 exit $RESULT
 }

# A quick draft compilation for debugging
./build -s PRETTY -nl -u gecko1_8 -i $REVDIR/$REVISION/war-debug -- -draftCompile

echo -n $REVISION > $REVDIR/$REVISION/war/web/version.txt
echo -n $REVISION > $REVDIR/$REVISION/war-debug/web/version.txt

exit 0
