#!/bin/sh
# Runs all JUnit tests

# 1. Start and loading configuration
test -r autotest.conf || {
 echo "$0: Cannot find autotest.conf (make sure you edit autotest.conf.dist first)"
 exit 127
 }
test -r autotest.conf && . ./autotest.conf

MYDIR=$SVNDIR/geogebra/test/scripts/autotest
TESTDIR=$SVNDIR/geogebra/test

cd $TESTDIR

sleep 3 # Dirty hack to ensure xvfb can run properly
xvfb-run -w 3 ./run-junit-tests || exit 1 # Problem running the tests
./junit2sqlite # Copying XML data into an SQL database

ERRORS=`cat .junit-tests-errors`

if [ $ERRORS -gt 0 ]; then
 exit 2 # Errors occured during the JUnit tests
 fi

exit 0 # No error
