#!/bin/sh
# Runs all JUnit tests

# 1. Start and loading configuration
test -r autotest.conf || {
 echo "$0: Cannot find autotest.conf (make sure you edit autotest.conf.dist first)"
 exit 127
 }
test -r autotest.conf && . ./autotest.conf

MYDIR=$SVNDIR/geogebra/test/scripts/autotest
TESTDIR=$SVNDIR/GeoGebraTest

cd $TESTDIR

xvfb-run ./run-junit-tests || exit 1 # Problem running the tests

ERRORS=`cat .junit-tests-errors`

if [ $ERRORS -gt 0 ]; then
 exit 2 # Errors occured during the JUnit tests
 fi

exit 0 # No error
