#!/bin/sh
# Checks if the current build works properly (basic checks)

# 1. Start and loading configuration
test -r autotest.conf || {
 echo "$0: Cannot find autotest.conf (make sure you edit autotest.conf.dist first)"
 exit 127
 }
test -r autotest.conf && . ./autotest.conf

MYDIR=$SVNDIR/test/scripts/autotest

REVISION=`svn info | grep Revision: | awk '{print $2}'`

cd $REVDIR/$REVISION || exit 1 # Build problem

test -r geogebra.jar || exit 2 # Non-existing JAR

xvfb-run timeout -k $SIMPLETESTTIMEOUT \
 java -jar geogebra.jar --regressionFile=simpletest.out $MYDIR/simpletest.ggb \
  >simpletest.stdout 2>simpletest.stderr
