#!/bin/sh
# Compiles GeoGebraWeb via command line.
# @author Zoltan Kovacs <zoltan@geogebra.org>
# Make sure that you run this script from its directory.

# 0. Functions first

# Cleanup
cleanup() {
 LASTEXITCODE=$?
 test -r $WEBDIR/src/geogebra/Web.gwt.xml.orig && {
  echo "* Cleaning up: putting back original Web.gwt.xml"
  cd $WEBDIR/src/geogebra
  mv Web.gwt.xml.orig Web.gwt.xml
  }
 cd $WEBDIR/src/geogebra
 for i in *; do
  test -L $i && {
   echo "* Cleaning up: removing link to $i"
   rm $i
   }
  done
  
 exit $LASTEXITCODE
}

# Sets the classpath. This must be fine tuned
# and maybe tidied up a bit, FIXME
classpath() {
CLASSPATH=\
$GGDIR/web/src:\
$GGDIR/common/src:\
$GGDIR/common/war/WEB-INF/lib:\
$GGDIR/common/src/geogebra/jre:\
$GGDIR/common/src/geogebra/webapache:\
/web/test-classes:\
$GGDIR/web/war/WEB-INF/classes:\
$GWTDIR/gwt-user.jar:\
$GWTDIR/gwt-dev.jar:\
$GWTDIR/validation-api-1.0.0.GA.jar:\
$GWTDIR/validation-api-1.0.0.GA-sources.jar:\
$GGDIR/common/test-classes:\
$GGDIR/common/war/WEB-INF/classes:\
$GWTDIR/gwt-dev.jar

export CLASSPATH
}

# 1. Setting up environment variables

GWTDIR=../gwt-2.4.0 # Override it if needed by using autobuild.conf
XML=`which xml 2>/dev/null`
if [ "$XML" = "" ]; then
 XML=`pwd`/xml
 fi
GGDIR=`cd ..; pwd`

test -r autobuild.conf && . ./autobuild.conf && echo "* Using autobuild.conf for overriding defaults"

# 2. Setting defaults
if [ "$SVNDIR" = "" ]; then
 ORIGDIR=`dirname $0`
 WORKDIR=`cd $ORIGDIR; pwd`
else
 WORKDIR=`cd $SVNDIR/geogebra/web; pwd`
 fi

export GWTDIR
cd $WORKDIR
WEBDIR=`pwd`

VERBOSE=0
USERAGENTS=gecko1_8,safari,ie9,opera
INSTALLDIR=""
XS=0
STYLE=OBFUSCATED
OTHEROPTS=""
JAVAC_CLEANUP=""

trap "cleanup" EXIT 2 9 15

# 3. Reading command line arguments
while [ $# -gt 0 ]; do
 case $1 in
  -h | -help | --help)
   echo "This script builds and installs GeoGebraWeb."
   echo
   echo "Usage: $0 [options]"
   echo " Where options can be (defaults in parentheses):"
   echo "  -h, -help, --help   This help"
   echo "  -u [useragents]     Comma separated list of user agents to compile ($USERAGENTS)"
   echo "  -i [directory]      If set, installs GeoGebraWeb into the given directory (first deletes!)"
   echo "  -x                  XS compilation"
   echo "  -c                  Do a cleanup before javac compilation"
   echo "  -s [style]          Compilation style: OBFUSCATED, PRETTY or DETAILED ($STYLE)"
   echo "  -g [directory]      Use GWT SDK from the given directory ($GWTDIR)"
   echo "  -X [path]           Use XMLStarlet from the given path ($XML)"
   echo "  -v, --verbose       Be verbose whenever possible (see the -H option as well)"
   echo "  -- [options]        Forward the rest options directly to the GWT Compiler"
   echo "  -H                  Show extra options for the GWT Compiler"
   echo
   echo "Example: ./build -X /usr/local/bin/xml -s PRETTY -u safari -i /tmp/ggw -- -draftCompile"
   exit 0
   ;;

  -u)
   shift
   USERAGENTS="$1"
   ;;

  -i)
   shift
   INSTALLDIR="$1"
   ;;

  -X)
   shift
   XML="$1"
   ;;

  -x)
   XS=1
   ;;

  -c)
   JAVAC_CLEANUP=clean
   ;;

  -s)
   shift
   STYLE="$1"
   ;;
   
  -g)
   shift
   GWTDIR="$1"
   ;;

  -v | --verbose)
   VERBOSE=1
   ;;
   
  --)
   shift
   OTHEROPTS=$*
   while [ "$2" != "" ]; do
    shift
    done
   ;;
   
  -H)
   classpath
   java com.google.gwt.dev.Compiler
   exit 0
   ;;

  *)
   echo "Unknown parameter: $1. Use \"$0 -h\" for help."
   exit 1
   ;;

  esac
 shift
 done

if [ "$VERBOSE" = 1 ]; then
 ANT="ant -v"
else
 ANT="ant"
 fi

# 4. Testing configuration
test -d $GWTDIR || {
 echo "Error: No GWT SDK directory exists at $GWTDIR"
 exit 4
}
test -x $XML || {
 echo "Error: No XMLStarlet executable exists at $XML"
 exit 4
 }

GWTDIR=`cd $GWTDIR; pwd` # Making it absolute path

echo "* GWT SDK directory is set to $GWTDIR"
echo "* User agents: $USERAGENTS"
echo "* Compilation style: $STYLE"

# 5. (Re)creating parser
cd ../desktop
$ANT compile-grammar-cl || exit 5

# 6. Compiling web with javac
cd ../web/src/geogebra
ln -s ../../../common/src/com
ln -s ../../../common/src/geogebra/common
ln -s ../../../common/src/geogebra/webapache

cd $WEBDIR
$ANT $JAVAC_CLEANUP javac || exit 6

# 7. Preparing specific compilation
cd ../web/src/geogebra
GWTXML=Web.gwt.xml
cp $GWTXML $GWTXML.orig

cat $GWTXML | \
 $XML ed -u "/module/set-property[@name='user.agent']/@value" -v "$USERAGENTS" > $GWTXML-b

if [ "$XS" = "1" ]; then
 cat $GWTXML-b | \
  $XML ed -d /module/add-linker |\
  $XML ed -s /module -t elem -n "add-linker" -v "" |\
  $XML ed -i /module/add-linker -t attr -n name -v xs > $GWTXML-b2
 mv $GWTXML-b2 $GWTXML-b
 fi

mv $GWTXML-b $GWTXML

# 8. Compiling web with GWT Compiler
classpath
if [ $VERBOSE = 1 ]; then
 echo "Classpath for GWT Compiler is $CLASSPATH"
 fi
java -Xmx512m com.google.gwt.dev.Compiler\
 -style $STYLE -war $GGDIR/web/war -strict $OTHEROPTS geogebra.Web geogebra.web.ggbloaderworker.GgbLoaderWorker || exit 8

# 9. Done!
if [ "$INSTALLDIR" = "" ]; then
 echo "GeoGebraWeb compilation finished. Insert this URL into your browser to test it:"
 echo "file:///$WEBDIR/war/Web.html"
else
 echo "Trying to remove and create $INSTALLDIR..."
 rm -fR $INSTALLDIR
 mkdir -p $INSTALLDIR || exit 9
 cp -a $WEBDIR/war/* $INSTALLDIR
 find $INSTALLDIR -name .svn -or -name WEB-INF | xargs rm -fR
 echo "GeoGebraWeb compilation and installation finished. Insert this URL into your browser:"
 echo "file:///$INSTALLDIR/Web.html"
 fi

exit 0
