#!/bin/sh
# Creates a GeoGebraWeb .zip file.
# Make sure that you run this script from its directory.
# @author Zoltan Kovacs <zoltan@geogebra.org>

# 1. Setting up environment variables
# Override them if needed by using autobuild.conf
test -r autobuild.conf && . ./autobuild.conf && echo "* Using autobuild.conf for overriding defaults"

# 2. Setting defaults
if [ "$SVNDIR" = "" ]; then
 ORIGDIR=`dirname $0`
 WORKDIR=`cd $ORIGDIR; pwd`
else
 WORKDIR=`cd $SVNDIR/geogebra/web; pwd`
 fi

cd $WORKDIR
WEBDIR=`pwd`

test -r war/web/web.nocache.js || {
 echo "GeoGebraWeb does not seem to be compiled. Try running ./build first."
 exit 2
 }

# 3. Creating index.html
echo '<meta http-equiv="refresh" content="0; url=http://wiki.geogebra.org/en/Tutorial:Creating_HTML5_documents_with_GeoGebraWeb"/>' > war/indexhtml
# ./ggb2html -v -i war/GeoGebraWeb.ggb -o indexhtml

# 4. Copying files to the ZIPDIR directory
REVISION=`svn info | grep ^Revision: | awk '{print $2}'`
VERSIONFILE=$WEBDIR/../common/src/geogebra/common/GeoGebraConstants.java
VERSION=`cat $VERSIONFILE | grep "public static final String VERSION\_STRING" \
 | awk '{print $7}' | sed s/\"//g | sed s/";"/""/`
ZIPDIR=GeoGebraWeb-$VERSION
rm -fR $ZIPDIR
cp -a war $ZIPDIR

# 4. Removing unnecessary files
cd $ZIPDIR || exit 41
cp README.txt READMEtxt
rm *.ggb *.txt *.html
mv indexhtml index.html
mv READMEtxt README.txt
rm -fR ggbloadworker WEB-INF
find -name .svn -or -name svnignore.txt | xargs rm -fR
rm -fR web/web.devmode.js web/statictexts css/font
find -name '*.cache.svg' -or -name '*.cache.ttf' -or -name '*.cache.woff' \
 -or -name '*.cache.eot' -or -name '*.cache.otf' | xargs rm

# 5. Adding license file and version
cp $WEBDIR/../desktop/geogebra/gui/_license.txt LICENSE.txt
echo $VERSION > version.txt
echo $REVISION > revision.txt

# 6. Zipping
cd $WEBDIR
rm -f $ZIPDIR.zip
zip -r $ZIPDIR.zip $ZIPDIR

# 7. Done
echo "Done! Result .zip file is in $ZIPDIR.zip."
