#!/bin/sh
# Gets the latest Giac and updates it on the dev server and in kickstart.xml.

TGZ=http://www-fourier.ujf-grenoble.fr/~parisse/giac/emgiac.tgz

# 0. Setting defaults
EMSCRIPTEN=~/emscripten-master
export JAVA_HEAP_SPACE=3072m
test -r autobuild.conf && . ./autobuild.conf && echo "* Using autobuild.conf for overriding defaults"

# 1. Downloading
FILENAME=`basename $TGZ`
wget -O lib/$FILENAME $TGZ
cd lib
WORKDIR=`tar tzf $FILENAME | head -1 | cut -f1 -d/`

# 2. Untarring:
tar xzf $FILENAME
cd $WORKDIR

# 3. Compiling
export PATH=$PATH:$EMSCRIPTEN
cd giac
cat Makefile | grep -v shared > Makefile.new
mv Makefile.new Makefile
make clean
make

# 4. Copying giac.js to the correct place
NAME=giac-`date +%Y%m%d`.js
mv ggbgiac.js $NAME
scp -P $DEV_SERVER_PORT -i $DEV_SERVER_KEY $NAME $DEV_SERVER_LOGIN:$DOWNLOADDIR/../lib/web

# 5. Changing kickstart.xml
cd ../../..
sed -i s/giac-latest\.js/$NAME/g kickstart.xml
svn commit -m "Changing giac to the latest version"
