#!/bin/sh
# Gets the latest Giac and updates it on the dev server and in kickstart.xml.
# @author Zoltan Kovacs <zoltan@geogebra.org>

# This is what to do before running this script:
#
# 1. Use a recent Ubuntu, version 12.04 should work properly.
#
# 2. Get LLVM binaries from http://llvm.org/releases/download.html#3.2 and
#    Put them into your home directory (~). Unzip the bundle and put
#    a symlink to that directory ("llvm"). I.e. ~/llvm should point to
#    your custom llvm installation.
#
# 3. Get a not very recent emscripten, e.g.
#    http://www-fourier.ujf-grenoble.fr/~parisse/giac/emscripten-master.zip
#    may be good enough. Uncompress it into your home folder.
#
# 4. Install node.js as a normal Ubuntu package.
#
# 5. Go to ~/emscripten-master and run ./emcc. Now you have a ~/.emscripten
#    config file created. Change the llvm configuration to use the directory
#    ~/llvm/bin.

# 1. Setting defaults
EMSCRIPTEN=~/emscripten-master
export JAVA_HEAP_SPACE=3072m
test -r autobuild.conf && . ./autobuild.conf && echo "* Using autobuild.conf for overriding defaults"
WORKDIR=../common/src/giac
WEBDIR=`pwd`

# 2. CD'ing to giac directory
cd $WORKDIR

# 3. Compiling
export PATH=$PATH:$EMSCRIPTEN
make clean
make || exit 3

# 4. Copying giac.js to the correct place
NAME=giac-`date +%Y%m%d%H%M`.js
mv giacggb.js $NAME
scp -P $DEV_SERVER_PORT -i $DEV_SERVER_KEY $NAME $DEV_SERVER_LOGIN:$DOWNLOADDIR/../lib/web || exit 4

# 5. Changing kickstart.xml
cd $WEBDIR
sed -i s/giac-[0-9]*\.js/$NAME/g kickstart.xml || exit 5
svn commit -m "Changing giac.js to the latest version in web/kickstart.xml" || exit 5
